### ISSUE TITLE
how to config it for outside eNB base on docket config

### ISSUE THREAD

**Issue by alf-askey** [herlesupreeth/docker_open5gs#10]
hi herlesupreeth

if i base on https://github.com/herlesupreeth/docker_open5gs/ to set up Core network with Volte ,
how config it for my enb (s1ap) connet to mme , because my eNB's IP is not "172.22.x.x"
my topology is 

ENB (192.188.2.151) <-------------> PC(192.188.2.2 can  access internet ) with docket_open5gs(172.22.x.x) 

just modify :
s1ap:
      dev: MME_IF --> ? 
    gtpc:
      dev: MME_IF

**Comment by herlesupreeth** [comment]
Uncomment the following section in docker-compose.yaml file

In mme

```
    # ports:
    #   - "36412:36412/sctp"
```

In sgwu

```
    # ports:
    #   - "2152:2152/udp"
```

In the eNB, set MME IP address as 192.188.2.2

That's it. Dont modify anything else

**Comment by alf-askey** [comment]
thank  Herlesupreeth,
                                   my small cell can get "s1 setup response" successfully 
                                   phone can attach and get ip address successfully.

**Comment by herlesupreeth** [comment]
I forgot to mention one more settings that needs to be changed

In .env file, set 

SGWU_ADVERTISE_IP=192.188.2.2

Then do 

source .env

Then run docker-compose to bring up all the components, then you will have internet
