### ISSUE TITLE
HSS Authorization Rejected in ICSCF

### ISSUE THREAD

**Issue by aprilsmith** [herlesupreeth/docker_open5gs#101]
Hello,

My UE has a problem with a VoLTE registration. After attaching in the LTE NW successfully, UE try to register to the IMS. 
PCSCF send register message to ICSCF with the URI("ims.mnc001.mcc001.3gppnetwork.org), but ICSCF send 403 Forbidden - HSS Authorization Rejected though OP value is saved in FHOSS as the same value as HSS.

I attached the pcap, log and capture file regarding the issue.
Thanks in advance for your help. 
[0819.zip](https://github.com/herlesupreeth/docker_open5gs/files/9379783/0819.zip)

**Comment by herlesupreeth** [comment]
You have not added other non-barred IMPUs for that subscriber and associated with IMPI

Please refer to step "20. Add IMS subscription use in FoHSS as follows from the Web GUI" here - https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/

**Comment by aprilsmith** [comment]
Thanks for your reply.
Does non-barred IMPU means MSISDN associated value? 
But I did not write the MSISDN in my usim. Because IMSI might be used as a substitute for MSISDN.
I would like to know that MSISDN is a mandatory for VoLTE registration.

**Comment by herlesupreeth** [comment]
> Does non-barred IMPU means MSISDN associated value?

No, the IMPI containing IMSI is usually barred because IMSI is a crucial element and must be hidden

> But I did not write the MSISDN in my usim. Because IMSI might be used as a substitute for MSISDN.

IMSI cannot be used as a substitute for MSISDN

MSISDN is used for a number to call not IMSI

**Comment by aprilsmith** [comment]
Thanks for your comment.

I have added other non-barred IMPU according to your comment and referring to step 20
(My IMPU : tel:0198765432100, sip:0198765432100@ims.mnc001.mcc001.3gppnetwork.org, 0198765432100 is not actual number)
MSISDN and IMSI pair is added in OSMOHLR as well.

But "Time-out" issue is happened.

I'd appreciate your help on this matter.
Thanks.
[0830.zip](https://github.com/herlesupreeth/docker_open5gs/files/9450564/0830.zip)

**Comment by herlesupreeth** [comment]
![image](https://user-images.githubusercontent.com/4115839/188323252-098aa538-8234-4eef-94f7-7aac27a00c58.png)

I believe you have programmed your SIM wrong this time. You have programmed IMPI/IMPU as 0198765432100@ims.mnc001.mcc001.3gppnetwork.org, but rather it should have been your <IMSI>@ims.mnc001.mcc001.3gppnetwork.org

**Comment by aprilsmith** [comment]
I have programmed my SIM card as you comment like below,
IMPI  001010000035004@ims.mnc001.mcc001.3gppnetwork.org
IMPU  sip:001010000035004@ims.mnc001.mcc001.3gppnetwork.org

Also IMPU have been modified to  sip:001010000035004@ims.mnc001.mcc001.3gppnetwork.org and tel 001010000035004.

Then, I got a new issue "HSS User Unknown".
Please let know how to solve this issue.

Thanks.
[hssuserunknown.zip](https://github.com/herlesupreeth/docker_open5gs/files/9487986/hssuserunknown.zip)

**Comment by aprilsmith** [comment]
For the this problem, I analyzed the diameter protocol again.

FHoSS send DIAMER_ERROR_USER_UNKNOWN.
Though ICSCF sends AVP User-Name: 001010000035004@ims.mnc001.mcc001.3gppnetwork.org which is already registered in IMPI of FHoSS

![image](https://user-images.githubusercontent.com/47843415/189022231-2e827990-ac60-4feb-87c8-ddb2848ab039.png)

I would appreciate it if you could tell me what more work I should do to solve this problem

**Comment by aprilsmith** [comment]
I didn't catch your meaning of "subscription details entered for that SIM in FhoSS" exactly.

Except IMPI and IMPU, is there any information that needs to be registered in FhoSS?
I attached IMPI and IMPU in my Fhoss. 
Please let me know if you have any additional information.

Thanks for your great cooperation.
[0913.zip](https://github.com/herlesupreeth/docker_open5gs/files/9554539/0913.zip)

**Comment by aprilsmith** [comment]
I can register the UE by correcting the part that was set incorrectly.
Thanks for your help.
