### ISSUE TITLE
Activate dedicated EPS bearer context reject

### ISSUE THREAD

**Issue by justinmarkr** [herlesupreeth/docker_open5gs#107]
Hi @herlesupreeth,

I'm having an error Activate dedicated EPS bearer context reject (Syntactical errors in packet filter). I'm using both samsung A03 UEs. Can you help me to pin point what's wrong with my setup. Thanks!

[Activate dedicated EPS bearer context reject.pcap.zip](https://github.com/herlesupreeth/docker_open5gs/files/9412768/Activate.dedicated.EPS.bearer.context.reject.pcap.zip)
.

**Comment by herlesupreeth** [comment]
Your UE modem LTE release version is 12 where the IPv4 Local Address Type is not supported in Packet Filter (Found in NAS EPS session management messages: Activate dedicated EPS bearer context request (0xc5)).

This scenario was covered as part of smf in open5gs. Make sure smf.yaml has the below section

```
parameter:
    no_ipv4v6_local_addr_in_packet_filter: true

```

**Comment by justinmarkr** [comment]
@herlesupreeth,

Thank you for the quick response. I'm was able to call now after adding the given parameter. Thanks again.
