### ISSUE TITLE
Rx interface issue

### ISSUE THREAD

**Issue by juanantono** [herlesupreeth/docker_open5gs#108]
Hello,

I am trying to REGISTER a VoNR subscriber to Kamailio IMS using UERANSIM-Open5GS(docker):
- UE attaches correctly and tunnel towards ims APN is created successfully
- Connectivity (ping and port 5060) from UE towards PCSCF is OK through uesimtun1 interface
- When generating a REGISTER with SIPP in UERANSIM, PCSCF queries Diameter to PCRF but PCRF replies: **[pcrf] ERROR: No Gx Session (../src/pcrf/pcrf-rx-path.c:190)**

Shouldn't PCSCF contact PCF instead? or should PCRF reply to PCSCF including the requested info?

![image](https://user-images.githubusercontent.com/96539633/186519471-16372dac-fe1e-40f9-83a0-d75f7c319e80.png)

![image](https://user-images.githubusercontent.com/96539633/186519539-3fa9a68c-7411-4755-b43c-2814e52257e6.png)

**Comment by juanantono** [comment]
Further checking, the AAA message contains error: **AVP: Experimental-Result-Code(298) l=12 f=-M- val=IP-CAN_SESSION_NOT_AVAILABLE (5065)**

![image](https://user-images.githubusercontent.com/96539633/186696216-8fe7b4bf-0dfb-4b1c-a926-5e50c0633a19.png)

Here the capture:
[UE_20220824b.zip](https://github.com/herlesupreeth/docker_open5gs/files/9425727/UE_20220824b.zip)

**Comment by herlesupreeth** [comment]
For VoNR, P-CSCF should as per spec talk with PCF (not PCRF) using SBI interface. Kamailio based P-CSCF does not have support for SBI interface to talk with PCF. That's why its not possible to test VoNR at the moment

**Comment by juanantono** [comment]
That is why! thanks @herlesupreeth !
