### ISSUE TITLE
Is it possible to connect LimeSDR (UE) to LimeSDR (ENB)?

### ISSUE THREAD

**Issue by egortaran** [herlesupreeth/docker_open5gs#109]
## Issue Description ##
Hello dear developers and users of srsRAN. I want use LimeSDR like UE. I will describe it with the example

## Setup Details ##
- 2 computers with Ubuntu 20.04
- 2 limeSDR v1.4
- open5gs
- srsRAN 22.04

## Expected Behavior ##
I would like to use the first computer and LimeSDR as ENB. And the second computer and LimeSDR as a UE

## Additional Information ##
I have the following questions:
1. Is it possible to connect the second LimeSDR (UE) to the first LimeSDR (ENB)?
2. Is it possible to call using Asterisk from the first computer to the second?

I will be glad to hear any answer answer, or links to documentation and which section. I used the following documentation. I admit that I may miss something:
- https://docs.srsran.com/en/latest/getting_started.html
- https://docs.srsran.com/en/latest/usermanuals/source/srsue/source/1_ue_intro.html#ue-intro

**Comment by egortaran** [comment]
Yes. Is it possible

**Comment by herlesupreeth** [comment]
Sorry for late response. Yes its possible but Asterisk calling may end up using default bearer rather than dedicated bearer like in VoLTE case.
