### ISSUE TITLE
how to access internet via UPF/SGWU

### ISSUE THREAD

**Issue by alf-askey** [herlesupreeth/docker_open5gs#11]
my topology is
ENB (192.188.2.151) <-------------> PC(192.188.2.2 can access internet ) with docket_open5gs(172.22.x.x)

1) ENB <---> mme     ===> successfully
2) phone can attachd ===> successfully 
3) phone access internet (www.google.com)  ===> fail
---------------------------------------
host's iptable nat POSTROUTING  as the below , how to let docker can access internet ( is it in docker-compose.yaml ?)
Chain POSTROUTING (policy ACCEPT 390 packets, 25239 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  any    !docker0  172.17.0.0/16        anywhere            
    0     0 MASQUERADE  all  --  any    !br-21febb5fcc58  172.22.0.0/24        anywhere            
    0     0 MASQUERADE  tcp  --  any    any     172.22.0.25          172.22.0.25          tcp dpt:3000
    0     0 MASQUERADE  udp  --  any    any     172.22.0.6           172.22.0.6           udp dpt:2152
    0     0 MASQUERADE  tcp  --  any    any     172.22.0.18          172.22.0.18          tcp dpt:http-alt
    0     0 MASQUERADE  sctp --  any    any     172.22.0.10          172.22.0.10          sctp dpt:38412
    0     0 MASQUERADE  sctp --  any    any     172.22.0.9           172.22.0.9           sctp dpt:36412

**Comment by herlesupreeth** [comment]
Always attach a packet capture if you are seeking help in debugging

**Comment by alf-askey** [comment]
sorry i forgot my packet , as the below
[access internet fail.zip](https://github.com/herlesupreeth/docker_open5gs/files/5799741/access.internet.fail.zip)

**Comment by alf-askey** [comment]
logs file as the below 
[amf.log](https://github.com/herlesupreeth/docker_open5gs/files/5799778/amf.log)
[ausf.log](https://github.com/herlesupreeth/docker_open5gs/files/5799779/ausf.log)
[hss.log](https://github.com/herlesupreeth/docker_open5gs/files/5799780/hss.log)
[mme.log](https://github.com/herlesupreeth/docker_open5gs/files/5799781/mme.log)
[nrf.log](https://github.com/herlesupreeth/docker_open5gs/files/5799782/nrf.log)
[pcrf.log](https://github.com/herlesupreeth/docker_open5gs/files/5799783/pcrf.log)
[sgwc.log](https://github.com/herlesupreeth/docker_open5gs/files/5799784/sgwc.log)
[sgwu.log](https://github.com/herlesupreeth/docker_open5gs/files/5799785/sgwu.log)
[smf.log](https://github.com/herlesupreeth/docker_open5gs/files/5799786/smf.log)
[udm.log](https://github.com/herlesupreeth/docker_open5gs/files/5799787/udm.log)
[udr.log](https://github.com/herlesupreeth/docker_open5gs/files/5799788/udr.log)
[upf.log](https://github.com/herlesupreeth/docker_open5gs/files/5799789/upf.log)

**Comment by herlesupreeth** [comment]
Since the SGWU_ADVERTISE_IP was set to internal Container IP the uplink traffic was reachable, please follow instructions here to get the internet working

https://github.com/herlesupreeth/docker_open5gs/issues/10#issuecomment-758390569

**Comment by alf-askey** [comment]
thank Herlesupreeth,

Thank you very much ^0^,  
1)  phone can access internet  
2)  phone 1 can reg IMS and call phone 2 , success packet as the below
[phone1 call phone 2_success.zip](https://github.com/herlesupreeth/docker_open5gs/files/5799981/phone1.call.phone.2_success.zip)

i can do some volte test case ,

**Comment by herlesupreeth** [comment]
Wonderful to hear that. Please close the issue if they are resolved
