### ISSUE TITLE
Wrong Request URI during Registration of UE in IMS

### ISSUE THREAD

**Issue by justinmarkr** [herlesupreeth/docker_open5gs#113]
Hi @herlesupreeth

Can you help me on this. I've tried using CX and with FHOSS in my setup, both setup I'm encountering the wrong Request URI during registration using samsung device.  Sometimes samsung device able to register to the IMS but most of the time it is trying to register with this Request URI: sip:ims.mnc002.mcc515.3gppnetwork.org. I have not encountered the said issue and works perfectly using Vivo, Huawei, and Realme device.

![Snip20220905_2](https://user-images.githubusercontent.com/93913757/188357661-9aef81a1-ba91-45d3-9835-4bbcd0324278.png)

![Snip20220905_3](https://user-images.githubusercontent.com/93913757/188357726-1abb2b78-e7c0-4a5f-9fe3-9deb81386df7.png)
[wrong request URI.pcap.zip](https://github.com/herlesupreeth/docker_open5gs/files/9486568/wrong.request.URI.pcap.zip)

**Comment by herlesupreeth** [comment]
Can you let me know which SIM card you are using? If you are using Sysmocom ISIM then you can program the domain and see if that fixes this. I have seen this issue on Samsung which takes the domain based on the PLMN of the major operator in the country the device was issued.

**Comment by justinmarkr** [comment]
@herlesupreeth yes I'm using Sysmocom ISIM SIM cards. May I ask how can I program the domain?

**Comment by herlesupreeth** [comment]
you can use `--ims-hdomain ims.mnc001.mcc001.3gppnetwork.org` in pySim-prog.py to program domain

**Comment by justinmarkr** [comment]
Hi @herlesupreeth 

I've tried to add the domain when programming the SIM but still encountered the error. Can you confirm if I program the SIM card correctly. Thanks


![Snip20220905_5](https://user-images.githubusercontent.com/93913757/188398156-ae618f17-ac64-4bc5-a158-5974dbbb899e.png)

**Comment by herlesupreeth** [comment]
Following is the command I usually use to program Sysmocom ISIMs

```
./pySim-prog.py -p 0 -x 001 -y 01 -s 8988211900000000004 -i 001011234567896 -k 8baf473f2f8fd09487cccbd7097c6862 --op 11111111111111111111111111111111 -o 8E27B6AF0E692E750F32667A3B14605D -a 72273953 -n exp.zii --msisdn 0698765432100 --epdgid epdg.epc.mnc001.mcc001.pub.3gppnetwork.org --pcscf pcscf.ims.mnc001.mcc001.3gppnetwork.org --ims-hdomain ims.mnc001.mcc001.3gppnetwork.org --impi 001011234567896@ims.mnc001.mcc001.3gppnetwork.org --impu sip:001011234567896@ims.mnc001.mcc001.3gppnetwork.org
```

Make sure to program IMPU, IMPI, PCSCF and IMS domain. This way ISIM details would be used by the phone. If even one is not programmed ISIM wont be activated

**Comment by justinmarkr** [comment]
@herlesupreeth Thanks for the quick reply.  I will try again and feedback the soonest.

**Comment by justinmarkr** [comment]
Hi @herlesupreeth 

I've tried the given command but unfortunately the phone still trying to request to this URI sip:ims.mnc002.mcc515.3gppnetwork.org.

Here's my command:

  ./pySim-prog.py -p 0 -x 001 -y 01 -s 8988211000000605744 -i 001010123456795 -k 00112233445566778899AABBCCDDEEFF -o 7ECC2F637BA2166146D6951A7DAC9AEB -a 44553079 -n TestNetwork --msisdn 9995 --epdgid epdg.epc.mnc001.mcc001.pub.3gppnetwork.org --pcscf pcscf.ims.mnc001.mcc001.3gppnetwork.org --ims-hdomain ims.mnc001.mcc001.3gppnetwork.org --impi 001010123456795@ims.mnc001.mcc001.3gppnetwork.org --impu sip:001010123456795@ims.mnc001.mcc001.3gppnetwork.org

**Comment by herlesupreeth** [comment]
Then, its the phone firmware settings its taking. Can you access Samsung IMS settings via the menu in CoIMS app? there you can override this value

**Comment by justinmarkr** [comment]
I can't access the Samsung IMS settings. I can only access the Testing mode menu.

**Comment by herlesupreeth** [comment]
Then, unfortunately I dont have any other ways to fix this device issue

**Comment by justinmarkr** [comment]
Thank you @herlesupreeth
