### ISSUE TITLE
External Application Server to Communicate with IMS

### ISSUE THREAD

**Issue by justinmarkr** [herlesupreeth/docker_open5gs#115]
Hi @herlesupreeth 

I want to explore external application server like FreeSwitch to communicate with IMS. Have you tried this or from your point of view, is this possible with the current setup? Thank you for usual support.

**Comment by herlesupreeth** [comment]
Yes, its possible. Just need the right Initial Filter Criteria (iFCs) in Fhoss configuration (I haven't tried it)

**Comment by justinmarkr** [comment]
This needs additional codes to work? Not possible using Cx interface?

**Comment by herlesupreeth** [comment]
Its not about coding or interfaces..its purely configuration in FhoSS

**Comment by justinmarkr** [comment]
@herlesupreeth Thanks for the quick response. I'll explore the FhoSS WebUI.

**Comment by justinmarkr** [comment]
Hi @herlesupreeth,

I've tried to configure additional application server, iFC and trigger point in FHoSS web UI but it seems doesn't working. I don't know if I configured it correctly. Not even trigger to communicate with FreeSwitch. Can you give me a hint how to do it properly?

When I'm trying to call from FS to IMS, I'm encountering an error "Contact not found based on Contact-header, trying IP/Port/Proto". I configured the FS to directly forward the SIP call to PCSCF. 

![image](https://user-images.githubusercontent.com/93913757/190561188-9cbb7e47-4e01-49b5-bc12-989c502b3b2b.png)

**Comment by herlesupreeth** [comment]
@justinmarkr I will see whether I can find any material regarding this.

If you could explain more in detail what you are trying to achieve with FS and what usecase you are trying to test I may be of help.

**Comment by justinmarkr** [comment]
Thank you @herlesupreeth 

Here's my usecase:
1. SIP phone/soft phone like zoiper is registered to the FreeSwitch
2. Another UE is registered to IMS with VoLTE

From SIP phone/soft phone I want to call the UE with VoLTE
same thing when call is originated from IMS, a UE with VoLTE will able to call the SIP phone/soft phone

**Comment by herlesupreeth** [comment]
For this, you may not need FS, you need two instances of P-CSCF, one with following flags disabled and another with enabled (currently its enabled by default in repo).

```
#!define WITH_RX
#!define WITH_RX_REG
#!define WITH_RX_CALL
```

The P-CSCF instance with flags disabled should be the one where SIP phone should be attached (rather SIP Server IP).

I haven't tried it myself so can't vouch for its working.

**Comment by justinmarkr** [comment]
Thanks @herlesupreeth

For additional P-CSCF do I need to setup separate mysql and FHoSS for this? I want to use FS to use its other features like IVR, call center setup and able to integrate to 2G network using osmocom.

**Comment by herlesupreeth** [comment]
For additional P-CSCF you just need to have separate mysql. It will share the rest i.e. FhoSS, S-CSCF and I-CSCF

> I want to use FS to use its other features like IVR, call center setup and able to integrate to 2G network using osmocom.

I have heard FS being used for this use case but honestly no idea how to configure the service profile in FhoSS to achieve this routing
