### ISSUE TITLE
volte precondition

### ISSUE THREAD

**Issue by gmaruzz** [herlesupreeth/docker_open5gs#116]
Hello,

I see that the phones who ask for volte precondition (qos) then fail the call after 8 seconds of connection.

As an example, oneplus 7t and 8t

So, it seems that open5gs (or srsran?) do not communicate to phones that resources has been allocated, and then qos volte preconditions are satisfied (des qos:local sendrecv des qos:remote sendrecv)

Seems that can also be satisfied if the bearer is QCI=1, but not sure how to force it, or how to communicate it to phones

I searched all Internet for long time, but I was unable to find info on how these preconditions can be satisfied in docker_open5gs (or similar)

do you have any hints (apart for setting the phones not to require preconditions)?

**Comment by gmaruzz** [comment]
using enb (lte) on 4G, not using 5G

**Comment by herlesupreeth** [comment]
If you are using docker_open5gs (for both srsRAN and Core) then VoLTE precondition should work. But if you are using srsRAN on another machine compiled from source or installed via apt then copy the rb.conf file contents in docker_open5gs/srslte folder to add support for QCI1 bearer creation.

If you could send me a trace of the issue I may be of help.

**Comment by gmaruzz** [comment]
hello, thanks for the prompt answer

I use docker_open5gs for both srsRAN and Core, and I have the correct rb.conf

I will double check if I changed anything related, then if I don't solve, I will attach a trace

Thanks again!

-giovanni

**Comment by gmaruzz** [comment]
[volte_precondition.zip](https://github.com/herlesupreeth/docker_open5gs/files/9615093/volte_precondition.zip)
seems to me there is no mechanism to communicate to the phone that preconditions are met by the network

this trace I attach now is between a phone that asks precondition and a phone that do not asks for it

if you want, I can attach a trace between two phones both asking for precondition

as you can see in traces, after 8 seconds the phone that asked for precond and have had them not satisfied, sends a BYE with reason "QOS"

<pre>
2022/09/21 11:10:26.459072 192.168.101.2:5060 -> 172.22.0.21:5060                                                                                                                                                                              
BYE sip:3682b5b9-e787-4c88-ae9d-eb205c063010@192.168.101.3:5060;alias=192.168.101.3~5060~2 SIP/2.0                                                                                                                                             
To: <tel:393472665612;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=3461850736                                                                                                                                                          
From: <sip:393472665613@ims.mnc001.mcc001.3gppnetwork.org>;tag=3461850137                                                                                                                                                                      
Call-ID: 3461850132_2567676092@192.168.101.2                                                                                                                                                                                                   
CSeq: 240624661 BYE                                                                                                                                                                                                                            
Via: SIP/2.0/UDP 192.168.101.2:5060;branch=z9hG4bK1855294858                                                                                                                                                                                   
Max-Forwards: 70                                                                                                                                                                                                                               
P-Access-Network-Info: 3GPP-E-UTRAN-FDD; utran-cell-id-3gpp=0010100010019B01                                                                                                                                                                   
Content-Length: 0                                                                                                                                                                                                                              
Route: <sip:mo@172.22.0.21;transport=tcp;r2=on;lr=on;ftag=3461850137;rm=8;did=fb1.20f2>,<sip:mo@172.22.0.21;r2=on;lr=on;ftag=3461850137;rm=8;did=fb1.20f2>,<sip:mo@172.22.0.20:6060;transport=tcp;r2=on;lr=on;ftag=3461850137;did=fb1.2652>,<si
mo@172.22.0.20:6060;r2=on;lr=on;ftag=3461850137;did=fb1.2652>,<sip:mt@172.22.0.20:6060;lr=on;ftag=3461850137;did=fb1.3652>,<sip:mt@172.22.0.21;lr=on;ftag=3461850137;rm=7;did=fb1.30f2>                                                        
P-Preferred-Identity: <sip:393472665613@ims.mnc001.mcc001.3gppnetwork.org>                                                                                                                                                                     
Reason: SIP;text="QOS"                                                                                                                                                                                                                         
User-Agent: OnePlus_HD1903_RKQ1.201022.002              
</pre>

**Comment by herlesupreeth** [comment]
I had a quick look at the trace. From my perspective SIP signalling is correct, i.e. the other UE is clearly not advertising that precondition is supported.

I would suggest put the OnePlus phone in safe mode and take it out of safe mode and give it a try. Somehow feel the device at fault here.

**Comment by gmaruzz** [comment]
Hello, thanks for the answer

Yes, as stated, the other phone do not support the precondition, and that is better: we only have to support one

As you can see, the problem is that the phone that asks for precondition ask for its one precondition mandatory (remote is optional)

It is network that is supposed to give him precondition, not the other phone

Also, if you want, I can take a trace of two phones that both asks for precondition, and the results is the same

Have you ever saw phones that asks for precondition doing complete calls of more than 8 seconds? In my experience, oneplus 5 and 6 do not asks for precon and they work. Oneplus 7 and 8 asks for precon and fails

I have done many dozen of tests (even putting phones in airplane and back)

There is some other tests or traces I can take for you?

Do you plan to add support to qos precondition?

I saw you suggested some manipulation at the proxy level, but it seems not to work :(

https://github.com/open5gs/open5gs/issues/581

do you have any hints? this problem block the usage of phones that are not very old... (btw, even Iphone 8 fails same way)

**Comment by gmaruzz** [comment]
(eg, manipulation at the proxy level do not works, I have succeeded into altering the SDP bodies on the proxies, so each phone receive all preconditions - local and remote - as sendrecv, but seems to be not enough)

**Comment by gmaruzz** [comment]
here in much more details:

https://netmanias.com/en/post/blog/11789/lte-volte/dedicated-bearer-setup-in-lte-and-impact-on-volte-precondition

**Comment by gmaruzz** [comment]
this gives the framework view (very good!):
https://realtimecommunication.wordpress.com/2016/02/02/volte-policy-control-summary/

then the case for qos:
https://realtimecommunication.wordpress.com/2015/03/06/it-is-about-quality/

**Comment by gmaruzz** [comment]
Hello, in your trace, if I understand correctly, your Xiaomi initially asks for precond qos, it does not receive/reach it, and it simply continues as it is not a problem.
Eg, probably your Xiaomi just work around, or accept it does not get precond qos
I do not see qos satisfied or even negotiated in the trace

<pre>
2022/01/10 14:59:24.673283 172.22.0.21:6101 -> 172.22.0.20:6060
INVITE tel:698765432100;phone-context=ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
Route: <sip:orig@scscf.ims.mnc001.mcc001.3gppnetwork.org:6060;lr>
Record-Route: <sip:mo@172.22.0.21:6101;r2=on;lr=on;ftag=3008437180;rm=8;did=4c6.f921>
Record-Route: <sip:mo@172.22.0.21:6101;transport=tcp;r2=on;lr=on;ftag=3008437180;rm=8;did=4c6.f921>
From: <sip:598765432100@ims.mnc001.mcc001.3gppnetwork.org>;tag=3008437180
To: <tel:698765432100;phone-context=ims.mnc001.mcc001.3gppnetwork.org>
CSeq: 860953524 INVITE
Call-ID: 3008437172_2340680172@192.168.101.3
Via: SIP/2.0/TCP 172.22.0.21:6101;branch=z9hG4bKaae6.edb5db4e5c909d444ec7d3a65b4c24a9.0;i=6
Via: SIP/2.0/TCP 192.168.101.3:40469;rport=40874;branch=z9hG4bK3456046736
Max-Forwards: 69
Contact: <sip:7abf42d5-3551-458f-a574-04f721995912@192.168.101.3:40469;alias=192.168.101.3~40874~2>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi;+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3g
.ps2cs-srvcc-orig-pre-alerting
P-Access-Network-Info: 3GPP-E-UTRAN-FDD; utran-cell-id-3gpp=0010100011A2D001
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
Content-Type: application/sdp
Accept: application/sdp,application/3gpp-ims+xml
P-Preferred-Service: urn:urn-7:3gpp-service.ims.icsi.mmtel
Accept-Contact: *;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Supported: timer,100rel,replaces,precondition,histinfo,tdialog
P-Early-Media: supported
User-Agent: xiaomi_Mi A2 Lite_QKQ1.191002.002
Content-Length: 596
Session-Expires: 1800;refresher=uac
P-Charging-Vector: icid-value=495653AC1600158D000000BC00000000; icid-generated-at=172.22.0.21
P-Asserted-Identity: <sip:598765432100@ims.mnc001.mcc001.3gppnetwork.org>
P-Visited-Network-ID: ims.mnc001.mcc001.3gppnetwork.org

v=0
o=- 15 1000 IN IP4 172.22.0.16
s=QC VOIP
c=IN IP4 172.22.0.16
b=AS:41
b=RS:600
b=RR:2000
t=0 0
m=audio 49118 RTP/AVP 104 102 96 97
b=AS:41
b=RS:600
b=RR:2000
a=curr:qos local none
a=curr:qos remote none
a=des:qos mandatory local sendrecv
a=des:qos optional remote sendrecv
a=maxptime:240
a=rtpmap:104 AMR-WB/16000/1
a=fmtp:104 mode-change-capability=2;max-red=0
a=rtpmap:102 AMR/8000/1
a=fmtp:102 mode-change-capability=2;max-red=0
a=rtpmap:96 telephone-event/16000
a=fmtp:96 0-15
a=rtpmap:97 telephone-event/8000
a=fmtp:97 0-15
a=sendrecv
a=rtcp:49119
a=ptime:20


=================


2022/01/10 14:59:32.762384 172.22.0.20:6060 -> 172.22.0.21:6101
SIP/2.0 200 OK
Record-Route: <sip:mt@172.22.0.21;lr=on;ftag=3008437180;rm=7;did=4c6.0a21>,<sip:mt@172.22.0.20:6060;lr=on;ftag=3008437180;did=4c6.5412>,<sip:mo@172.22.0.20:6060;r2=on;lr=on;ftag=3008437180;did=4c6.4412>,<sip:mo@172.22.0.20:6060;transport=t
;r2=on;lr=on;ftag=3008437180;did=4c6.4412>,<sip:mo@172.22.0.21:6101;r2=on;lr=on;ftag=3008437180;rm=8;did=4c6.f921>,<sip:mo@172.22.0.21:6101;transport=tcp;r2=on;lr=on;ftag=3008437180;rm=8;did=4c6.f921>
From: <sip:598765432100@ims.mnc001.mcc001.3gppnetwork.org>;tag=3008437180
To: <tel:698765432100;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=3008437486
CSeq: 860953524 INVITE
Call-ID: 3008437172_2340680172@192.168.101.3
Via: SIP/2.0/TCP 172.22.0.21:6101;branch=z9hG4bKaae6.edb5db4e5c909d444ec7d3a65b4c24a9.0;i=6,SIP/2.0/TCP 192.168.101.3:40469;rport=40874;branch=z9hG4bK3456046736
P-Access-Network-Info: 3GPP-E-UTRAN-FDD; utran-cell-id-3gpp=0010100011A2D001
Content-Type: application/sdp
Content-Length: 350
Session-Expires: 1800;refresher=uac
Privacy: id
Contact: <sip:192.168.101.2:5060;alias=192.168.101.2~5060~2>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";video;+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting
Supported: 100rel,tdialog
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
Require: timer
C-Params: +g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";video;+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting

v=0
o=- 1002 1000 IN IP4 172.22.0.16
s=QC VOIP
c=IN IP4 172.22.0.16
b=AS:41
b=RS:600
b=RR:2000
t=0 0
m=audio 49132 RTP/AVP 104 96
b=AS:41
b=RS:600
b=RR:2000
a=maxptime:240
a=rtpmap:104 AMR-WB/16000/1
a=fmtp:104 mode-change-capability=2;max-red=0
a=rtpmap:96 telephone-event/16000
a=fmtp:96 0-15
a=sendrecv
a=rtcp:49133
a=ptime:20

=================


2022/01/10 14:59:32.849009 172.22.0.21:6101 -> 172.22.0.20:6060
ACK sip:192.168.101.2:5060;alias=192.168.101.2~5060~2 SIP/2.0
From: <sip:598765432100@ims.mnc001.mcc001.3gppnetwork.org>;tag=3008437180
To: <tel:698765432100;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=3008437486
CSeq: 860953524 ACK
Call-ID: 3008437172_2340680172@192.168.101.3
Via: SIP/2.0/TCP 172.22.0.21:6101;branch=z9hG4bKaae6.c4b9dde5ab412a8785a05c62905b0703.0
Via: SIP/2.0/UDP 192.168.101.3:40469;branch=z9hG4bK476577475
Content-Length: 0
Require: sec-agree
Max-Forwards: 69
Route: <sip:mo@172.22.0.20:6060;transport=tcp;r2=on;lr=on;ftag=3008437180;did=4c6.4412>,<sip:mo@172.22.0.20:6060;r2=on;lr=on;ftag=3008437180;did=4c6.4412>,<sip:mt@172.22.0.20:6060;lr=on;ftag=3008437180;did=4c6.5412>,<sip:mt@172.22.0.21;lr=
;ftag=3008437180;rm=7;did=4c6.0a21>
Proxy-Require: sec-agree
User-Agent: xiaomi_Mi A2 Lite_QKQ1.191002.002

</pre>

**Comment by herlesupreeth** [comment]
> I do not see qos satisfied or even negotiated in the trace

That is true. But its acting according to SDP in INVITE i.e. for remote the qos is optional. Eitherway, if you observe both yours and my pcap in both cases the dedicated bearer had been established (i.e. qos is maintained). Just that its not notified as part of SDP/SIP header

**Comment by gmaruzz** [comment]
> But its acting according to SDP in INVITE i.e. for remote the qos is optional.

yep, but if you test with another phone the same exact call to oneplus 5 (I have oneplus 5), then the call will fail because the originator do not have its own (local) qos satisfied

you can check with oneplus 7/8, or with iphone

would you like me to provide traces?

**Comment by herlesupreeth** [comment]
@gmaruzz I happen to face this issue myself when testing with an UE which didnt support precondition and I managed to fix this in the latest commits.
