### ISSUE TITLE
Issue with WebUI

### ISSUE THREAD

**Issue by joaodonatosilva2** [herlesupreeth/docker_open5gs#120]
Hello,

I've followed this tutorial https://github.com/herlesupreeth/docker_open5gs and deployed the script "sa-deploy.yaml" where all containers are running with the exception of webUI, that exits automatically.
Do you have any suggestion on how to solve this issue?

Thanks in advance,
Best regards,
João Silva

**Comment by herlesupreeth** [comment]
It could be related to this issue in open5gs - https://github.com/open5gs/open5gs/issues/1824

Most likely be fixed in upcoming commits

**Comment by herlesupreeth** [comment]
Is fixed in open5gs repo so closing this
