### ISSUE TITLE
DNAI parameter

### ISSUE THREAD

**Issue by joaodonatosilva2** [herlesupreeth/docker_open5gs#124]
Hello,

I would like to integrate the Open5GS Core with an Edge cloud computing software, where the DNAI parameter would be needed to integrate both.
Do you know where I can find this parameter defined from Open5GS side?

Thanks in advance

**Comment by zikkuratti** [comment]
https://smart-edge-open.github.io/ido-specs/doc/applications-onboard/using-smartedge-open-cnca/

**Comment by zikkuratti** [comment]
- dnai: 'edgeLocation001' it's looks like  docker yaml part not for soft o5gs whatether etc.

**Comment by joaodonatosilva2** [comment]
Thank you for the response zikkuratti!

Were you able to integrate Open5GS with Intel Smart Edge? I'm actually trying to integrate both, I have them deployed and working but not connected yet.

Thanks!

**Comment by herlesupreeth** [comment]
@joaodonatosilva2 no idea about edge cloud so can’t be off much help unfortunately
