### ISSUE TITLE
Scp open5gs in cx branch

### ISSUE THREAD

**Issue by modyngs** [herlesupreeth/docker_open5gs#126]
Hi
@herlesupreeth 
The latest open5gs is now default into scp( not NRF anymore) and I think dockerized Volte won't work with it!
Would you please update the files? Or give me some insight on how to use the old one?

Thanks
Best regards

**Comment by herlesupreeth** [comment]
Thanks for pointing it out. Fixed it in latest commit. Basically using tag v.2.4.11 of open5gs where this change has not been made
