### ISSUE TITLE
could not resolve hostname: "ims.mnc01.mcc001.3gppnetwork.org"

### ISSUE THREAD

**Issue by modyngs** [herlesupreeth/docker_open5gs#127]
Hi
Would you please give me some insight on that?

Thanks
Best regards
[New Text Document.txt](https://github.com/herlesupreeth/docker_open5gs/files/9847070/New.Text.Document.txt)

**Comment by herlesupreeth** [comment]
The log you provided is not properly visible in gedit so please re-post in different format. Rather I would prefer if you sent me pcap trace

**Comment by modyngs** [comment]
@herlesupreeth Thanks for the reply
Would you please check dockerized VOLTE (dockeropen5gs+IMS+OSMOMSC/HLR + SRSeNB) in cx branch?
It has some challenges in VOLTE registrations and Calls.

I would also capture and send the traces.

Thanks
Best regards

**Comment by modyngs** [comment]
I've checked it again and it was related to the wrong version on Open5gs!

Thanks
Best regards
