### ISSUE TITLE
How to fine-tune to make docker with open5gs faster ?

### ISSUE THREAD

**Issue by alf-askey** [herlesupreeth/docker_open5gs#13]
i found  docker with open5gs , it's performance less than physical machine with open5gs 
How to fine-tune to make docker faster ?

**Comment by herlesupreeth** [comment]
I dont think adding a docker element reduces the performance, but have you done some measurements to prove thats the case? If so, can you please provide here?

**Comment by herlesupreeth** [comment]
Here is one such study - https://stackoverflow.com/questions/21889053/what-is-the-runtime-performance-cost-of-a-docker-container

If you are running the eNB in a separate host then rather using port publish for MME and SGWU, you may as well run in host mode just to get slightly more performance as mentioned in above post

**Comment by herlesupreeth** [comment]
or go for a architecture with splitting components in different hosts

**Comment by herlesupreeth** [comment]
Closing this issue as it has more to do with docker performance in general and performance optimization if any either in docker technology or open5gs code
