### ISSUE TITLE
The key problem of mme hss pcrf and smf

### ISSUE THREAD

**Issue by shuimoshusheng** [herlesupreeth/docker_open5gs#130]
After newly adding scp, the key in the open5gs configuration file has changed. Do you still use the original generation method here?

**Comment by herlesupreeth** [comment]
Please be more specific about what key you are referring to.

**Comment by shuimoshusheng** [comment]
> Please be more specific about what key you are referring to.

old: 
![image](https://user-images.githubusercontent.com/15867686/203013674-82820cd6-786c-47fa-8894-402f801df773.png)

new:
![image](https://user-images.githubusercontent.com/15867686/203013602-ac1147f9-78a9-4fb0-9ad1-87e6da1a3f60.png)

**Comment by herlesupreeth** [comment]
Please open this ticket in open5gs as its not related to docker_open5gs. In docker_open5gs these certs are updated based on domain used.

**Comment by shuimoshusheng** [comment]
> Please open this ticket in open5gs as its not related to docker_open5gs. In docker_open5gs these certs are updated based on domain used.

Thanks, I have updated the latest key generation method.
