### ISSUE TITLE
HSS not updated when modifying MSISDN

### ISSUE THREAD

**Issue by justinmarkr** [herlesupreeth/docker_open5gs#133]
Hi @herlesupreeth,

Good day! As observed when I modified the MSISDN of the UE on open5gs UI, it was confirmed that MSISDN has been changed & confirmed also on mongodb. However, when I'm trying to call the newly nominated MSISDN, the call will not be succeeded. 

![image](https://user-images.githubusercontent.com/93913757/204204256-8d3c08db-4d19-434e-b472-66559d68e397.png)

![image](https://user-images.githubusercontent.com/93913757/204204055-cffc5039-1f07-48c6-8b7a-f20d237d1f17.png)

I've seen this logs on HSS.

11/28 05:23:19.284: [hss] ERROR: No Server-Name in Public-Identity[tel:48723333331] (../src/hss/hss-cx-path.c:899)

Then, when I've tried to call the old MSISDN, the call was successful. BTW, I'm using the CX branch.
I've tried also to restart the HSS but still throwing same error when calling the new nominated MSISDN.

**Comment by herlesupreeth** [comment]
@justinmarkr That's because open5gs HSS does not support on-the-fly changing of UE subscription details. You would have to bring down the docker_open5gs and bring it back up again for the new MSISDN to take effect.

**Comment by justinmarkr** [comment]
Thanks @herlesupreeth for the information. This is noted.
