### ISSUE TITLE
About CANCEL procedure in VOLTE

### ISSUE THREAD

**Issue by myonlystarWang** [herlesupreeth/docker_open5gs#136]
Hi @herlesupreeth 
     I'd like to ask you a question about VOLTE,procedure is as follows:
     1. two phone register to IMS successfully with HD flag.
     2. The calling mobile phone initiates a call
     3. The called mobile phone do not pick up
     4. Then the calling mobile phone hang up,the called phone keep ringing
     5. The second call from the calling phone failed
     Only after the calling phone flight re-registration can the call be successful again.
 
     I checked the pcap file in IMS,find that after the CANCEL message is sended, IMS does not send the dedicated bearer release message to the core network like STR.So I want to ask, how does the CANCEL procedure release the dedicated bearer?

     Thanks in advance!

**Comment by herlesupreeth** [comment]
CANCEL should have been relayed to the called mobile phone and the bearer release is initiated by the Core Network when it receives STR from P-CSCF towards PCRF. Please attach the trace so I could take a look.

**Comment by myonlystarWang** [comment]
@herlesupreeth Thank you for your rapid response!
Here are the pcaps[
[cancel pcap.zip](https://github.com/herlesupreeth/docker_open5gs/files/10236232/cancel.pcap.zip)
](url)
I used **openimscore**, and obviously IMS did not initiate STR after receiving CANCEL.
Maybe I missed something in `pcscf.cfg?
[pcscf.zip](https://github.com/herlesupreeth/docker_open5gs/files/10236249/pcscf.zip)
`

**Comment by herlesupreeth** [comment]
Please do not open issue here if its not using kamailo IMS. I haven't worked with openimscore so can't say whether it has a working IMS core or not/ or whether it has been integrated with open5gs CN.

**Comment by myonlystarWang** [comment]
Thank you very much! I'm closing this ticket now.
I just wanted to ask for some help because I know you are very familiar with VOLTE.
It would be better if you could give me a IMS+EPC pcap with CANCEL procedure, thanks in advance!

**Comment by herlesupreeth** [comment]
@myonlystarWang Unfortunately, I don't. But I remember testing this with kamailio and it worked

**Comment by myonlystarWang** [comment]
> @myonlystarWang Unfortunately, I don't. But I remember testing this with kamailio and it worked

Okay,I got it.
At least you told me that IMS need send STR to PCRF then release the dedicated bearer after CANCEL.
That's a big help :)  Thank you again!
