### ISSUE TITLE
volte docker setup kamailio_base folder missing

### ISSUE THREAD

**Issue by ping2balaji** [herlesupreeth/docker_open5gs#137]
Hi @herlesupreeth , 

I am interested in trying out volte call with LTE core and came across your notes on bringing up volte dockerized setup in following link:
https://open5gs.org/open5gs/docs/tutorial/03-VoLTE-dockerized/

In the steps its mentioned as:
`cd ../kamailio_base

docker build --no-cache --force-rm -t open5gs_kamailio .
`
But i could not see this "kamailio_base" folder in the clone. May i know how to build open5gs_kamailio docker image?
Is it the "ims_base" folder same as "kamailio_base" u were referrring to in the article?
Please clarify.

**Comment by s5uishida** [comment]
`ims_base` is correct as explained in this repository.

**Comment by herlesupreeth** [comment]
Yep, as @s5uishida mentioned its the ims_base folder ( I need to update that tutorial in open5gs). Thanks @s5uishida

**Comment by bjeyabalan** [comment]
Thanks for the clarification @s5uishida  / @herlesupreeth .

I am following that open5gs steps to try volte in dockerized env now. Can you pls clarify following:

1. Have built the images using: "docker-compose build --no-cache".
I assume next step is to do "docker-compose up" command though its not mentioned in the steps ? (im new to this, so just confirming). 

2. Also i see the docker-compose.yaml file that its starting all 4g and 5g containers probably. Is there any way i can run only LTE/EPC-Core using this docker environment? 

3. In the article the next step mentioned as:
`Follow the instructions in [VoLTE Setup](https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/):

Step 18, set IMSI, Ki, OP, SQN and APN of your SIM cards. Important! Set the type of both APN to IPv4. Kamailio does not support VoLTE over IPv6 at the moment. (See the screenshot below.)
Step 20, add IMS subscriptions to FHoSS.`
Does this mean i just have to follow step-18 and step-20 at this point? and no need to do from step 1 to 17?

4. I am using real radio and real 2 UEs. Hope its enough to configure correct PLMNs/Keys in my sim cards and set 2 APNs(internet/ims) in mobile to make this VoLTE testing work?
 
Please clarify.

Thanks,
...Balaji.J

**Comment by ping2balaji** [comment]
Thanks for the clarification @s5uishida  / @herlesupreeth .

I am following that open5gs steps to try volte in dockerized env now. Can you pls clarify following:

1. Have built the images using: "docker-compose build --no-cache".
I assume next step is to do "docker-compose up" command though its not mentioned in the steps ? (im new to this, so just confirming). 

2. Also i see the docker-compose.yaml file that its starting all 4g and 5g containers probably. Is there any way i can run only LTE/EPC-Core using this docker environment? 

3. In the article the next step mentioned as:
```
Follow the instructions in [VoLTE Setup](https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/):
Step 18, set IMSI, Ki, OP, SQN and APN of your SIM cards. Important! Set the type of both APN to IPv4. Kamailio does not support VoLTE over IPv6 at the moment. (See the screenshot below.)
Step 20, add IMS subscriptions to FHoSS.
```


Does this mean i just have to follow step-18 and step-20 at this point? and no need to do from step 1 to 17?

4. I am using real radio and real 2 UEs. Hope its enough to configure correct PLMNs/Keys in my sim cards and set 2 APNs(internet/ims) in mobile to make this VoLTE testing work?
 
Please clarify.

Thanks,
...Balaji.J

**Comment by s5uishida** [comment]
When using docker_open5gs, steps 1 to 17 are provided, so steps 18 (latter half) and 20 are required.

I'm using the `open5gs_hss_cx` branch of docker_open5gs. The reason is that the setting of FHoSS is a little troublesome, so instead of FHoSS, I connected Kamailio's S-CSCF and I-CSCF to Open5GS's HSS.

For reference, I wrote a tiny settings for using VoLTE/SMS with docker_open5gs.

https://github.com/s5uishida/docker_open5gs_volte_sms_config

**Comment by herlesupreeth** [comment]
> Have built the images using: "docker-compose build --no-cache".
> I assume next step is to do "docker-compose up" command though its not mentioned in the steps ? (im new to this, so just confirming).

Yes, that's right

> Also i see the docker-compose.yaml file that its starting all 4g and 5g containers probably. Is there any way i can run only LTE/EPC-Core using this docker environment?

yes, its possible. If you use `4g_plus` branch in this repo. That will bring up only 4G components + IMS

> Does this mean i just have to follow step-18 and step-20 at this point? and no need to do from step 1 to 17?

Yes, that is right. All the steps from 1 to 17 are more or less automated in this docker setup

> I am using real radio and real 2 UEs. Hope its enough to configure correct PLMNs/Keys in my sim cards and set 2 APNs(internet/ims) in mobile to make this VoLTE testing work?

It should be enough. But you never know whether VoLTE is truly activated on your UE until you attach to your network. Most of the times UE vendors lock the VoLTE functionality to only certain PLMN. If that is case then you can try force activating VoLTE on the phones using the guide here - https://github.com/herlesupreeth/CoIMS_Wiki (I am assuming that you have a programmable SIM card with all the required keys)
