### ISSUE TITLE
Issue in Open5GS SBI

### ISSUE THREAD

**Issue by joaodonatosilva2** [herlesupreeth/docker_open5gs#139]
Hello,

I've deployed Open5GS in docker using this repository:
https://github.com/herlesupreeth/docker_open5gs
All pods are successfully deployed but I'm getting the following for the PCF component:
![image](https://user-images.githubusercontent.com/103496863/209823181-1f5ec679-420e-4a03-815c-378e87e75534.png)

Do you have a suggestion to solve this issue?

Thank you very much for the attention,
Best regards,
João Silva

**Comment by herlesupreeth** [comment]
Please post a trace (.pcap) file so that I can take a look

**Comment by joaodonatosilva2** [comment]
Hello Supreeth,

Thank you very much for the response!

I have the Open5GS Core in docker running (from this repo: https://github.com/herlesupreeth/docker_open5gs) and I'm trying to integrate with a MEC tool, where it's present a NEF, AF and OAM. It's only required to add some IPs from the 5G Core in the MEC to establish the connection between both, which currently exists.

When I try to test the connectivity between Edge and 5G Core some errors are generated in the PCF, which didn't ocurred with another 5G Core tested.

I'm attaching the logs of PCR, UDR, the IPs used and 3 Wireshark traces, one only with the 5G Core deployed, another one with 5G Core and Edge deployed and the last one with Core and Edge deployed and testing connectivity from the edge to the 5G Core.

Do you have any suggestion to solve this issue?

[Open5GS_ISE deployment.zip](https://github.com/herlesupreeth/docker_open5gs/files/10355162/Open5GS_ISE.deployment.zip)

Thanks a lot for your time,
João

**Comment by herlesupreeth** [comment]
As per the logs in PCF screenshot you sent and the pcap, it seems like open5gs PCF is expecting User-Agent in HTTP2 Header of the request sent from NEF (10.42.235.244). You should probably look at the Intel Smart Edge configuration and see whether its sending User-Agent in HEADER or not - https://stackoverflow.com/questions/24274789/is-lack-of-user-agent-in-http-request-valid

**Comment by herlesupreeth** [comment]
Also, I found this in open5gs code. This could be the reason open5gs is relying on User-Agent

    /* Instead of Discovery-requester-nf-type,
     * Open5GS uses User-Agent for requester-nf-type */

**Comment by herlesupreeth** [comment]
Closing this as it could be an open5gs issue and not related to this repo specifically.
