### ISSUE TITLE
phone1 and 2 Volte register failure after reboot docker of pc 

### ISSUE THREAD

**Issue by alf-askey** [herlesupreeth/docker_open5gs#14]
my test steps as the below 

1)  Phone 1 call phone phone 2 successfully
2)  reboot docket and pc 
3)  launch "source .env"
4)  launch "docker-compose up"
5) phone 1/2 attach successfully 
6) phone 1/2 enable "VoLTE"  and try to register IMS 

step 6 )  is failure , i attached packet as the below , could you help check this ?
[phone1 and 2 Volte register failure.zip](https://github.com/herlesupreeth/docker_open5gs/files/5801615/phone1.and.2.Volte.register.failure.zip)

**Comment by herlesupreeth** [comment]
Can you make sure the PCRF's Diameter (Rx) connection to PCSCF is in Connected state or not? It needs to be in connected state in order for SIP register to work

**Comment by herlesupreeth** [comment]
> phone 1/2 enable "VoLTE" and try to register IMS

Do you mean you toggled the VoLTE on phone after the phones got attached successfully?

**Comment by alf-askey** [comment]
> > phone 1/2 enable "VoLTE" and try to register IMS
> 
> Do you mean you toggled the VoLTE on phone after the phones got attached successfully?

==> yes  , and i also try to enable "VoLTE" when phone bring up at the same time

**Comment by alf-askey** [comment]
> Can you make sure the PCRF's Diameter (Rx) connection to PCSCF is in Connected state or not? It needs to be in connected state in order for SIP register to work

==> i have no check this , could you teach me how to do ?
i just do "docker-compose up" after reboot pc

**Comment by herlesupreeth** [comment]
> ==> i have no check this , could you teach me how to do ?

You need to check the logs and its should say something like the following 

`[diam] INFO: CONNECTED TO 'pcscf.ims.mnc001.mcc001.3gppnetwork.org' (TCP,soc#14): (../lib/diameter/common/logger.c:108)`

Can you send the output of below command?

docker ps

**Comment by alf-askey** [comment]
i don't know what happen ,but now i try to reinstall docker and open5gs to check if the phone can be registered

**Comment by alf-askey** [comment]
i can do "docker ps"

**Comment by alf-askey** [comment]
output's log:
[log.txt](https://github.com/herlesupreeth/docker_open5gs/files/5801785/log.txt)

CONTAINER ID   IMAGE                  COMMAND                  CREATED       STATUS          PORTS                                                                                               NAMES
c476f5cf3060   docker_open5gs_mme     "/bin/sh -c '/mnt/mm…"   3 hours ago   Up 46 minutes   2123/udp, 3868/sctp, 3868/tcp, 3868/udp, 5868/udp, 5868/sctp, 5868/tcp, 0.0.0.0:36412->36412/sctp   mme
372e4ff32a03   docker_scscf           "/bin/sh -c '/mnt/sc…"   3 hours ago   Up 46 minutes   3870/tcp, 3870/udp, 6060/tcp, 6060/udp                                                              scscf
651e1969f919   docker_icscf           "/bin/sh -c '/mnt/ic…"   3 hours ago   Up 46 minutes   3869/tcp, 3869/udp, 4060/tcp, 4060/udp                                                              icscf
412b5e65b2d1   docker_open5gs_sgwc    "/bin/sh -c '/mnt/sg…"   3 hours ago   Up 46 minutes   2123/udp, 8805/udp                                                                                  sgwc
5c568f675fa2   docker_open5gs_amf     "/bin/sh -c '/mnt/am…"   3 hours ago   Up 46 minutes   7777/tcp, 0.0.0.0:38412->38412/sctp                                                                 amf
58e8a6c6a54f   docker_open5gs_sgwu    "/bin/sh -c '/mnt/sg…"   3 hours ago   Up 46 minutes   0.0.0.0:2152->2152/udp, 8805/udp                                                                    sgwu
e141bc594c85   docker_open5gs_upf     "/bin/sh -c '/mnt/up…"   3 hours ago   Up 46 minutes   2152/udp, 8805/udp                                                                                  upf
fd3b2f1bcea8   docker_fhoss           "/bin/sh -c /mnt/fho…"   3 hours ago   Up 46 minutes   3868/tcp, 3868/udp, 0.0.0.0:8080->8080/tcp                                                          fhoss
6a524d32f8c4   docker_open5gs_webui   "/bin/sh -c 'sleep 1…"   3 hours ago   Up 46 minutes   0.0.0.0:3000->3000/tcp                                                                              webui
89861de337ca   docker_open5gs_udr     "/bin/sh -c '/mnt/ud…"   3 hours ago   Up 46 minutes   7777/tcp                                                                                            udr
4e297b2ddf49   docker_open5gs_pcrf    "/bin/sh -c '/mnt/pc…"   3 hours ago   Up 46 minutes   3868/sctp, 3868/tcp, 3868/udp, 5868/sctp, 5868/tcp, 5868/udp                                        pcrf
27f84a7835e5   docker_open5gs_hss     "/bin/sh -c '/mnt/hs…"   3 hours ago   Up 46 minutes   3868/sctp, 3868/tcp, 3868/udp, 5868/sctp, 5868/tcp, 5868/udp                                        hss
c1531df562fd   docker_open5gs_udm     "/bin/sh -c '/mnt/ud…"   3 hours ago   Up 46 minutes   7777/tcp                                                                                            udm
46c6114b0198   docker_open5gs_ausf    "/bin/sh -c '/mnt/au…"   3 hours ago   Up 46 minutes   7777/tcp                                                                                            ausf
583404fcf806   docker_open5gs_smf     "/bin/sh -c '/mnt/sm…"   3 hours ago   Up 46 minutes   2123/udp, 3868/sctp, 3868/tcp, 3868/udp, 5868/tcp, 5868/udp, 8805/udp, 5868/sctp, 7777/tcp          smf
43481649f71a   docker_dns             "/bin/sh -c '/mnt/dn…"   3 hours ago   Up 46 minutes   53/udp                                                                                              dns
f06975a5d11f   docker_open5gs_nrf     "/bin/sh -c '/mnt/nr…"   3 hours ago   Up 46 minutes   7777/tcp                                                                                            nrf
1426deefbfe1   docker_open5gs_mongo   "/bin/sh -c /mnt/mon…"   3 hours ago   Up 46 minutes   27017/tcp, 27017/udp                                                                                mongo
e70d5c6f9c08   docker_rtpengine       "/bin/sh -c /mnt/rtp…"   3 hours ago   Up 46 minutes   2223/udp, 49000-50000/udp                                                                           rtpengine
1b2b7962442c   docker_mysql           "/bin/sh -c /mysql_i…"   3 hours ago   Up 46 minutes   3306/tcp                                                                                            mysql

**Comment by herlesupreeth** [comment]
I dont see PCSCF running in above list of cotnainer, thats the reason you dont see SIP messages

I would recommend to do the following before you plan to restart the docker setup

1. Ensure the containers are not already running, if so bring them down as follows

docker-compose down

2. Wait for it and then execute docker-compose up

**Comment by alf-askey** [comment]
thank herlesupreeth ,
                                  i follow your the above steps , now VoLTE is workd
