### ISSUE TITLE
how to interconnect a baicells enb? 

### ISSUE THREAD

**Issue by gmaruzz** [herlesupreeth/docker_open5gs#140]
Hello!

I have docker_open5gs working with usrp b210, volte calls no problem

I am now trying to use a baicells (nova 227) as enb

what changes are needed to docker_open5gs config ?

(I tried to reconstruct them from various git issues and docs, but I am not sure I got it right)

I will wait for your instructions on how to change docker_open5gs config to use the external baicell enb, and test it

If I still have problems, I will then ask about the baicell config itself

(at this moment I can ping from baicell the mme container, and I see sctp traffic between mme and baicell and viceversa, on the right ports. But the baicell status tells me the mme is not connected. I suspect the problem is in the ECI parameter in "quick settings" in baicells, but I would first like to be sure I got the docker_open5gs config change for external enb right)

Thanks a big lot, and happy new year!!! :)

**Comment by herlesupreeth** [comment]
Please refer to the documentation in README

Edit only the following parameters in .env as per your setup

MCC
MNC
TEST_NETWORK --> Change this only if it clashes with the internal network at your home/office
DOCKER_HOST_IP --> This is the IP address of the host running your docker setup
SGWU_ADVERTISE_IP --> Change this to value of DOCKER_HOST_IP set above only if eNB/gNB is not running the same docker network/host
UPF_ADVERTISE_IP --> Change this to value of DOCKER_HOST_IP set above only if eNB/gNB is not running the same docker network/host


If eNB/gNB is NOT running in the same docker network/host as the host running the dockerized Core/IMS then follow the below additional steps

Under mme section in docker compose file (docker-compose.yaml, nsa-deploy.yaml), uncomment the following part

...
    # ports:
    #   - "36412:36412/sctp"
...

**Comment by gmaruzz** [comment]
![baicell_09](https://user-images.githubusercontent.com/331862/210578305-22aaaf28-e1f9-4033-9400-3a1c4895dc10.jpg)
![baicell_08](https://user-images.githubusercontent.com/331862/210578306-faf3f81c-e926-4caa-90b5-1df329734883.jpg)
![baicell_07](https://user-images.githubusercontent.com/331862/210578310-262b43d5-ee62-41ee-b93b-c86b5be2a872.jpg)
![baicell_06](https://user-images.githubusercontent.com/331862/210578312-27843678-4ae1-4dfa-8de2-f7a5ec8b9ff0.jpg)
![baicell_05](https://user-images.githubusercontent.com/331862/210578316-b8c6d170-b5be-48b7-a406-b0461777e336.jpg)
![baicell_04](https://user-images.githubusercontent.com/331862/210578319-1ff4a21c-967b-46bd-af24-0c9775912d28.jpg)
![baicell_03](https://user-images.githubusercontent.com/331862/210578321-04ffc5a4-5bb0-481e-9558-1aa0e549662d.jpg)
![baicell_02](https://user-images.githubusercontent.com/331862/210578323-fb296c51-c17d-442c-950f-71be337e6c14.jpg)
![baicell_01](https://user-images.githubusercontent.com/331862/210578327-766b98f4-1402-4a75-963b-df92890a4c27.jpg)
[PCAP_baicell_01.zip](https://github.com/herlesupreeth/docker_open5gs/files/10344987/PCAP_baicell_01.zip)


Hello!

Thanks a lot for the info and your efforts!

I modified the config as you wrote.
Then I started docker compose
When docker compose was up, I started the tcpdump
Then I rebooted the baicell

baicell is at 192.168.1.251
mme is at 172.22.0.9
docker host (the laptop) is at 192.168.1.61


As you can see, the baicell sends SCTP INIT, mme answers with INIT_ACK, and that's it

I attach as pictures all baicell config screenshots that seems relevant to me, please let me know if you need more/others

particularly, I suspect:

- PCI and ECI in quick settings (no idea what values to assign)
- LGW settings (disable? NAT? Bridge?)

or maybe is

- baicell networking that is wrong? (eg, mme must not be connected through the wan interface?)

Please consider me completely available to provide you with any other info, and to do any test you deem useful

Also, if you have info about the baicell config that works, please let me know

Thanks a lot!!

**Comment by gmaruzz** [comment]
[PCAP_baicell_01.zip](https://github.com/herlesupreeth/docker_open5gs/files/10344987/PCAP_baicell_01.zip) is the tcpdump capture

**Comment by gmaruzz** [comment]
> Aha, I see. You should provide the MME IP in Baicells as 192.168.1.61 and not 172.22.0.9

I will test it immediately
I was under the impression I must set it to 172.22.0.9 and set the static route to it (I've done that)

I will update here with test results

**Comment by gmaruzz** [comment]
GLORIOUS! :)

it works!
(now I can begin playing with it)

THANKS A LOT!
![baicell_10](https://user-images.githubusercontent.com/331862/210589540-9c1aba61-c2f9-4850-be46-6c444399f000.jpg)
