### ISSUE TITLE
[Info request]: Command to list all UEs connected to open5gs

### ISSUE THREAD

**Issue by anevrekarh9** [herlesupreeth/docker_open5gs#143]
Ask: Please provide command to list all UEs connected to open5gs.

We have deployed docker version of open5gs as mentioned in https://github.com/s5uishida/docker_open5gs_volte_sms_config
We have real eNBs and UEs connected to it.
We want to see on open5gs core which UEs are connected to core with their IMSI, APN, allocated IP.
I could not find such command in open5gs documentation.
Is there any way to get this info.

**Comment by herlesupreeth** [comment]
I dont think you will be able to see which UEs are connected with their IMSI, APN and IP. But if you access the Prometheus, then you would be able to have the graph of the following metrics

![image](https://user-images.githubusercontent.com/4115839/216534419-51f96799-47f3-4663-b059-e545f4f278e8.png)
