### ISSUE TITLE
FYI: latest osmomsc need to delete its db, or it will stop mme 

### ISSUE THREAD

**Issue by gmaruzz** [herlesupreeth/docker_open5gs#144]
if you rebuild the compose, it loads the newer osmomsc

latest osmomsc changed db format, so it will not start if it find the old db

if osmomsc do not start, mme start but will not accept enb, eg: mme do not works correctly

fix: if you update osmomsc, delete its sms.db* files (all of them)
they are used only for retransmission of messages that failed, and the files will be re-created at startup

**Comment by herlesupreeth** [comment]
Hey, Thanks for letting me know. Will fix that right away.

**Comment by gmaruzz** [comment]
maybe just delete the DB before startup in any case :)
