### ISSUE TITLE
The configuration files of Open5GS have been changed.

### ISSUE THREAD

**Issue by s5uishida** [herlesupreeth/docker_open5gs#147]
Hi @herlesupreeth 

The configuration files were changed in the commit below.

https://github.com/open5gs/open5gs/commit/05fbaf69587488e53b5e741a9ada9f9fa5749322

So, for example, in the case of amf.yaml, I think it is necessary to add the following settings.
```diff
--- amf.yaml.orig       2023-02-21 12:52:55.890196628 +0900
+++ amf.yaml    2023-02-21 16:47:28.352909751 +0900
@@ -3,6 +3,12 @@
 
 parameter:
 
+sbi:
+    server:
+      no_tls: true
+    client:
+      no_tls: true
+
 amf:
     sbi:
       - addr: AMF_IP
```
Same for ausf, bsf, nrf, nssf, pcf, scp, smf, udm, udr.

In my environment, this change made `sa-deploy.yaml` work.

**Comment by herlesupreeth** [comment]
Thanks @s5uishida . I will address them once I am back from holidays

**Comment by herlesupreeth** [comment]
Done..Thanks once again.

**Comment by s5uishida** [comment]
Hi @herlesupreeth 

Thanks!

BTW, seeing `open5gs/configs/open5gs/upf.yaml.in`, I think this change for UPF is not necessary.

**Comment by herlesupreeth** [comment]
Ah I see. Will fix that. Thanks
