### ISSUE TITLE
ViLTE will disconnect after 10 seconds

### ISSUE THREAD

**Issue by alf-askey** [herlesupreeth/docker_open5gs#15]
Hi herlesupreeth,
                           
my test steps as the below
1) phone 1(tel:0711) call phone2(tel:0713)
2) phone 2 accept a call
3) phone 1 invite phon2 via "video mode" 
4) phone 2 accept a video
5) phone 1 and 2 display video

fail on step 5 , it only display about 13 seconds , packet and log as the below

[packet-ViLTE-Disconnect after ten seconds.zip](https://github.com/herlesupreeth/docker_open5gs/files/5806122/packet-ViLTE-Disconnect.after.ten.seconds.zip)
[log-ViLTE-Disconnect after ten seconds.txt](https://github.com/herlesupreeth/docker_open5gs/files/5806124/log-ViLTE-Disconnect.after.ten.seconds.txt)
[video.zip](https://github.com/herlesupreeth/docker_open5gs/files/5806169/video.zip)

**Comment by alf-askey** [comment]
i try to the above step 3 invite "video mode" from phon2 (tel:0713)
the VoLTE will continuely work after ViLTE disconnect
[video-2.zip](https://github.com/herlesupreeth/docker_open5gs/files/5806235/video-2.zip)

**Comment by herlesupreeth** [comment]
You need to have APN configuration as follows for both UEs to authorize QoS for Video call in open5gs Web UI (also make sure your eNB support Data Radio Bearer Configuration corresponding to QCI 2)

```
APN Configuration:
-------------------------------------------------------------------------------------------------------------------------
| APN      | QCI | ARP | Capability | Vulnerablility | MBR DL/UL(Kbps)     | GBR DL/UL(Kbps) | PGW IP        |
-------------------------------------------------------------------------------------------------------------------------
| internet | 9   | 8   | Disabled   | Disabled       | unlimited/unlimited |                 |               |           
-------------------------------------------------------------------------------------------------------------------------
| ims      | 5   | 1   | Disabled   | Disabled       | 3850/1530           |                 |               |           
|          | 1   | 2   | Enabled    | Enabled        | 128/128             | 128/128         |               |
|          | 2   | 4   | Enabled    | Enabled        | 812/812             | 812/812         |               |
-------------------------------------------------------------------------------------------------------------------------
```

**Comment by alf-askey** [comment]
yes , i check amarisoft 's ENB that  it support  "qci: 2, /*  - real time (video) */"
but  the same disconnect after 10 seconds
[vilte-disconnet.zip](https://github.com/herlesupreeth/docker_open5gs/files/5806882/vilte-disconnet.zip)
i will try other smallcell for vilte , thank your help

**Comment by herlesupreeth** [comment]
I will re-open this as I would like to work on this when I have time

**Comment by alf-askey** [comment]
thank your help .^0^

**Comment by modyngs** [comment]
@alf-askey 
Can u share your drb config for QCI 2 ?

**Comment by herlesupreeth** [comment]
Video calling should work so closing this. Please re-open the issue with pcaps and logs if you still face issue.
