### ISSUE TITLE
5GSA Deployment in Multiple interfaces VM

### ISSUE THREAD

**Issue by giangdh1009** [herlesupreeth/docker_open5gs#150]
I Have a VM with 2 interfaces
IP 1: 10.155.146.101 (Could Access Internet).
IP 2: 10.204.73.88 (Could not access to internet).
Because of security policy, real gnodeB could only connect to IP 2, but i try from UERANSIM, session could establish, but UE couldn't ping to internet. 
.env: https://1drv.ms/u/s!AraARB5vdTNrhvoxv_GMYPBiO-5YOg?e=GsvbNd 
sa-deploy.yaml: https://1drv.ms/u/s!AraARB5vdTNrhvowAlWfE0qtMK9hfw?e=nKcghW 
Have anyone had experience?

**Comment by herlesupreeth** [comment]
I don't see any issue in your .env and docker-compose file. I believe issue maybe in VM level. Can you post a pcap file here trying to perform some ping traffic from UERANSIM?

**Comment by giangdh1009** [comment]
![image](https://user-images.githubusercontent.com/100834437/224936912-566054b1-9dcd-44a9-b60b-be0a77c8c5db.png)
I used UERANSIM container in a seperate VM, i seems GTP tunnel return to docker IP instead of VM IP.
If i used UERANSIM native without docker it worked fine, no problem at Core.
https://1drv.ms/u/s!AraARB5vdTNrhvppSfN9a2YsoJ-PBw?e=hXTkH7 
So if UERANSIM in another VM, .env 
# UERANSIM
NR_GNB_IP=172.22.0.23
NR_UE_IP=172.22.0.24
shoud change to VM's IP, right?

**Comment by herlesupreeth** [comment]
Ah I see..if you want to run UERANSIM in another VM then you would have to change the networking to host mode in UERANSIM docker compose file. And, change the IP to host IP e.g. 10.155.146.101 in .env file.

**Comment by giangdh1009** [comment]
If change to host-mode, UE can't find gnodeB
Is this config OK:
  nr_ue:
    image: docker_ueransim
    container_name: nr_ue
    stdin_open: true
    tty: true
    volumes:
      - ./ueransim:/mnt/ueransim
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ueransim-ue-1
    expose:
      - "4997/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    network-mode: host
services:
  nr_gnb:
    image: docker_ueransim
    container_name: nr_gnb
    stdin_open: true
    tty: true
    volumes:
      - ./ueransim:/mnt/ueransim
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ueransim-gnb-1
    expose:
      - "38412/sctp"
      - "2152/udp"
      - "4997/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    network_mode: host

**Comment by herlesupreeth** [comment]
No need to run nr_ue in host mode, you need to run only nr_gnb in host mode. My bad for not being clear earlier.

Also, dont forget to set the IP in .env as follows

NR_GNB_IP=<HOST_MACHINE_IP>
NR_UE_IP=172.22.0.24

**Comment by giangdh1009** [comment]
Thanks herlesupreeth, it worked
