### ISSUE TITLE
Request support for OAI

### ISSUE THREAD

**Issue by VLiu7** [herlesupreeth/docker_open5gs#152]
Hi, I saw the discussion about OAI support in the issue over a year ago, do you have any recent plans to add configs to support OAI SA/NSA gNB and eNB?

Thanks in advance!

**Comment by herlesupreeth** [comment]
For OAI, its a bit tricky since I have only LimeSDR to work with. I did give a try recently with OAI gNB (SA) and had no luck. Can't say about the timeline when I would have an OAI working config. Will update the repo as soon as I have it working.

**Comment by VLiu7** [comment]
Thank you for reply. I'm trying to build environment with OAI, open5gs, USRP B210 and COTS UE. But I'm having a lot of problems, I'm not sure if it's a problem with my configuration or if the two themselves are not compatible. I will keep trying.
