### ISSUE TITLE
xiaomi 9a make volte call but in second call , could you help me why he doesn't make it in frist call

### ISSUE THREAD

**Issue by defalmatari** [herlesupreeth/docker_open5gs#156]

**Comment by herlesupreeth** [comment]
Please describe your setup, attach the config changes if any and a trace of the issue you are facing in the issue description (not in the issue title)

**Comment by defalmatari** [comment]
thanks, Herlesupreeth
the problem is solved, and thanks a lot for your effort on docker_open5gs.
