### ISSUE TITLE
SMS send fail 

### ISSUE THREAD

**Issue by alf-askey** [herlesupreeth/docker_open5gs#16]
My  test step

1) phone 1 / 2 regisiter IMS successfully 
2) phone 1(tel:0711) send  message to phone 2(tel:0712)

error step2:  Status-Line: SIP/2.0 478 Unresolvable destination (478/TM)

packet as the below:
[sms_err.zip](https://github.com/herlesupreeth/docker_open5gs/files/5806949/sms_err.zip)

**Comment by alf-askey** [comment]
sorry i update packet 
[sms_err.zip](https://github.com/herlesupreeth/docker_open5gs/files/5806977/sms_err.zip)

**Comment by herlesupreeth** [comment]
IMS supports only basic calling nothing else i.e. No SMS/ViLTE support. For the ViLTE it should be a bit straightforward, i have less time to work on it so it will take time to support ViLTE

**Comment by herlesupreeth** [comment]
Closing this issue as SMS wont be supported

**Comment by alf-askey** [comment]
thank herlesupreeth

**Comment by modyngs** [comment]
@herlesupreeth 
Hi, is there a way to send SMS over IMS after Cx interface was added?
could you please give us some hints on How to do SMS over IMS in LTE? Does it need a server or any additional domain?

Thanks
Best regards

**Comment by herlesupreeth** [comment]
Yes, its possible. You need to set the application server for SMS as part of Cx data. I am not fully aware of the list of components required for it. But you can use the SMS module of kamailio and give it a try.

**Comment by modyngs** [comment]
@herlesupreeth Thanks for your Quick replay,
So how about VILTE? does it also need another AP?

Thanks
Best regards

**Comment by herlesupreeth** [comment]
No, it does not
