### ISSUE TITLE
smsc unicode

### ISSUE THREAD

**Issue by defalmatari** [herlesupreeth/docker_open5gs#161]
how to make smsc sent text arabic  ?

**Comment by defalmatari** [comment]
I try to sent sms text arabic but received unknown text on other phone.

**Comment by herlesupreeth** [comment]
I think its a known issue but sadly I dont know the solution for it. https://github.com/herlesupreeth/docker_open5gs/issues/128

**Comment by herlesupreeth** [comment]
Sending unicode should be working now. Please re-compile kamailio base image and give it a try.

**Comment by s5uishida** [comment]
Hi @herlesupreeth 

In my environment, I was able to send and receive Japanese messages using SMS over IMS without any garbled characters.

Thank you very much!

However, as I wrote in my repository, VoLTE didn't work with the latest docker_open5gs and Open5GS combination earlier this month, so I used these older versions. (It may be a problem specific to my environment.)

In addition, I replaced only Kamailio and docker_open5gs/smsc with the latest version, rebuilt, and confirmed SMS over IMS.

**Comment by herlesupreeth** [comment]
Happy to hear that it works with Japanese characters :) thanks for confirming.

> However, as I wrote in my repository, VoLTE didn't work with the latest docker_open5gs and Open5GS combination earlier this month, so I used these older versions. (It may be a problem specific to my environment.)

Can you send me the logs and pcaps of the issue? I will take a look

**Comment by s5uishida** [comment]
Hi @herlesupreeth 

I don't have access to my environment right now, so I'd like to get the logs tomorrow.

Thank you so much!

**Comment by s5uishida** [comment]
Hi @herlesupreeth 

I tried VoLTE with the latest docker_open5gs and worked fine.
Also, `SMS over IMS` and `SMS over SGs` also worked.

Sorry to bother you.

I have added a list of confirmed versions for my environment to my repository.

**Comment by herlesupreeth** [comment]
Awesome.. thanks. Then i will close this issue
