### ISSUE TITLE
Are these network elements enough to support the ims subsystem?

### ISSUE THREAD

**Issue by ljysdfz** [herlesupreeth/docker_open5gs#164]
I have had a running SA deployment.
Now I would like to make it voice centric in a way that I try to attach an IMS subsystem without introducing LTE.
In the light of the docker compose file, I want to know if these extra images are enough to fulfill the purpose: dns, rtpengine, mysql, fhoss, icscf, scscf, pcscf?

**Comment by ljysdfz** [comment]
@herlesupreeth 
Long time no see herle !! 
Thanks a lot all the same !! 
May all the blessings overtake you !!

**Comment by ljysdfz** [comment]
@herlesupreeth 
Excuse me, one more question.
I'm afraid the HSS cannot make use of gNB. 
Is the IMS capable of being used  if I install the whole suite (5G+LTE+gNB) but hasn't got an eNB ?

**Comment by herlesupreeth** [comment]
Sadly, no. Because the entity which takes care of Policy enforcing in 4G is PCRF and the one in 5G is PCF.

So, if you want to have an IMS registration then the policy/media flow needs to be approved by PCF in the case of 5G.

**Comment by ljysdfz** [comment]
@herlesupreeth 
Dear Herle,
In other words, I think you mean that the IMS currently in this project can only run in LTE.
This is a pcap capturing several Booting process of a physical phone -- VIVO S9
[IMS-Deprivation.zip](https://github.com/herlesupreeth/docker_open5gs/files/11516508/IMS-Deprivation.zip)
The core network has got 2 DNNs -- IMS (voice-wise, 192.168.101.0/24) & ctnet (Internet-wise, 192.168.100.0/24).
I found that the phone tell us it is "voice centric" in the "security mode complete" packet.
![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/3bc42fc6-7e53-49a9-9680-327befa0e369)
And it was clear that the ctnet session has been established successfully, while the IMS session failed.
I supposed it was caused by the lack of IMS subsystem, because voice centric UE needs to establish IMS session first. Is this understanding correct?
And if an eNB seems not available, do I have another approach to make an IMS work under current circumstances?
Such as can I make it through by removing the core network capability indicated by the feature "IMS voice over PS session indicator (IMS VoPS)" in the "registration accept" packet?
![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/69ba1ca8-9182-4fdb-86e4-038abe9e749b)

**Comment by ljysdfz** [comment]
OK, thanks, bro.

**Comment by herlesupreeth** [comment]
Hey, sorry I couldn't reply sooner.. Pleas find my reply below

> In other words, I think you mean that the IMS currently in this project can only run in LTE.

Yes, thats right.

> I supposed it was caused by the lack of IMS subsystem, because voice centric UE needs to establish IMS session first. Is this understanding correct?

Yes, it was caused by lack of IMS subsystem using 5G SBI based interface. And, voice centric just means that UE is voice capable and does not mean IMS session must be setup first.

> And if an eNB seems not available, do I have another approach to make an IMS work under current circumstances?

The only way forward is to add 5G interface to P-CSCF of Kamailio to talk with PCF.

> If no, is there any workaround to make a phone surf the Internet correctly while establishing the network pdu session successfully without IMS session established?

Yes, disable VoLTE switch in your phone settings and if you have CoIMS app installed, uninstall it and reboot the phone.

**Comment by ljysdfz** [comment]
@herlesupreeth 
Really appreciate your answers that bring me a lot of understandings.
This is the the pcap which has been narrowed down.
[selective.zip](https://github.com/herlesupreeth/docker_open5gs/files/11557642/selective.zip)
I'm trying to locate the failure cause responded by UE.
Finally I identified it was sent by the packet `PDUSessionResourceSetupResponse` and named `Transfer Syntax Error`
![1](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/9b2e70d9-bf77-4a07-96d2-8a320f318c44)
According to 3GPP TS38.413, this error was caused by illegitimacy of parameters, such as type violation, lack of mandatory fields, or out of range.
![2](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/726d2f95-98a8-428c-b240-ca85cd27b14a)
So I track down the `PDUSessionResourceSetupRequest` in which the 5GC requires UE to establish a GTP-U tunnel for IMS session.
At last, I found this part.
![3](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/7856ab69-ef33-4a1a-be89-128d08d45ea5)
I tried to figure out what's going wrong but failed to confirm any mishap about the parameters per se.
Do you have any idea about how to determine what the heck triggered the `Transfer Syntax Error`?

**Comment by ljysdfz** [comment]
@herlesupreeth 
Hi bro.
I recognized two suspicious places in the PDU session resource setup request.
The first one is the P-CSCF address that is the default docker intranet address.
![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/c5e9f23b-72b8-461e-917b-6ed25f12edd6)
The second one is the PDU addresses without IPV6 presence.
![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/397eb5bc-a781-47f2-a45e-253f405a91de)
The first one is definitely the aforementioned IMS deprivation crisis that waits to be solved.
How would you reflect on these questions?

**Comment by ljysdfz** [comment]
Dear Herle,
I try to make a regression test which induced a new confusion.
Here's the pcap cought by the gNB.
[n2.zip](https://github.com/herlesupreeth/docker_open5gs/files/11567170/n2.zip)
I think IMS failure is explainable because no IMS system exists for now.
But I don't know why the ctnet, that is the Internet session, also finally failed.
I succeeded in making the UPF can ping gateway, ping Internet especially ping domain names of prominent web portals.
But as you can see in the pcap, the ctnet session looks like being destined to fade away.
Every packet from Internet blacked out.
![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/1588965e-031d-488c-b3fd-75edf9b2f388)
No signaling.
No prompting.
Could you please help me sort it out ?

**Comment by herlesupreeth** [comment]
I dont see any issue with the ctnet session. Those blacked out session are TCP re-transmissions and not much to worry about.

I still see communication between 192.168.100.2 and other IP address even after packet 123 in your screenshot. So the session is intact.

**Comment by ljysdfz** [comment]
Dear Herle,
Good news.
I've got a IMS test instrument which is centos7 based.
It support direct communication with PCF and UPF.
But there is still a requirement that UDM should involve the function of HSS, so that it can commune with the IMS through DIAMETER protocol.
If I deploy in this way, is it enough to install an extra HSS on the base of SA installment?

**Comment by ljysdfz** [comment]
@herlesupreeth 
Dear Herle,

I tried to build a set of NSA system through the docker-compose.yaml build using independent USRP system.
I've created 2 APN: ctnet & IMS.
I've made a subscriber like this 
![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/db2c5c69-10a6-4607-aaf2-d834b8fa6286)
Have got a weird question.
UE has successfully attached, but failed to ping 192.168.100.1 or 192.168.101.1. 
This is the [pcap](https://github.com/herlesupreeth/docker_open5gs/files/11715084/2.zip).
The pcap seems in good condition with a GTP tunnel built.
For your information, these are several other [problems](https://github.com/herlesupreeth/docker_open5gs/files/11715095/Draft.docx) I have solved during the deployment.
In the process, I subscribed in osmohlr & fhoss for 3G and 4G ims respectively.
I want to ask:
1. Do you know why failing to ping the two gateways?
2. Do I have to establish a gNB in the NSA situation, or can I just use eNB standalone?
3. If I open a new gNB, can I set it at the same frequency, that is the dl_arfcn, as eNB?

God bless you.

**Comment by herlesupreeth** [comment]
In the open5gs WebUI, set the IP type as IPv4 rather than IPv4v6, then you would be able to ping

**Comment by ljysdfz** [comment]
@herlesupreeth 
Dear Herle,
Thank you for the timely replys.
I tried to convert session type to IPv4
But UE still cannot ping the 192.168.100.1
and actually this is also the reason the DNS never answered.
Here are the [pcaps](https://github.com/herlesupreeth/docker_open5gs/files/11849994/pcaps.zip)
I tried to use different UEs to test the attachment, of which CPE can be considered as the first-stage target.
And you can find that the test results have many common points:
- They had succeeded in attachment.
- They cannot ping the gateway, that is the ogstun(192.168.100.1)/ogstun2(192.168.101.1).
- They cannot receive any replies from DNS servers, which may possibly be considered as a sequel of previous bullet.
- They failed to do these things after "Activate default EPS bearer context accept", after which sometimes UE faced a context release.
- ...

Compared to the successful gNB connections (for CPE only), there are several suspicious points:
- There are still ipv6 settings taken under way in the upf/upf_init.sh
![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/ac9f26ae-2e35-44e1-b07b-d6f2861a6fb5)
- There are some UL/DL speed limits.
![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/99476b36-d411-40ad-9523-0e32b1e50c1a)
- The srsenb repetitively disconnected and connected, which I've never seen in the NR connection.
![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/26890974-aeae-44cf-873d-aa725c8f4690)
- There is not any IMS-related registration packet. This is why I used CPE as a control experiment for cellphones. CPE is a data centric device so it does not need to establish IMS session. And it failed, so it may be caused by something rather than IMS.
- ...

Do a favor, please.
Salvage me a desperately pathetic guy.

**Comment by ljysdfz** [comment]
@herlesupreeth 
Dear Herle,
On the previous floor, I was trying 4G access because I want to use the IMS subsystem in order to overcome the IMS session establishment request coming from UE.
On this floor, I tried another direction -- 5G SA using Google Pixel 6.
Why I tried it is because I found in the 4G experiment, Google didn't request for a IMS session establishment.
I thought it may bypass the Voice service and utilize Internet directly.
Here is the [pcap](https://github.com/herlesupreeth/docker_open5gs/files/11857798/pcap.zip).
As you can see, the Internet pdu session "default" has been established.
And I use some different PLMN -- "00101".
And DNS reply correctly.
And UE can ping gateway -- UPF.
Everything seemed to be going well.
Unfortunately, it failed as following:
To begin with 5GC connected.
![Screenshot_20230624-165922](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/379ca147-8ca4-4ba2-a827-af7409b9509e)
But no phone services. (Because no IMS)
![Screenshot_20230624-165954](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/caf4769c-3f70-40bd-993d-4b84e4e6ab4b)
Details.
![Screenshot_20230624-170234](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/7901a918-d54b-40dc-97e0-0c1aeea3cdd5)
Finally it cannot access Internet.
![Screenshot_20230624-165832](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/fd83d018-e622-460e-a01b-7cc9583ac14c)

I want to ask:
- Any thought about the problem?
- One of my friends told me that according to 3GPP, N1 will cut off if there is no IMS session establishment for a voice centric UE.  According to all the experiments I have tested, probably this judgment is true? 
- If you can make a voice centric phone establish a data session without voice session existing, could you please tell me how?
- At the halfway, there were always these service requests with a service type marked as "data". Do you know what they exactly did there? Just for UE to apply new data traffic or something else? It looks weird because it went with UE context release.
![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/f0e99570-e5eb-4f3f-a255-cdfbc7b5cf57)

**Comment by ljysdfz** [comment]
@herlesupreeth 
Dear Herle, I tried to ping the Internet immediately following the session establishment.
The ping was successful as follows:
![Screenshot_20230625-082526](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/7b869e4c-f979-4fad-9ca3-f1dfeb6f1be6)
But it stoped after about 3 minutes.
Then I tried to disable the USIM and enable it again (or use airplane mode)
The ping restarted.
Then it stoped after about 3 minutes.
So this showed that the data session has no problem.
The fatal choke hold was the fact that the voice centric mobile requires an IMS session or something else that enbales calls and SMSs.
Is my understanding correct?

**Comment by ljysdfz** [comment]
@herlesupreeth 
Dearr Herle,
I've caught such 2 errors about IMS after the UE attached to a EPC.
Could you please help me analyze what's the real cause behind these errors.

To begin with pcscf.
![Error-pcscf](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/1c1920e0-e40f-4d7a-9951-f0802efb1d30)

Further more is osmohlr. 
![Error-osmohlr](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/304b785f-c21f-4c4f-ad8c-e643a2ed5d70)

**Comment by herlesupreeth** [comment]
Check out this answer as to why Pixel disconnects after 3 minutes

https://github.com/srsran/srsRAN_Project/discussions/100#discussioncomment-6260974


> One of my friends told me that according to 3GPP, N1 will cut off if there is no IMS session establishment for a voice centric UE. According to all the experiments I have tested, probably this judgment is true?

Thats right.

**Comment by ljysdfz** [comment]
@herlesupreeth 
My holy Herle!! you are definitely the 24-karat 360-degree fantastic guy!!
I tried it and I made it !!
A multitude of thanks to you !!
By the way, that author [jonniebeeb](https://github.com/jonniebeeb) said the gNB under srsRAN_4G project could be used without completing an IMS registration.
Do you have a try with this version of srsRAN?

**Comment by herlesupreeth** [comment]
> Do you have a try with this version of srsRAN?

The repo was using srsRAN_4G repo based gNB until recently (https://github.com/herlesupreeth/docker_open5gs/commit/68e0f0125803ba5a4c9cfa03840112b7a23a6296) and then I switched to srsRAN_Project since the latter project supports both FDD and TDD and more feature rich

**Comment by herlesupreeth** [comment]
> In a [ USRP+COTS UE ] setup (rather than ZMQ approach), how actually do you make the container srsgnb/srsenb recognize the USRP?

In the docker compose file (say srsgnb.yaml) you will notice the below lines, which shares the access to USB of the host running the docker

```
    volumes:
      - /dev/serial:/dev/serial:ro
      - /dev/bus/usb:/dev/bus/usb:ro
```

**Comment by ljysdfz** [comment]
@herlesupreeth 
OMG~
I just noticed that B210 actually uses a USB 3.0 as the network interface !!
What a convenient design !!
![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/08bbd77a-bd8c-4cb2-9a6f-2d42508bfc3e)

**Comment by ljysdfz** [comment]
Just checked out the 3GPP TS 23.501 Clause 5.16.3.5 about the voice centric behavior:
![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/e2d6d679-da6e-4144-b905-c7069e69fcb7)
