### ISSUE TITLE
 Amplify signal 10 Watt+ 

### ISSUE THREAD

**Issue by zikkuratti** [herlesupreeth/docker_open5gs#166]
Someone try to Amplify signal 10 Watt+ got some problems with ISI ICI Interference of something like that?

**Comment by herlesupreeth** [comment]
Nope. IMO rather than just amplifying I would put a duplexer between antenna port and amplifier. That way you get clean signal and you would  be amplifying that signal. I am not radio expert so I will let other comment :)

**Comment by zikkuratti** [comment]
yeah ive got duplexer but stil no signal 100m + trying to find some examples or practices? someone use Turbo Convolutional Codes in srsmodulation decoding part but not shure is good way if no signal

**Comment by herlesupreeth** [comment]
Here is one source where they are using duplexer but no amplifier - https://www.crowdsupply.com/lime-micro/limesdr-mini-2/updates/creating-a-private-lte-network-with-srsran
