### ISSUE TITLE
create ipsec failed

### ISSUE THREAD

**Issue by Sivanesh1992** [herlesupreeth/docker_open5gs#167]
Hi ,
I am following below link to enable voice over lte .
https://github.com/herlesupreeth/docker_open5gs

I am trying to make a call by using oneplus 8T mobile after attached the LTE network .

I am getting ipsec failed in wireshark.

![image](https://github.com/herlesupreeth/docker_open5gs/assets/96040330/a2149526-6b4c-4e93-b221-8b7b414eda69)

As per core network log 

mme   | 05/29 12:38:41.523: [emm] INFO:     M-TMSI:[0xc000074a] IMSI:[001010000001131] (../src/mme/emm-handler.c:772)
mme   | 05/29 12:38:41.728: [mme] INFO: UE Context Release [Action:2] (../src/mme/s1ap-handler.c:1526)
mme   | 05/29 12:38:41.728: [mme] INFO:     ENB_UE_S1AP_ID[43] MME_UE_S1AP_ID[43] (../src/mme/s1ap-handler.c:1527)
mme   | 05/29 12:38:41.728: [mme] INFO:     IMSI[001010000001131] (../src/mme/s1ap-handler.c:1530)
mme   | 05/29 12:38:41.728: [mme] INFO: [Removed] Number of eNB-UEs is now 0 (../src/mme/mme-context.c:4042)
mme   | 05/29 12:38:44.350: [gtp] WARNING: [28] REMOTE Request Duplicated. Discard! for step 1 type 176 peer [172.22.0.5]:2123 (../lib/gtp/xact.c:558)
mme   | 05/29 12:38:46.851: [gtp] WARNING: [28] REMOTE Request Duplicated. Discard! for step 1 type 176 peer [172.22.0.5]:2123 (../lib/gtp/xact.c:558)
mme   | 05/29 12:38:47.851: [emm] WARNING: Paging to IMSI[001010000001131] failed. Stop paging (../src/mme/emm-sm.c:144)
sgwc  | 05/29 12:38:47.851: [sgwc] WARNING: GTP Cause [Value:90] - PFCP_CAUSE[77] (../src/sgwc/s11-handler.c:1192)
mme   | 05/29 12:39:14.362: [mme] INFO: InitialUEMessage (../src/mme/s1ap-handler.c:232)
mme   | 05/29 12:39:14.362: [mme] INFO: [Added] Number of eNB-UEs is now 1 (../src/mme/mme-context.c:4035)
mme   | 05/29 12:39:14.362: [mme] INFO:     S_TMSI[G:2,C:1,M_TMSI:0xc000074a] IMSI:[001010000001131] (../src/mme/s1ap-handler.c:304)
mme   | 05/29 12:39:14.362: [mme] INFO:     ENB_UE_S1AP_ID[44] MME_UE_S1AP_ID[44] TAC[1] CellID[0x19b01] (../src/mme/s1ap-handler.c:387)
mme   | 05/29 12:39:14.362: [emm] INFO: [001010000001131] Tracking area update request (../src/mme/emm-sm.c:420)
mme   | 05/29 12:39:14.362: [emm] INFO:     GUTI[G:2,C:1,M_TMSI:0xc000074a] IMSI:[001010000001131] (../src/mme/emm-handler.c:668)

please help me resolve the issue

**Comment by Sivanesh1992** [comment]
HI ,

After change the UE one plus 8T to samsung A52  ,I am trying to call my personal number UE is trying to make call but i am seeing HSS user unknown in wireshark I attached logs and config file please help me to resolve the issue


[amf.log](https://github.com/herlesupreeth/docker_open5gs/files/11598553/amf.log)
[ausf.log](https://github.com/herlesupreeth/docker_open5gs/files/11598555/ausf.log)
[bsf.log](https://github.com/herlesupreeth/docker_open5gs/files/11598556/bsf.log)
[hss.log](https://github.com/herlesupreeth/docker_open5gs/files/11598559/hss.log)
[mme.log](https://github.com/herlesupreeth/docker_open5gs/files/11598561/mme.log)
[nrf.log](https://github.com/herlesupreeth/docker_open5gs/files/11598563/nrf.log)
[nssf.log](https://github.com/herlesupreeth/docker_open5gs/files/11598564/nssf.log)
[pcf.log](https://github.com/herlesupreeth/docker_open5gs/files/11598565/pcf.log)
[pcrf.log](https://github.com/herlesupreeth/docker_open5gs/files/11598566/pcrf.log)
[scp.log](https://github.com/herlesupreeth/docker_open5gs/files/11598567/scp.log)
[sgwc.log](https://github.com/herlesupreeth/docker_open5gs/files/11598568/sgwc.log)
[sgwu.log](https://github.com/herlesupreeth/docker_open5gs/files/11598569/sgwu.log)
[wiresharklog.zip](https://github.com/herlesupreeth/docker_open5gs/files/11598601/wiresharklog.zip)

[smf.log](https://github.com/herlesupreeth/docker_open5gs/files/11598570/smf.log)
[udm.log](https://github.com/herlesupreeth/docker_open5gs/files/11598571/udm.log)
[udr.log](https://github.com/herlesupreeth/docker_open5gs/files/11598572/udr.log)
[upf.log](https://github.com/herlesupreeth/docker_open5gs/files/11598573/upf.log)

**Comment by herlesupreeth** [comment]
If you are trying to call a number which is not registered in your local IMS then its not possible

**Comment by herlesupreeth** [comment]
If your SIM is issued by local mobile operator then you would not be able to get the K, OP/OPc value of your SIM which are needed for authentication. If you have them then you can add them in open5gs WebUI and also in FHoSS webpage

**Comment by Sivanesh1992** [comment]
ok , I am using opencells simcard ,so i need to add both simcard details in open5gs webui and Fhoss webpage  .

suppose I switched master to open5gs_hss_cx branch , i need to add simcard details in  open5gs webui  only right?

correct me if my understanding is wrong means

**Comment by herlesupreeth** [comment]
> suppose I switched master to open5gs_hss_cx branch , i need to add simcard details in open5gs webui only right?

That is correct. Dont forget to add MSISDN in open5gs webui. You would have to add IMSI and MSISDN to omsohlr as well as mentioned here - https://github.com/s5uishida/docker_open5gs_volte_sms_config#register-the-imsi-and-msisdn-with-osmohlr. This is because SMS over SGs interface is enabled by default.

**Comment by Sivanesh1992** [comment]
thankyou for your support, now voice call is established after upgrade the OS version 11 to 12

**Comment by Sivanesh1992** [comment]
`

**Comment by Sivanesh1992** [comment]
issue resolved
