### ISSUE TITLE
Not able to see LTE signal in Redmi mobile

### ISSUE THREAD

**Issue by Sivanesh1992** [herlesupreeth/docker_open5gs#168]
Hi,

I am using test simcard to test LTE .open5gs core network are up and running and i started using below command

docker_open5gs$ docker-compose -f srsenb.yaml up -d && docker attach srsenb

then i turn OFF airplane mode and doing manual network search . i am not able to the network in network list.
below  APN setting i given in redmi mobile

apn: internet , 
APN type : default ,
mcc:001
 mnc:01  ,
APN protocol : ipv4
APN  roaming protocol : ipv4
APN: enabled

Please  give me some tips to troubleshoot the issue

I am able to attache oneplus 8T and samsung A42 mobile but why redmi mobile i am able to see network .

**Comment by Sivanesh1992** [comment]
I am using usrpB210 no external clock .kindly find the attached log for your reference 

in srsenb console :

:docker_open5gs$ docker-compose -f srsenb.yaml up -d && docker attach srsenb
WARNING: Found orphan containers (udr, amf, ausf, scscf, pcscf, sgwc, smsc, smf, osmomsc, icscf, scp, nssf, mme, pcf, rtpengine, nrf, udm, upf, bsf, osmohlr, dns, srsenb_zmq, metrics, pcrf, mongo, webui, sgwu, mysql, srsgnb, hss) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Recreating srsenb ... done

Built in Release mode using commit 10f81ca03 on branch lc/main.

Opening 1 channels in RF device=default with args=default
Supported RF device list: UHD soapy zmq lime file
Trying to open RF device 'UHD'
[INFO] [UHD] linux; GNU C++ version 9.4.0; Boost_107100; UHD_4.4.0.0-0ubuntu1~focal1
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=1, args: type=b200,master_clock_rate=23.04e6
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [B200] Detected Device: B210
[INFO] [B200] Loading FPGA image: /usr/share/uhd/images/usrp_b210_fpga.bin...
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Detecting internal GPSDO.... 
[INFO] [GPS] No GPSDO found
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
RF device 'UHD' successfully opened

==== eNodeB started ===
Type <t> to view trace
Setting frequency: DL=2660.0 Mhz, UL=2540.0 MHz for cc_idx=0 nof_prb=50
^CStopping ..
---  exiting  ---
i am not able to attach pcap file because file size is 147 MB , i will attach core network log please help me.

Please share me your email id if possible i will share pcap log


[ausf.log](https://github.com/herlesupreeth/docker_open5gs/files/11651470/ausf.log)
[nssf.log](https://github.com/herlesupreeth/docker_open5gs/files/11651471/nssf.log)
[upf.log](https://github.com/herlesupreeth/docker_open5gs/files/11651472/upf.log)
[sgwc.log](https://github.com/herlesupreeth/docker_open5gs/files/11651473/sgwc.log)
[sgwu.log](https://github.com/herlesupreeth/docker_open5gs/files/11651474/sgwu.log)
[bsf.log](https://github.com/herlesupreeth/docker_open5gs/files/11651475/bsf.log)
[pcf.log](https://github.com/herlesupreeth/docker_open5gs/files/11651476/pcf.log)
[udm.log](https://github.com/herlesupreeth/docker_open5gs/files/11651477/udm.log)
[udr.log](https://github.com/herlesupreeth/docker_open5gs/files/11651478/udr.log)
[pcrf.log](https://github.com/herlesupreeth/docker_open5gs/files/11651480/pcrf.log)
[mme.log](https://github.com/herlesupreeth/docker_open5gs/files/11651481/mme.log)
[amf.log](https://github.com/herlesupreeth/docker_open5gs/files/11651482/amf.log)
[hss.log](https://github.com/herlesupreeth/docker_open5gs/files/11651483/hss.log)
[smf.log](https://github.com/herlesupreeth/docker_open5gs/files/11651484/smf.log)
[nrf.log](https://github.com/herlesupreeth/docker_open5gs/files/11651485/nrf.log)
[scp.log](https://github.com/herlesupreeth/docker_open5gs/files/11651486/scp.log)

**Comment by herlesupreeth** [comment]
It looks like your phone is not seeing the eNB at all. If you have access to external clock then it would be highly helpful in these situations. USRP B210 clock tends to drift a lot. If you dont have access to external clock, then I would suggest to tweak the following value in enb.conf and give it a try. You could try setting that value to say from 100 to 300.

#time_adv_nsamples = auto

**Comment by Sivanesh1992** [comment]
sorry for delay response . as per you suggestion i try to increase the  time_adv_nsamples  from 100 to 300, but still i am not able to see the network name while doing manual search in redmi note 4 mobile(Android 11.0.2.0)

please give me idea how to debug.

below enb terminal log

:docker_open5gs$ docker-compose -f srsenb.yaml up -d && docker attach srsenb
WARNING: Found orphan containers (webui, pcscf, scp, nssf, metrics, sgwc, amf, ausf, mme, osmohlr, udr, dns, upf, srsgnb, bsf, hss, pcrf, mongo, pcf, osmomsc, srsenb_zmq, sgwu, udm, scscf, rtpengine, smf, mysql, smsc, nrf, icscf) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting srsenb ... done

Built in Release mode using commit 10f81ca03 on branch lc/main.

Opening 1 channels in RF device=default with args=default
Supported RF device list: UHD soapy zmq lime file
Trying to open RF device 'UHD'
[INFO] [UHD] linux; GNU C++ version 9.4.0; Boost_107100; UHD_4.4.0.0-0ubuntu1~focal1
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=1, args: type=b200,master_clock_rate=23.04e6
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
RF device 'UHD' successfully opened

==== eNodeB started ===
Type <t> to view trace
Setting manual TX/RX offset to 300 samples
Setting frequency: DL=2660.0 Mhz, UL=2540.0 MHz for cc_idx=0 nof_prb=50

**Comment by herlesupreeth** [comment]
> please give me idea how to debug.

Try setting the log level to debug for all layer in enb.conf

You could try reducing the cell bandwidth to 25 RBs in enb.conf (reset  time_adv_nsamples value to as it was before, I guess auto)

`n_prb = 25`

**Comment by Sivanesh1992** [comment]
after chanage the 25 rbs also facing same issue

docker-compose -f srsenb.yaml up -d && docker attach srsenb
WARNING: Found orphan containers (dns, amf, scscf, scp, webui, pcrf, ausf, bsf, hss, upf, pcscf, smf, smsc, rtpengine, pcf, metrics, mme, nssf, udm, mysql, udr, sgwc, osmomsc, icscf, nrf, mongo, osmohlr, sgwu, srsenb_zmq, srsgnb) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting srsenb ... done

Built in Release mode using commit 10f81ca03 on branch lc/main.

Opening 1 channels in RF device=default with args=default
Supported RF device list: UHD soapy zmq lime file
Trying to open RF device 'UHD'
[INFO] [UHD] linux; GNU C++ version 9.4.0; Boost_107100; UHD_4.4.0.0-0ubuntu1~focal1
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=1, args: type=b200,master_clock_rate=23.04e6
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
RF device 'UHD' successfully opened

==== eNodeB started ===
Type <t> to view trace
Setting frequency: DL=2660.0 Mhz, UL=2540.0 MHz for cc_idx=0 nof_prb=25

Kindly find the attached enb config file

[enb.zip](https://github.com/herlesupreeth/docker_open5gs/files/11674907/enb.zip)

**Comment by Sivanesh1992** [comment]
hi 
[enb.log](https://github.com/herlesupreeth/docker_open5gs/files/11675193/enb.log)
pls find the attached debug log . please help me resolve the issue

**Comment by Sivanesh1992** [comment]
@herlesupreeth please help to resolve this issue

**Comment by herlesupreeth** [comment]
@Sivanesh1992 Over the air issues are difficult to debug. I would sugges thte following

1. Either buy a GPSDO as its really helps in both 4G and 5G attach failing cases
2. Or change the EARFCN to say dl_earfcn = 6300 and give it a try
3. Switch on eNB and keep it running and place the phone quite near to eNB and leave it there for quite sometime. I have seen phone attach after some random time.

I hope you are using an antenna for increased signal strength from eNB
