### ISSUE TITLE
May i ues outside gNB(on a different host) to connect this docker with open5gs ?

### ISSUE THREAD

**Issue by alf-askey** [herlesupreeth/docker_open5gs#17]
Hi herlesupreeth,
Very thank you to help much on corenetwork and IMS , I got much knowledge from you
(I just got in touch with LTE / 5G related knowledge not long ago )

i have one more issue

Now LTE small cell ready and phone can attached and access internet successfuly 
but i wanna use outside gNB(on a different host) to connect this docker with open5gs

gnb(192.188.2.251) <-----ngap/gtp----->(192.188.2.2)host with docket_open5gs(172.22.x.x)

if i wanna external gNB(SA,NSA),do i only just need to do the below 2 steps? 

step 1) modify "UPF" of .env and lanuch "source .env"

In UPF:
**UPF_ADVERTISE_IP=192.188.2.2**

below is LTE parameter
SGW:
SGWU_ADVERTISE_IP=192.188.2.2

then 
source .env

step 2) Uncomment the following and add ports' parameter in docker-compose.yaml 
 
In amf:
    # ports:
    #   - "38412:38412/sctp"
  after i add this , i can attachd successfully . 
  if phone can access internet , i must config upf ,right or not ?

In upf:
    Does it follow sgwu format to add ports parameter ? if i have add below parameter: 
    ports:
       - "2152:2152/udp"
    , it will error "0.0.0:2152 failed: port is already allocated" 

below is LTE's parameter
In mme

    # ports:
    #   - "36412:36412/sctp"
In sgwu

    # ports:
    #   - "2152:2152/udp"

**Comment by alf-askey** [comment]
if comment sgwu, upf can run successfully and  phone access internet  , so how to let LTE/5G  can access internet at the same time .
In sgwu
# ports:
#   - "2152:2152/udp"

**Comment by herlesupreeth** [comment]
Since both SGWU and UPF both use 2152 port its not possible to support both SA+NSA and have gNB in another host. But if you run only SA mode then its possible as follows

When running in SA mode, set UPF_ADVERTISE_IP=192.188.2.2 and uncomment the following sections

In amf

```
    # ports:
    #   - "38412:38412/sctp"
```

In upf

```
    # ports:
    #   - "2152:2152/udp"
```

**Comment by herlesupreeth** [comment]
or you need to have an virtual interface on the 192.168.2.2 machine and do as follows, but make that the virtual interface is reachable by gNB

In sgwu

```
    ports:
        - "<VIRTUAL_IP_1>:2152:2152/udp"
```

In upf

```
    ports:
        - "<VIRTUAL_IP_2>:2152:2152/udp"
```

**Comment by alf-askey** [comment]
thank you
