### ISSUE TITLE
Cannot create ipsec for volte

### ISSUE THREAD

**Issue by aseaudi** [herlesupreeth/docker_open5gs#172]
in some cases, the UE does not send the ipsec parameters in the IMS Register
this causes the pcscf to reject the registration, as shown in the logs below
what is the reason for this ? why the ue does not send the ipsec parameters ?
also, when i try in another installation, like magma, the same ue sends the parameters
i tried comparing several s1ap messages to deduce the reason the ue send or not send ipsec, but i don't find 

![image](https://github.com/herlesupreeth/docker_open5gs/assets/28780402/443e6734-d0ed-49a6-ba00-4628b7ee6492)

 2(47) NOTICE: <script>: PCSCF: REGISTER sip:ims.mnc0xx.mccxxx.3gppnetwork.org (sip:xxxxxxxxxxxxxx@ims.mncxxx.mccxxx.3gppnetwork.org (192.168.xxx.xxx:5060) to sip:xxxxxxxxxxx@ims.mncxxx.mccxxx.3gppnetwork.org, uPn1hdKNfzlDicikN2jdWNls)
 2(47) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
 2(47) NOTICE: <script>: PCSCF REGISTER: 
 Destination URI: <null>
 Request URI: sip:ims.mncxxx.mccxxx.3gppnetwork.org
 2(47) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
 2(47) NOTICE: <script>: Source IP and Port: (192.168.xxx.xxx:5060)
 Route-URI: 
 2(47) NOTICE: <script>: Received IP and Port: (172.22.0.21:5060)
 2(47) NOTICE: <script>: Contact header: <sip:192.168.xxx.xxx:5060>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.smsip;+sip.instance="<urn:gsma:imei:xxxxxxxxx-xxxxxxx-0>"
 2(47) INFO: ims_registrar_pcscf [sec_agree.c:264]: cscf_get_security(): No security parameters found
 2(47) INFO: ims_registrar_pcscf [sec_agree.c:296]: cscf_get_security_verify(): No security-verify parameters found
 2(47) ERROR: ims_ipsec_pcscf [ipsec.c:582]: clean_sa(): Error sending delete SAs command via netlink socket: No data available
 2(47) WARNING: ims_ipsec_pcscf [cmd.c:1170]: ipsec_cleanall(): Error cleaning IPSec Security associations during startup.
 2(47) ERROR: ims_ipsec_pcscf [ipsec.c:624]: clean_policy(): Error sending delete policies command via netlink socket: No data available
 2(47) WARNING: ims_ipsec_pcscf [cmd.c:1174]: ipsec_cleanall(): Error cleaning IPSec Policies during startup.
 2(47) INFO: cdp [authstatemachine.c:270]: auth_client_statefull_sm_process(): after callback of event 1
94(139) INFO: cdp [authstatemachine.c:270]: auth_client_statefull_sm_process(): after callback of event 7
 4(49) ERROR: ims_ipsec_pcscf [cmd.c:680]: ipsec_create(): No security parameters found in contact
 4(49) NOTICE: <script>: Expires=600000
 4(49) NOTICE: <script>: Old header - WWW-Authenticate=Digest realm="ims.mncxxx.mccxxx.3gppnetwork.org", nonce="78xMUeJgoBfxyPZNlKDavqS2qU/qqIAACGTTxtFRV2c=", algorithm=AKAv1-MD5, ck="fc418658c06ad5b7d90c28ddaa7f0619", ik="1429b37d3cf531db0ddb5155587ccf5d", qop="auth,auth-int"
 4(49) NOTICE: <script>: New header - WWW-Authenticate=Digest realm="ims.mncxxx.mccxxx.3gppnetwork.org", nonce="78xMUeJgoBfxyPZNlKDavqS2qU/qqIAACGTTxtFRV2c=", algorithm=AKAv1-MD5, qop="auth,auth-int"

[herlesupreeth-ispec-ims.pcapng.zip](https://github.com/herlesupreeth/docker_open5gs/files/11714671/herlesupreeth-ispec-ims.pcapng.zip)

**Comment by herlesupreeth** [comment]
Please provide the pcap with issue in order to debug

**Comment by aseaudi** [comment]
hi, i attached a pcap file, if you need another one tell me.

**Comment by herlesupreeth** [comment]
@aseaudi Can you describe your setup with IPs ?? There are 3 differents network IPs , 10.0.2.x , 192.168,128.x , 172.16.221.135

Is your IMS running on a different machine than EPC?

**Comment by aseaudi** [comment]
I attach another capture here, 2 mobiles, 192.168.101.4 (ipsec ok) and 192.168.101.5 (ipsec nok), using the default test network for open5gs 172.22.0.0.
[sip-ims-register-2-mobiles.pcapng.zip](https://github.com/herlesupreeth/docker_open5gs/files/11714889/sip-ims-register-2-mobiles.pcapng.zip)

**Comment by herlesupreeth** [comment]
The device with IP 192.168.101.5 is not sending Security-Client SIP header and is not requesting IPSec connection. And, I am guessing you are not using kamailio from this fork - https://github.com/herlesupreeth/kamailio since I dont remember logic present in there to reject non-IPsec connections with 503.

**Comment by aseaudi** [comment]
@herlesupreeth iam using your docker_open5gs dovker-compose, using default images, i did not modify anything. The device is iphone, but i noticed it also with samsung.  how does your fork kamailio handle a device that does not send sip ipsec header ?

**Comment by herlesupreeth** [comment]
ummm then its strange...then you apply the below patch and give it a try?

```
diff --git a/pcscf/route/register.cfg b/pcscf/route/register.cfg
index de33391..0cb412a 100644
--- a/pcscf/route/register.cfg
+++ b/pcscf/route/register.cfg
@@ -261,10 +261,10 @@ onreply_route[REGISTER_reply]
        }
        else {
                if (t_check_status("401")) {
-                       if(ipsec_create("location")!=1) {
+                       if($(T_req($hdr(Security-Client))) != $null && ipsec_create("location")!=1) {
                                send_reply("503", "Service Unavailable (Create ipsec failed)");
                        }
-                       if ($sht(ipsec_clients=>$(T_req($ct){nameaddr.uri})) != $null) {
+                       if ($(T_req($hdr(Security-Client))) != $null && $sht(ipsec_clients=>$(T_req($ct){nameaddr.uri})) != $null) {
                                $var(sec_client) = $(T_req($hdr(Security-Client)));
                                xnotice("Security-Client=$var(sec_client)\n");
                                $var(sc_port_c) = $(var(sec_client){re.subst,/.*port-c=([0-9]*).*$/\1/s});
```

**Comment by aseaudi** [comment]
From what i see, the code says, if the request does not have Security-Client Header, the REGISTER fails, is my understanding correct ?
If yes, is there another way we can deal with mobile phones that do not sent the Security-Client header in the REGISTER message ?

**Comment by aseaudi** [comment]
also from RFC 3329:
   A server that by policy requires the use of this specification and
   receives a request that does not have the sec-agree option tag in a
   Require, Proxy-Require or Supported header field MUST return a 421
   (Extension Required) response.  If the request had the sec-agree
   option tag in a Supported header field, it MUST return a 494
   (Security Agreement Required) response.  In both situation the server
   MUST also include in the response a Security-Server header field
   listing its capabilities and a Require header field with an option-
   tag "sec-agree" in it.  The server MUST also add necessary
   information so that the client can initiate the preferred security
   mechanism (e.g., a Proxy-Authenticate header field for HTTP Digest).

**Comment by herlesupreeth** [comment]
> from what i see, the code says, if the request does not have Security-Client Header, the REGISTER fails, is my understanding correct ?

No, basically it checks whether the REGISTER request has Security-Client header or not and if yes then tries to create IPSec (if its fails then sends 503). If there is no Security-Client header then it proceeds without creating IPSec and registration should proceed

**Comment by herlesupreeth** [comment]
Strange thing is, I have an Oneplus 5 which does not use IPSec and the registration works. Can you post the pcap with the patch I sent applied??

**Comment by aseaudi** [comment]
i sent the file privately, 
do you mean oneplus 5 does not use IPSEC at all, 
or do you mean it does not initiate IPSEC, and waits for the pcscf to initiate IPSEC ?

**Comment by herlesupreeth** [comment]
> do you mean oneplus 5 does not use IPSEC at all,

Yes, it does not use IPSec


> or do you mean it does not initiate IPSEC, and waits for the pcscf to initiate IPSEC ?

Oneplus 5 does not initiate IPSec. But in general its the phone which decide whether it wants to use IPSec or not (although PCSCF can enforce but in that phones not supporting IPSec wont be able to connect to IMS)

> i sent the file privately,

Havent had time to take a look but do over the weekend. Btw, please attach the pcap here in the github itself. In order to upload here in github you need to compress the pcap in either .zip or .tar format andf then upload

**Comment by aseaudi** [comment]
@herlesupreeth pcap attached here below
[supreeth.pcapng.zip](https://github.com/herlesupreeth/docker_open5gs/files/11768428/supreeth.pcapng.zip)

**Comment by herlesupreeth** [comment]
Thanks @aseaudi . I took a look at pcap you sent in email and I believe the patch I gave is working. Now I believe the issue may be in the authentication parameters dont match. Can you verify whether the Ki, OP/OPc what you programmed the SIM with matches that in FHoSS ??

**Comment by aseaudi** [comment]
thanks @herlesupreeth , i will double-check
could you tell me how you reached this conclusion ?

**Comment by herlesupreeth** [comment]
Thats because even in the second or third REGISTER, the phone is not sending "Digest Authentication Response" in Authorization SIP header.

**Comment by aseaudi** [comment]
Your are right, it worked, it is now registered, without IPSEC, thanks to the patch. Thanks a lot, appreciated.
By the way, did you ever see a SIM that makes the VOLTE settings toggle option disappears from the network connections menu ? What might make a SIM make the VOLTE option disappear ?
When i use a different SIM, the VOLTE toggle switch option appears again in the settings network connection menu.

**Comment by herlesupreeth** [comment]
> By the way, did you ever see a SIM that makes the VOLTE settings toggle option disappears from the network connections menu ? 

Well, thats because by default Android configuration are set to hide those VoLTE settings. They are only shown for certain operators for which Android configuration has it enabled.

**Comment by aseaudi** [comment]
anyway we can force android to open volte settings if the plmn is not enabled by default for volte ?

**Comment by herlesupreeth** [comment]
> anyway we can force android to open volte settings if the plmn is not enabled by default for volte ?

Not always. Depends on phone vendors in the end
