### ISSUE TITLE
Unable to compose up

### ISSUE THREAD

**Issue by poisonmuthu70** [herlesupreeth/docker_open5gs#184]
1. I try to compose up but i am facing the below issue

docker-compose up
WARNING: Found orphan containers (srsenb) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Pulling icscf (docker_kamailio:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]N
ERROR: pull access denied for docker_kamailio, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by herlesupreeth** [comment]
Please re-read the README. You need to compile docker_kamailio image first
