### ISSUE TITLE
OCS Interface 

### ISSUE THREAD

**Issue by mycloudbss** [herlesupreeth/docker_open5gs#19]
Hi,
First of all congrats for the work, I have a couple of questions (if this is the wrong place to ask it, let me know and I'll delete it).

1. It would be really nice to see an OCS integration, is it possible to connect the PCRF and PGW with it? I believe this would be done by a 127.0.0.X IP, right? Is this something simple to implement? It would be nice to check the support to OCS

2- I'm intrigued, is it possible to have support for an external HSS, like Oracle,Cisco, etc...the same way you have multi-platform support for Enode-B?

**Comment by herlesupreeth** [comment]
1. For OCS integration I believe PGW of open5gs does not support Gy interface. If it supports then should quite straightforward to integrate with thrid-party OCS if they are standard complaint 
2. Definitely possible, just dont run the open5gs HSS and publish port 3868 of MME for Diameter connection between HSS and MME as in following example of docker-compose file

```
    ports:
      - "3868:3868/tcp"
      - "3868:3868/sctp"
```

**Comment by mycloudbss** [comment]
Hi 
Thank you ..so in this case i ahve to change IP address and port to OCS IP ?

![Uploading Screen Shot 2021-01-25 at 11.58.31 AM.png…]()

**Comment by herlesupreeth** [comment]
Please re-read this comment again

> For OCS integration I believe PGW of open5gs does not support Gy interface. If it supports then should quite straightforward to integrate with thrid-party OCS if they are standard complaint

**Comment by mycloudbss** [comment]
Ok got it ...so we have to wait for some time untill they start supporting Gy..

**Comment by herlesupreeth** [comment]
Well, regarding that I am not sure whether open5gs has Gy interface in their development pipeline. Better to raise an issue in open5gs project asking about it.

**Comment by herlesupreeth** [comment]
Closing this issue as there is no support for Gy interface in open5gs

**Comment by Takuto88** [comment]
Gy interface support is now available in open5gs. See: https://github.com/open5gs/open5gs/pull/1479
