### ISSUE TITLE
SMS retries syntax in kamailio_smsc.cfg incorrect

### ISSUE THREAD

**Issue by bem4444** [herlesupreeth/docker_open5gs#190]
In the kamailio_smsc.cfg the sql query does not work.

The current line is: `sql_query("sms", "delete from messages where id=$sht(sms_retries=>$dbr(q=>[$var(i),0]));");` 
This will always attempt to delete id=3. It should probably just be `id=$dbr(q=>[$var(i),0])`

**Comment by herlesupreeth** [comment]
Ah true..thanks for noticing this.
