### ISSUE TITLE
 [mme] WARNING: S1-Setup failure: (../src/mme/s1ap-handler.c:185)

### ISSUE THREAD

**Issue by Sivanesh1992** [herlesupreeth/docker_open5gs#193]
hi @herlesupreeth  in Pi4B  docker open5gs is up and running  

i am running srs lte outside the docker . i was checked mcc =001 and mnc =01 in both are same  .env file and srsran config file 

As per enb log  i am getting below error:

S1setup failed
Failed to initiate S1 connection. Attempting reconnection in 10 seconds
S1 Setup Failure. Cause: misc - unknown-PLMN

MME log:

07/26 15:54:51.526: [mme] WARNING:     Cannot find Served TAI. Check 'mme.tai' configuration (../src/mme/s1ap-handler.c:186)
07/26 15:54:51.546: [mme] INFO: eNB-S1[192.168.2.226] connection refused!!! (../src/mme/mme-sm.c:166)
07/26 15:54:51.550: [mme] INFO: [Removed] Number of eNBs is now 0 (../src/mme/mme-context.c:2583)
07/26 15:55:01.544: [mme] INFO: eNB-S1 accepted[192.168.2.226]:50689 in s1_path module (../src/mme/s1ap-sctp.c:114)
07/26 15:55:01.545: [mme] INFO: eNB-S1 accepted[192.168.2.226] in master_sm module (../src/mme/mme-sm.c:108)
07/26 15:55:01.546: [mme] INFO: [Added] Number of eNBs is now 1 (../src/mme/mme-context.c:2549)
07/26 15:55:01.547: [mme] INFO: eNB-S1[192.168.2.226] max_num_of_ostreams : 30 (../src/mme/mme-sm.c:150)
07/26 15:55:01.549: [mme] WARNING: S1-Setup failure: (../src/mme/s1ap-handler.c:185)
07/26 15:55:01.550: [mme] WARNING:     Cannot find Served TAI. Check 'mme.tai' configuration (../src/mme/s1ap-handler.c:186)
07/26 15:55:01.557: [mme] INFO: eNB-S1[192.168.2.226] connection refused!!! (../src/mme/mme-sm.c:166)
07/26 15:55:01.559: [mme] INFO: [Removed] Number of eNBs is now 0 (../src/mme/mme-context.c:2583)

**Comment by herlesupreeth** [comment]
> 07/26 15:55:01.550: [mme] WARNING: Cannot find Served TAI. Check 'mme.tai' configuration (../src/mme/s1ap-handler.c:186)

TAI in MME config and SRS LTE eNB config should match

**Comment by Sivanesh1992** [comment]
yes i understand but bot mcc and mnc is same in both mme config .

In mme yml file i seen TAC=1 but i am not able to find TAC  in srsenb file . please give some idea

**Comment by herlesupreeth** [comment]
It should be in rr.conf file

**Comment by Sivanesh1992** [comment]
thankyou @herlesupreeth
