### ISSUE TITLE
docker-compose fails installing jdk

### ISSUE THREAD

**Issue by psravikiran** [herlesupreeth/docker_open5gs#196]
Hi,
 docker-compose is failing loading the JDK 7u80 with the following error. Is there any simple solution?

$$:~/docker_open5gs$ docker-compose up
Building fhoss
Step 1/13 : FROM ubuntu:focal
 ---> 14be0685b768
Step 2/13 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 35e29103bb15
Step 3/13 : RUN apt-get update &&       apt-get -y install git vim wget subversion mysql-server
 ---> Using cache
 ---> f49138fb442e
Step 4/13 : RUN mkdir -p  /usr/lib/jvm/ &&      cd / && wget https://files-cdn.liferay.com/mirrors/download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz &&   tar -zxf /jdk-7u80-linux-x64.tar.gz -C /usr/lib/jvm/ &&      update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk1.7.0_80/bin/java 100 &&       update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk1.7.0_80/bin/javac 100
 ---> Running in b3fc57b68979
--2023-07-31 16:02:03--  https://files-cdn.liferay.com/mirrors/download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz
Resolving files-cdn.liferay.com (files-cdn.liferay.com)... 104.18.29.95, 104.18.28.95, 2606:4700::6812:1c5f, ...
Connecting to files-cdn.liferay.com (files-cdn.liferay.com)|104.18.29.95|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2023-07-31 16:02:04 ERROR 500: Internal Server Error.

ERROR: Service 'fhoss' failed to build: The command '/bin/sh -c mkdir -p  /usr/lib/jvm/ &&      cd / && wget https://files-cdn.liferay.com/mirrors/download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz &&        tar -zxf /jdk-7u80-linux-x64.tar.gz -C /usr/lib/jvm/ &&         update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk1.7.0_80/bin/java 100 &&       update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk1.7.0_80/bin/javac 100' returned a non-zero code: 8
========================
Thank you,
Ravi

**Comment by herlesupreeth** [comment]
> Is there any simple solution?

I would suggest to use open5gs_hss_cx branch for now until the above issue is resolved

**Comment by herlesupreeth** [comment]
All instance of FhoSS has now been removed from this repo and moved to pyHSS so this should not be an issue anymore. Please re-open the issue with pcaps and logs if you still face issue.

**Comment by psravikiran** [comment]
Thank you.
