### ISSUE TITLE
docker-compose build failed

### ISSUE THREAD

**Issue by shanmukhapothana** [herlesupreeth/docker_open5gs#202]
Hi Team,

We are try to deploying the docker_open5gs in ubuntu 22.04 OS and following the command is :

docker-compose build --no-cache

While running the above command, we are getting this below error.

 docker-compose build --no-cache
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml
        
Please help me to resolve this issue.

**Comment by herlesupreeth** [comment]
Ah my bad. I will update the README. You can skip that step

**Comment by shanmukhapothana** [comment]
Thanks for the update.
