### ISSUE TITLE
UE failed to connect to eNB

### ISSUE THREAD

**Issue by pelopor23** [herlesupreeth/docker_open5gs#206]
Hi @herlesupreeth,

I have already configure the parameter according to the info in the github and open5gs website, but the UE failed to connect to eNB.

Could you please give advice regarding this issue, and please check the following pcap file:
[UE_fail_to_connect.zip](https://github.com/herlesupreeth/docker_open5gs/files/12311545/UE_fail_to_connect.zip)

Thanks for your advice,

**Comment by herlesupreeth** [comment]
![image](https://github.com/herlesupreeth/docker_open5gs/assets/4115839/70ef2a72-8bb9-4624-9647-1c307a475c67)

Looks like open5s is rejecting the attach with protocol error. I would suggest to raise an issue in open5gs repo

**Comment by pelopor23** [comment]
Hi @herlesupreeth 

I've try to install open5gs & srsran on a non-docker environment and it works fine, so I guess the issue is not at open5gs. 
Is there any settings that I have to add in order to be able to register the ue?

Please advice,
Thanks

**Comment by herlesupreeth** [comment]
> I've try to install open5gs & srsran on a non-docker environment and it works fine, so I guess the issue is not at open5gs.

Then I guess you are using different versions of open5gs (check the commit id).

Also, can you please tell which gNB you are using??

**Comment by pelopor23** [comment]
I installed the Open5GS on non-docker environment using this method: https://open5gs.org/open5gs/docs/tutorial/01-your-first-lte/

How to use this version of open5gs on docker environment?

Thanks

**Comment by herlesupreeth** [comment]
I am not sure which commit is being used when its packaged for ubuntu. But I am guessing it when a tagged release is done.

In that case you could change the following file contents - https://github.com/herlesupreeth/docker_open5gs/blob/master/base/Dockerfile

as follows:

```
# Get open5gs code and install
RUN git clone --recursive https://github.com/open5gs/open5gs && cd open5gs && \
    git checkout tags/v.2.6.4 && meson build --prefix=`pwd`/install && \
    ninja -C build && cd build && ninja install && \
    mkdir -p /open5gs/install/include
```

**Comment by pelopor23** [comment]
Hi @herlesupreeth 

Just want to confirm that the problem is solved now. Previously I skip the registration at OsmoHLR, I've only register the IMSI through Open5GS web console. Also, the code is working fine, no need to modify the dockerfile.

Thanks for your support
