### ISSUE TITLE
IMS registration failure - qop specified with no nonce count

### ISSUE THREAD

**Issue by ljysdfz** [herlesupreeth/docker_open5gs#213]
Dear Herle and guys.
I'm still trying a FHoSS based docker_open5gs.

These are references I've been following:
https://github.com/s5uishida/docker_open5gs_volte_sms_config/tree/cee56f3c5d950b6ba774b5f147be3f73cac262fd
https://open5gs.org/open5gs/docs/tutorial/03-VoLTE-dockerized/
https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/

But I stumbled upon a SIP registration failure where the S-CSCF prompted "qop specified with no nonce count".

Here are the prompting feedbacks from CSCFs, in which you can see the red-color error:
![CSCF](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/b04e6377-0ecf-45e0-97a9-98a5793647aa)

Here are the prompting feedbacks from FHoSS:
![FHoSS](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/c600a4ce-835b-4fef-8f77-1ec485d44e57)

Here are the prompting feedbacks from MME:
![MME](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/1330efa8-e43a-4824-a879-d8bce513f2f2)

Here is the pcaps captured at IMS and S1 respectively.
[pcap.zip](https://github.com/herlesupreeth/docker_open5gs/files/12403400/pcap.zip)

I've checked a lot of historical posts about IMS registration failures, but I cannot find a relevant problem.
These are historical discussions related to registration failures I've studied:
https://github.com/open5gs/open5gs/issues/462
https://github.com/open5gs/open5gs/issues/509
https://github.com/open5gs/open5gs/issues/486

BTW, all of them had Herle involved. :D
I found that Herle has finished a lot of patches mentioned in these issues.
I have tried to align the SQNs in both open5gs (dec mode) and FHoSS (hex mode) through WebUI.
I have also removed S-CSCF in the IMPI RTR area.
But nothing changes.
I found that the UE had issued the 2nd registration request.
But as you can see, the S-CSCF didn't pass the authentication.
I'm not quite familiar with the registration details, though I've got some slides about it.
I only understand the overall process.
It seems that the nonce is just random+AUTS.
I cannot understand why the nonce count mattered and how it worked.
Because I actually cannot find out where it was used.
I would appreciate if you guys tell me ideas about this.

**Comment by herlesupreeth** [comment]
From the pcap you attached above, I think the SIM details entered in FHoSS maybe wrong. Can you please verify whether Ki, OP/OPc value is correct and match the one provided in open5gs??

**Comment by ljysdfz** [comment]
> From the pcap you attached above, I think the SIM details entered in FHoSS maybe wrong. Can you please verify whether Ki, OP/OPc value is correct and match the one provided in open5gs??

My fault, man.
I should've put up the configurations beforehand.

![open5gs](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/12a1664f-53ba-482a-ba6f-4f7a1e782f92)

![IMSU](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/b3a547b6-e334-4484-8876-d40f01a8a7c5)

![IMPI](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/4794f3e5-72c0-4693-81e1-2ed73cf68505)

![IMPU](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/651313df-0c92-47fb-bab3-75525a4a99c0)

Actually, nothing different.

**Comment by herlesupreeth** [comment]
Can you please also post the images of the other IMPUs you set for this subsriber in FHoSS??

**Comment by ljysdfz** [comment]
Roger that :D

![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/e3abdda8-5bcb-4b15-8b17-b3bb813a5668)

![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/8ab225e0-fed5-4096-ae26-22561e6b3ec7)

And here is the USIM:
![USIM](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/3f420ead-5164-4a3b-b37a-ebaa817e1afa)

**Comment by ljysdfz** [comment]
> Can you please also post the images of the other IMPUs you set for this subsriber in FHoSS??

I tried to unlock all the 4G features of my Pixel 6
OMG.. It finally ended up with only 1 register now .. 
The second registration packet DID NOT issue.

Here's the pcap.
[s1.zip](https://github.com/herlesupreeth/docker_open5gs/files/12414245/ng.zip)

**Comment by ljysdfz** [comment]
@herlesupreeth 

Dear Herle,

I resort to my iPhone 6p and finally the registration seemed to work.

The FHoSS told me the registration was completed appropriately.
![FHoSS](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/67e31284-b67f-4d87-868d-7270b5bd8491)

And the CSCF told me P-CSCF returned a 200, but why is it an ERROR ??
![CSCF](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/9b5efdfe-7879-4679-a232-8b88bcb6bbb6)

Here is the pcap. 
[pcap.zip](https://github.com/herlesupreeth/docker_open5gs/files/12414644/pcap.zip)

But as far as ng.pcap was concerned, you cannot find a 200 response.
And the only existent 401 unauthorized packet showed that the SQN is 545!! WTF is this??
![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/cae1805d-96e8-4234-b0a1-6bb792c1d7a9)

At the same time, you can see following ESP packets that indicate the IPsec tunnel had been established.
I'm totally perplexed.

**Comment by ljysdfz** [comment]
I have tested other 2 phones -- VIVO & Redmi.
They both cannot launch ims registration process.

**Comment by herlesupreeth** [comment]
> And the CSCF told me P-CSCF returned a 200, but why is it an ERROR ??

Please ignore that, its a wrong logging level in IMS

**Comment by herlesupreeth** [comment]
> But as far as ng.pcap was concerned, you cannot find a SECOND 401 response or further 200 response.
> And the only existent 401 unauthorized packet showed that the SQN is 545!! WTF is this??

There is second REGISTER in ims.pcap file, packet no. 1364. You need to enable decoding of null encryption ESP packets in wireshark protocol settings.

https://user-images.githubusercontent.com/3489980/262536404-cae1805d-96e8-4234-b0a1-6bb792c1d7a9.png
In the picture you posted. That is not SQN that you provide in HSS WebUI. Its a sequence number maintained for a SIP transcation

**Comment by ljysdfz** [comment]
> There is second REGISTER in ims.pcap file, packet no. 1364. You need to enable decoding of null encryption ESP packets in wireshark protocol settings.

Aha ~ It's so kind of you, dear Herle.
New skill leant ~

**Comment by Sivanesh1992** [comment]
hi @ljysdfz  which model redmi and oppo mobile your use to test volte

**Comment by Sivanesh1992** [comment]
@ljysdfz  i am trying to attach redmi mobile without root . I am not able to see network while doing network search manually. which usrp your using and please share me config file i will try with your config file

**Comment by ljysdfz** [comment]
@Sivanesh1992 

> i am trying to attach redmi mobile without root . I am not able to see network while doing network search manually. which usrp your using and please share me config file i will try with your config file

Hi, Sivanesh.
Sorry for deferral.
I've been busy with too many affairs.
FYI, I'm using USRP X310.
This is the configuration folder [srsran.zip](https://github.com/herlesupreeth/docker_open5gs/files/12640353/srsran.zip) that comes from the path `~/.config/srsran`
I had mainly modified the files `enb.conf` and `rr.conf`
I think the most important parameter is the `dl_earfcn` defined in `rr.conf`
you can try my configuration `dl_earfcn = 1650` which set the central frequency at band 3.

**Comment by ljysdfz** [comment]
@herlesupreeth 
Dear Herle,
I've made it by establishing both ims bearer and internet bearer.
But I have gotten 2 troubles.
1. It seems that only iPhones support PLMN=00101, Androids looked like having forbidden that testing PLMN. When the EPC tried to send a `PDN connectivity request`, the phone will reject and release context. Reference this pcap [ng-1+fail.zip](https://github.com/herlesupreeth/docker_open5gs/files/12640372/ng-1%2Bfail.zip). But you have tested several Android phones, I know. Could you please check what's the root cause that failed my Android phones?
2.  My data connections between 2 iPhones seemed so slow, they cannot even open a web portal quickly. And the phone call are slow too. I have to wait a few more seconds to see the calling prompt. Sometimes it didn't appear at all !! It's not stable actually. And on the process of communication, I can hardly hear the voice coming from the peer. Could you please instruct me how to improve and streamline the data bearer and the voice bearer ?

Thank you in advance.

**Comment by abouillot-stl** [comment]
I can confirm Android devices live happily on test networks 001/01. 

If the device get rejected, it might be because the APN presented by the device differs from the one expected by the network. I observed this couple of time. Defaults APN for 001/01 differs between devices manufacturers.

**Comment by ljysdfz** [comment]
@abouillot-stl 
Thanks a lot !! Abouillot !!
You're so amazing !!
I'm gonna dive deeper into the APNs.

**Comment by ljysdfz** [comment]
@abouillot-stl 
Dear Abouillot，
I think I need to clarify a little more about it.
The data network "internet" is always capable of being constructed.
The only problem is the voice network "ims".
I used to try to catch the APN for "ims" that is requested by UE.
But literally I cannot get any information sent by UE.
Could you please tell me how to get the exact APN for a UE's IMS?

**Comment by herlesupreeth** [comment]
> Could you please instruct me how to improve and streamline the data bearer and the voice bearer ?

First of all, I would never recommend running eNB in a VM. Second, I would recommend assigning atleast 2 or more CPUs for the VM running eNB. You could do the same for the VM running EPC.

The trace you attached I see UE successfully registered with IMS

![Screenshot from 2023-09-16 17-51-47](https://github.com/herlesupreeth/docker_open5gs/assets/4115839/6d534300-e26d-4bea-9817-a68e1bea2703)

The calling is failing because the number you are dialing is not registered with IMS

![image](https://github.com/herlesupreeth/docker_open5gs/assets/4115839/50c92707-18d1-4646-b1aa-c598b358857b)

**Comment by abouillot-stl** [comment]
@ljysdfz
When the device tries to attach, RRC Connection Request, this will initiate a NAS Attach request [packet 29] for the data connection, usualy relying on the selected APN on the device for its caracteristics, such IP type v4, v6 or v4v6.

After some exchanges, the device will send an NAS ESM Information response [37] carring the APN name.

The IMS APN establishment comes after the initial Attach Request through a NAS PDN Connectivity Request. It can be observed in the packet [42] of your pcap
I noticed when the APN name on the device is not known on the network side, no data will happen, but wouldn't prevent IMS or registration.

Regarding APNs, The device will use the APN type default for the data connection. I saw `internet`, `apn` or other names being presented by the devices. Having the APN on the network side is a must.

The APN for IMS is called `ims` (never saw otherwise), and the APN type *must* be `ims`.

**Comment by ljysdfz** [comment]
@herlesupreeth @abouillot-stl 
Thank for you guys' quick replies.
I think I need to explain the core problem deeper.
At first, sorry for uploading foregoing pcap [ng-1+fail.zip](https://github.com/herlesupreeth/docker_open5gs/files/12640372/ng-1%2Bfail.zip).
That pcap had a successful iPhone and a failed OnePlus which gave too much interfering information.
Now we focus on one phone for one time in order to see the differences.

Before proceeding, we assume that the EPC, i.e. the web page has already a complete configuration like this:
![image](https://github.com/herlesupreeth/docker_open5gs/assets/3489980/fee1ae34-6575-4cb7-841d-4d9826b88cf7)

 And I want to just make it a foundation that we have two ways to indicate an APN that a UE wants to connect:
1. It will issue the establishment request by default when it passes AKA.
2. we formulate an APN manually in the UE.

Here is the iphone pcap [iphone.zip](https://github.com/herlesupreeth/docker_open5gs/files/12642178/iphone.zip) which is able to establish a default bearer that has an APN `ims`. This was done without intentionally formulating an APN `ims` by yourself.

Here is the OnePlus pcap [1+.zip](https://github.com/herlesupreeth/docker_open5gs/files/12642179/1%2B.zip) which has a manually created APN `ims` that failed to indicate itself. It finally showed a test APN `VZWINTERNET` which is not selected by me though in the candidate list.

I have other Android phones like Pixel 6. It cannot issue an `ims` bearer request too. And if you formulate an APN `ims` for it, it finally stumbles  on some hiccups. That is to say, for my personal experiences, only the automatic generated `ims` bearer can finally make it through to subscribe. Any handmade `ims` APN will fail at last.

Could you guys give me some suggestions or opinions.
If I have any understanding that is not mature, please feel free to point it out.
Thank you in advance.

**Comment by abouillot-stl** [comment]
In your 1+.pcap trace [38], the device request `VZWINTERNET` APN, as shown in your screenshot. It look like this out of the box config will request `VZWIMS` for the ims services.

I can suggest, as step one measure, to create or rename the APN on the core side to `VZWINTERNET` and `VZWIMS` and see if you move forward.

I don't know what is in your `ims` APN, but this shouldn't be the selected one. The selected APN designate the APN for internet like service. The type of this APN should be at least default.

If you have an `internet` APN properly configured, such as bellow, if you select that one, it should be ok.

Here are internet and ims:
![Screenshot_20230917-123309](https://github.com/herlesupreeth/docker_open5gs/assets/90634041/81f035ab-22c9-40f5-b416-daeca95d6510)

![Screenshot_20230917-123359](https://github.com/herlesupreeth/docker_open5gs/assets/90634041/ef00c2df-22cb-4be8-a185-bf3abf5ba604)

Point of attention:
Protocol: set to the needed value. IPv4v6 allows to connect whatever network settings. If you want to force on type, select it, but ensure this is also activated on the core side. IPv4 on one side and IPv6 on the other one will not work. All other combination will work v4v6/v6 v4v6/v4 v4/v4v6 or v6/v4v6.
Type:
The phone will use this to select the APN to be used. In your case, default for all traffic, but the one for which a different APN exist and ims for ims service are the ones.
APN:
This name need to be present in the core configuration.
You can have several APN for the same purpose on the core side, i.e. if one devie use `internet` and another one `test`, you can have two APN defined on core side - or maybe two names for the same, can remeber how Open5GS web GUI works on this.

Hope you can make one step forward with these info.

**Comment by ljysdfz** [comment]
@abouillot-stl  
Your kind help is so much appreciated !!
I've tried to make a single `ims` APN with these configuration:
APN=ims, APN protocol=IPv4, APN enable=true, Bearer=LTE, MVNO type=IMSI, others being left as they are.
So the only `ims` APN is just the selected one.
Then you know what? 
The other candidates in the APN list disappeared.
I thought that's exactly what I wanted.
And the ims bearer successfully established.

Then I tried to add a new `internet` APN with these configuration:
APN=internet, APN protocol=IPv4, APN enable=true, Bearer=LTE, MVNO type=IMSI, others being left as they are.
And took the `internet` APN as the selected one.
And the both APNs made it !!

I can use a net tool to ping both gateways (192.168.100.1 & 192.168.101.1) too !!

But here I had another problem.
Please check the hiccups of my Pixel 6.
It just cannot pass the subscription in IMS.
Here's the pcap [pixel6-fail.zip](https://github.com/herlesupreeth/docker_open5gs/files/12642717/pixel6-fail.zip)

**Comment by abouillot-stl** [comment]
From what I see in the pcap, the `ims` APN is properly setup. Then the device tries to register to IMS core on port 5060 [42] and get kicked out as expected [46]. It is then expected to connect over port 6100. This time, it should work, but don't.

I noticed the IMSI used for the iPhone trace is different. Is `01011234567101`correctly setup on IMS core?

Could you try with the SIM you used in iPhone (001011234567100) ?

**Comment by ljysdfz** [comment]
@abouillot-stl Thank you!! I've tried the measure but failed. I just dispensed with Pixel 6 as a EPS UE.

**Comment by ljysdfz** [comment]
@herlesupreeth 
Dear Herle,
Got another question.
How to let the UPF be the one who assign IPs for UEs.
To be clear, I want to remove the IP pool settings in SMF configuration.
Is that possible?

**Comment by abouillot-stl** [comment]
> @abouillot-stl Thank you!! I've tried the measure but failed. I just dispensed with Pixel 6 as a EPS UE.

Maybe share your trace to see what happens

**Comment by herlesupreeth** [comment]
> How to let the UPF be the one who assign IPs for UEs.
> To be clear, I want to remove the DNN and IP pool settings in the SMF configuration.

Its not the task of the UPF to assign IPs to UE. Its the SMF's task so you cant remove DNN or IP pool settings in either SMF or UPF.

**Comment by lynxis** [comment]
I came across the same bug. Just for future reference:
The problem is the pixel6/7a is not correct encoding the "qop" field in the SIP Register (WWW-Authenticate field) following the Unauthorized.

The pixel will encode it as qop=auth,auth-int while the correct one would be qop="auth,auth-int".
By setting kamailio https://github.com/herlesupreeth/docker_open5gs/blob/d531b571030c657b9029bf4f4ae5aa8931152418/scscf/kamailio_scscf.cfg#L294C1-L295C1 it allows the pixel to connect.

**Comment by ljysdfz** [comment]
> I came across the same bug. Just for future reference: The problem is the pixel6/7a is not correct encoding the "qop" field in the SIP Register (WWW-Authenticate field) following the Unauthorized.
> 
> The pixel will encode it as qop=auth,auth-int while the correct one would be qop="auth,auth-int". By setting kamailio https://github.com/herlesupreeth/docker_open5gs/blob/d531b571030c657b9029bf4f4ae5aa8931152418/scscf/kamailio_scscf.cfg#L294C1-L295C1 it allows the pixel to connect.

Noted !!
Great work !! @lynxis 
I will take a try then.
