### ISSUE TITLE
PCO option is not included in srsUE

### ISSUE THREAD

**Issue by ganeshg87** [herlesupreeth/docker_open5gs#219]
Hi @herlesupreeth ,

 I am trying to VoLTE call, Deployment is successful. srsUE attach procedure is successful.
srsUE is not included in PCO to fetch the PCSCF address for VoLTE call.

 
![Screenshot from 2023-08-29 11-38-42](https://github.com/herlesupreeth/docker_open5gs/assets/83060027/14a9cfea-4df7-47a2-a6af-0cc09083aef9)

**Comment by herlesupreeth** [comment]
I dont think its possible to test VoLTE call with srsUE. However, you can test VOIP calling, which does not require UE to send request for P-SCSF address as you would need to enter that address manually in SIP client using srsUE.

**Comment by ganeshg87** [comment]
thank @herlesupreeth.
I am attempting to perform testing using the simulator UE (srsUE for 4G attachment + sipp for IMS call) prior to using real mobile devices.
I will extract the P-CSCF information from the .env file and attempt to initiate an IMS call after a successful srsUE attachment.

----------
please have a look below if we need to correct the steps.

I cannot access pyHSS via the URL http://172.22.0.18:8080/docs/. However, I am able to access it using the URL (http://<DOCKER_HOST_IP>:8080/docs/).
![Screenshot from 2023-08-30 08-58-08](https://github.com/herlesupreeth/docker_open5gs/assets/83060027/2ca0268a-1d75-4147-81c9-ea0eff1d097b)

Thank you
Ganesh

**Comment by herlesupreeth** [comment]
Thats strange, I am able to access it. If you are accessing from another machine then you wont be able to access but if you are accessing from the same machine you would be able to. But you are right, I will fix the docs.

![image](https://github.com/herlesupreeth/docker_open5gs/assets/4115839/84176416-260a-4ce1-b584-102b8c3d9385)
