### ISSUE TITLE
4G attach successful and data path failed

### ISSUE THREAD

**Issue by ganeshg87** [herlesupreeth/docker_open5gs#222]
Hi @herlesupreeth, 

I have successfully deployed a 4G core along with IMS components. The srsUE has also successfully attached to the 4G Core network. However, I'm facing an issue where the srsUE is unable to send data, and I cannot establish a ping connection to either [www.google.com](http://www.google.com/) or the IP address 8.8.8.8.

![Screenshot from 2023-08-31 16-53-45](https://github.com/herlesupreeth/docker_open5gs/assets/83060027/64a55792-300d-4422-bc3d-48da01fd9801)
![Screenshot from 2023-08-31 16-54-12](https://github.com/herlesupreeth/docker_open5gs/assets/83060027/7b1c7202-0569-47d0-8c31-4da91aeba3f7)

I am missing anything, please help to address the issue.

Thank you
Ganesh

**Comment by herlesupreeth** [comment]
Can you please send me the pcap of the issue you are facing? Its hard to know what's the cause of issue from screenshots

**Comment by ganeshg87** [comment]
ignore this issue, it was an issue from my side.
apologies.

thanks a lot for your support 

it was a minor issue. ping command failed while passing the address to the ping command

Thank you
Ganesh
