### ISSUE TITLE
Unable to ping UE to UPF and UPF to External IP via Network Tunnel

### ISSUE THREAD

**Issue by GarethRader** [herlesupreeth/docker_open5gs#223]
Hello,

 

I am not able to successfully ping from the SRS UE ZMQ to the UPF via the network tunnel (tun_srsue) or the UPF to an external IP address (using ogstun interface).

 

I read through the documentation on this repository and was able to set up everything smoothly. Logs show that the AMF detects the gNB and UE registers/configures both, UE container establishes PDU session and SRS RAN gNB connects to the AMF.  As far as I know, the UPF and the rest of the 5G Core from the sa-deploy.yaml seems to be functioning fine otherwise.

 

I am running everything on the same host (Ubuntu 22.04) and hence did not change any other configuration other than the DOCKER_HOST_IP in the .env file. However, both host IP and example IP given in the docs give the same result.

 

My steps to replicate the issue are:

 

- Clone repository
- Build images, disable firewall, enable ip fowarding (as per the readme says)
- Start 5G Core Network, RAN/gNB, UE (ZMQ)

 

```docker-compose -f sa-deploy.yaml up```

 

- Add subscriber via web UI (as per the .env):
```
UE1_IMEI=356938035643803
UE1_IMEISV=4370816125816151
UE1_IMSI=001011234567895
UE1_KI=8baf473f2f8fd09487cccbd7097c6862
UE1_OP=11111111111111111111111111111111
UE1_AMF=8000
```

 

```docker-compose -f srsgnb_zmq.yaml up -d && docker container attach srsgnb_zmq```
```docker-compose -f srsue_5g_zmq.yaml up -d && docker container attach srsue_5g_zmq```

 

- docker exec into UE container and ping UPF via tunnel:
```
ping -I tun_srsue upf
```

 

- docker exec into UPF container and ping external address via interface:
```
ping -I ogstun <IP ADDRESS>
```

 

Is there an issue with the routing between UE, UPF and external addresses? I ran some Tshark captures and didn't find anything obvious. Any help would be greatly appreciated!

[amf.log](https://github.com/herlesupreeth/docker_open5gs/files/12498564/amf.log)
[srsgnb_zmq.log](https://github.com/herlesupreeth/docker_open5gs/files/12498565/srsgnb_zmq.log)
[srsue_5g_zmq.log](https://github.com/herlesupreeth/docker_open5gs/files/12498566/srsue_5g_zmq.log)
[upf.log](https://github.com/herlesupreeth/docker_open5gs/files/12498567/upf.log)

**Comment by herlesupreeth** [comment]
Thanks for nicely describing the issue. I happen to see this issue at my local setup as well. There is nothing wrong with routing rather lates at the gNB was the issue at my end. 

In order to fix this, i set the cpu governor to performance mode and I was able to ping from UE to anywhere and vice versa. Please try below command and then bring up the components and then try pinging.

sudo cpupower frequency-set -g performance

**Comment by GarethRader** [comment]
> In order to fix this, i set the cpu governor to performance mode and I was able to ping from UE to anywhere and vice versa. Please try below command and then bring up the components and then try pinging.
> 
> sudo cpupower frequency-set -g performance

 

Thank you for the quick response! I have been running the command as per the readme and ```lscpu``` and ```sudo cpupower frequency-info``` indicates that they have been set to performance mode. However, the issue unfortunately still persists.... Do you have any other suggestions?

 

Also, would it be possible to know what kernel you are using when this runs successfully? We are running Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-78-generic x86_64) with a Intel(R) Xeon(R) E-2136 CPU.

**Comment by herlesupreeth** [comment]
Sorry for the late reply. Apparently there is a bug I guess in srsRAN_Project gNB and applying this (https://github.com/srsran/srsRAN_4G/issues/1213#issuecomment-1703512937) seems to fix these issues.

> Also, would it be possible to know what kernel you are using when this runs successfully? We are running Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-78-generic x86_64) with an Intel(R) Xeon(R) E-2136 CPU.

I dont think its a kernel issue. I am running 6.2.0-32-generic kernel with Ubuntu 22.04.3 LTS

**Comment by herlesupreeth** [comment]
Can do me a favor and run the srsRAN_Project gNB by setting log level to debug and send me the log file generated in srsran folder inside docker_open5gs ??

https://github.com/herlesupreeth/docker_open5gs/blob/6fabf5d08eb4f2c767a828854923bfe4b7afc3de/srsran/gnb_zmq.yml#L27

**Comment by grader7684** [comment]
Hello, here is the log as per your specifications. It is truncated as the original log is 80 mb with some repeat from the zmq. The repeated section is mostly this:
```
2023-09-15T12:44:05.100702 [FAPI    ] [D] [    21.4] Slot.indication
2023-09-15T12:44:05.100726 [SCHED   ] [W] [    21.4] ue=0 rnti=0x4601 PDSCH allocation skipped. Cause: No available HARQs. Check if any HARQ-ACK went missing or is arriving to the scheduler too late.
2023-09-15T12:44:05.100731 [FAPI    ] [D] [    21.4] DL_TTI.request slot=21.4
2023-09-15T12:44:05.100736 [FAPI    ] [D] [    21.4] UL_TTI.request slot=21.4
2023-09-15T12:44:05.100743 [zmq:tx:0:0] [D] Requested to transmit 5760 samples.
2023-09-15T12:44:05.100756 [zmq:rx:0:0] [D] Requested to receive 5760 samples.
2023-09-15T12:44:05.100794 [zmq:tx:0:0] [D] Socket received request.
2023-09-15T12:44:05.100806 [zmq:tx:0:0] [D] Socket sent 5760 samples.
2023-09-15T12:44:05.100909 [zmq:tx:0:0] [D] Socket received request.
2023-09-15T12:44:05.101297 [zmq:rx:0:0] [D] Socket received 11520 samples.
2023-09-15T12:44:05.101321 [zmq:rx:0:0] [D] Socket sent request.
2023-09-15T12:44:05.101787 [zmq:tx:0:0] [D] Requested to transmit 5760 samples.
2023-09-15T12:44:05.101800 [zmq:rx:0:0] [D] Requested to receive 5760 samples.
2023-09-15T12:44:05.101813 [zmq:tx:0:0] [D] Socket sent 5760 samples.
```
Just for clarification, I was running a ping command through the tun_srsue interface to ping the UPF (`ping -I tun_srsue upf` as well as with the actual IP addresses for both interface and UPF) while this was running. Perhaps a line that might be worth investigating is:

 ```[SCHED   ] [D] [   196.7] DL HARQ rnti=0x4601 cell=0 h_id=0: Setting HARQ to "pending reTx" state. Cause: HARQ-ACK wait timeout (10 slots) was reached but only invalid HARQ-ACKs were received so far.```[](url)
[Uploading warning_gnb.log…]()


Let me know if there is anything else I can do to help! Thank you!

**Comment by grader7684** [comment]
Hello, here is the log as per your specifications. It is truncated as the original log is 80 mb with some repeat from the zmq. The repeated section is mostly this:
```
2023-09-15T12:44:05.100702 [FAPI    ] [D] [    21.4] Slot.indication
2023-09-15T12:44:05.100726 [SCHED   ] [W] [    21.4] ue=0 rnti=0x4601 PDSCH allocation skipped. Cause: No available HARQs. Check if any HARQ-ACK went missing or is arriving to the scheduler too late.
2023-09-15T12:44:05.100731 [FAPI    ] [D] [    21.4] DL_TTI.request slot=21.4
2023-09-15T12:44:05.100736 [FAPI    ] [D] [    21.4] UL_TTI.request slot=21.4
2023-09-15T12:44:05.100743 [zmq:tx:0:0] [D] Requested to transmit 5760 samples.
2023-09-15T12:44:05.100756 [zmq:rx:0:0] [D] Requested to receive 5760 samples.
2023-09-15T12:44:05.100794 [zmq:tx:0:0] [D] Socket received request.
2023-09-15T12:44:05.100806 [zmq:tx:0:0] [D] Socket sent 5760 samples.
2023-09-15T12:44:05.100909 [zmq:tx:0:0] [D] Socket received request.
2023-09-15T12:44:05.101297 [zmq:rx:0:0] [D] Socket received 11520 samples.
2023-09-15T12:44:05.101321 [zmq:rx:0:0] [D] Socket sent request.
2023-09-15T12:44:05.101787 [zmq:tx:0:0] [D] Requested to transmit 5760 samples.
2023-09-15T12:44:05.101800 [zmq:rx:0:0] [D] Requested to receive 5760 samples.
2023-09-15T12:44:05.101813 [zmq:tx:0:0] [D] Socket sent 5760 samples.
```
Just for clarification, I was running a ping command through the tun_srsue interface to ping the UPF (`ping -I tun_srsue upf` as well as with the actual IP addresses for both interface and UPF) while this was running. Perhaps a line that might be worth investigating is:

 ```[SCHED   ] [D] [   196.7] DL HARQ rnti=0x4601 cell=0 h_id=0: Setting HARQ to "pending reTx" state. Cause: HARQ-ACK wait timeout (10 slots) was reached but only invalid HARQ-ACKs were received so far.```[](url)



Let me know if there is anything else I can do to help! Thank you!
[warning_gnb.log](https://github.com/herlesupreeth/docker_open5gs/files/12619779/warning_gnb.log)

**Comment by herlesupreeth** [comment]
> Does this seem related to (https://github.com/srsran/srsRAN_4G/issues/1213#issuecomment-1703512937) ?Let me know if there is anything else I can do to help! Thank you!

Sorry for the late reply. Yes, it is related. Should be fixed in coming release. In the meantime if you want to give a try with that diff. Then, I would suggest the following. Copy the contents of that diff to a file inside srsran folder.Then, modify the Dockerfile in srsran folder as follows:

```
diff --git a/srsran/Dockerfile b/srsran/Dockerfile
index 07f94c6..37ee2a9 100644
--- a/srsran/Dockerfile
+++ b/srsran/Dockerfile
@@ -41,6 +41,7 @@ RUN add-apt-repository ppa:ettusresearch/uhd && \
 # Get srsRAN_Project, compile and install
 RUN git clone https://github.com/srsran/srsRAN_Project.git && \
     cd srsRAN_Project && \
+    git apply fix_diff_filename && \
     mkdir build && cd build && \
     cmake ../ -DENABLE_EXPORT=ON -DENABLE_ZEROMQ=ON && make -j`nproc` && make install && \
     ldconfig
```

then, execute the below command inside srsran folder

`docker build -t docker_srsran .`

**Comment by GarethRader** [comment]
Ok, that works! Thank you for the help! Will close the issue for now. Looks like the UPF out just needed the routing configured manually as per the SRS documentation.
