### ISSUE TITLE
how to configure TAC in docker open5gs?

### ISSUE THREAD

**Issue by fatafalihhilmi** [herlesupreeth/docker_open5gs#224]
Hello

I have successfully installed open5gs docker. Besides that, I have also managed to configure IP and PLMN so that they can connect to my GnB, but the problem is that in .env there is no configuration for TAC

do you know how to configure TAC?
Thank You

regards
Fata

**Comment by herlesupreeth** [comment]
For TAC you would have to alter the configuration files inside `mme` folder (for 4G) and in `amf` folder (for 5G). Then, re-deploy.

.env is meant only for quick setup scenario. For more custom needs you would need to alter the configuration file in respective components folder.
