### ISSUE TITLE
5G SA internet not working

### ISSUE THREAD

**Issue by Sivanesh1992** [herlesupreeth/docker_open5gs#225]
hi @herlesupreeth  i am using docker_open5gs (open5gs_hss_cx branch) to test 5G SA in onplus 8T UE 

I am delpoying in same host both gnb and  open5gs in docker . I replaced my host ip in DOCKER_HOST_IP on .env file

I am able to attach the network but  not able to see 5G symbol also internet is not working.

in UE i set both internet and ims apn .

kindly find the attached log
[5G_internet_issue.zip](https://github.com/herlesupreeth/docker_open5gs/files/12536329/5G_internet_issue.zip)

**Comment by Sivanesh1992** [comment]
hi @herlesupreeth sorry foe delay response .

After disable volte also i am not getting internet and also i am not installed coIMS app 


[5g_internet_fail.zip](https://github.com/herlesupreeth/docker_open5gs/files/12656154/5g_internet_fail.zip)

**Comment by Sivanesh1992** [comment]
hi @herlesupreeth   It seems onle plus 8T having issue. suppose i use one plus nord ce 5G UE , I am able to attach network and pdu session also success.

**Comment by herlesupreeth** [comment]
Ah, I imagined so its an UE issue.

**Comment by Sivanesh1992** [comment]
may be but  last month i am able to attach successfully and browse internet also on same one plus 8T UE

**Comment by MKSBarbosa** [comment]
Hello @Sivanesh1992, did you solve this problem, I am also facing the same problem, I am using the Motorola Edge Plus and Motorola G53 5G. I tried to disable the Vo5G, but the loop continues. 

The gnb that I am using is from the OAI, and the band is n78. The usrp that I am using is b210.

**Comment by herlesupreeth** [comment]
> I tried to disable the Vo5G

From my experience disabling Vo5G causes the phone to disconnect and reconnect. Therefore I would suggest deploying the 5GC + IMS using the following docker compose file - https://github.com/herlesupreeth/docker_open5gs/blob/master/sa-vonr-deploy.yaml and enable Vo5G

**Comment by Sivanesh1992** [comment]
.
