### ISSUE TITLE
Unable to Start OAI gNB

### ISSUE THREAD

**Issue by warlock1302** [herlesupreeth/docker_open5gs#229]
[oai_log.txt](https://github.com/herlesupreeth/docker_open5gs/files/12577914/oai_log.txt)

Hi,
we are trying to start OAI gnB and getting the below error. Any help is appreciated. I have attached the log file in this issue.

```
oaignb    | [HW]   No USRP Device Found.
oaignb    |  
oaignb    | Assertion (0) failed!
oaignb    | In openair0_device_load() /openairinterface5g/radio/COMMON/common_lib.c:154
oaignb    | can't open the radio device: none
oaignb    | 
oaignb    | Exiting execution
oaignb    | /openairinterface5g/radio/COMMON/common_lib.c:154 openair0_device_load() Exiting OAI softmodem: _Assert_Exit_
oaignb    | [HW]   releasing USRP
oaignb    | Segmentation fault (core dumped)
oaignb exited with code 139
```

**Comment by herlesupreeth** [comment]
Well, I never managed to get OAI gNB working so maybe I cant be of much help here. But, from the logs above it looks like there is no USRP device attached to the system where you are running OAI gNB.

> [HW]   No USRP Device Found.

**Comment by warlock1302** [comment]
We tried to run the docker-based OAI gNB using the https://github.com/herlesupreeth/docker_open5gs/blob/master/oai/gnb_dockerfile that is available in the repository.

1. When you said "I never managed to get OAI gNB working", did you mean the docker-based OAI gNB or the standalone gNB?
2. Do you know if the docker-based Open5GS can work with standalone OAI gNB?

**Comment by warlock1302** [comment]
Thanks a lot for your insights @herlesupreeth
We are able to connect Docker open5gs with OAI
