### ISSUE TITLE
UE failed to connect to the eNB

### ISSUE THREAD

**Issue by akseslab** [herlesupreeth/docker_open5gs#23]
Hi Herlee,

The UE was able to detect the eNB and it shown Test PLMN 1-1 4G, but when UE attempt to connect to the eNB it fails to register.
Previously i've already register the UE identity via web browser, and i have try the same settings in non-docker environment and works properly for data connections (without voLTE settings).

The eNB also shown the connection attempt from the UE:
Built in Release mode using commit d045213fb on branch HEAD.

---  Software Radio Systems LTE eNodeB  ---

Reading configuration file /etc/srslte/enb.conf...
Opening 1 RF devices with 1 RF channels...
[INFO] [UHD] linux; GNU C++ version 7.5.0; Boost_106501; UHD_3.15.0.0-release
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP with args: type=b200,master_clock_rate=23.04e6
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
Setting frequency: DL=2685.0 Mhz, UL=2565.0 MHz
Setting Sampling frequency 11.52 MHz

==== eNodeB started ===
Type <t> to view trace
RACH:  tti=2541, preamble=48, offset=1, temp_crnti=0x46
Disconnecting rnti=0x46.
RACH:  tti=7091, preamble=7, offset=1, temp_crnti=0x47
Disconnecting rnti=0x47.
RACH:  tti=7371, preamble=19, offset=0, temp_crnti=0x48
Disconnecting rnti=0x48.
RACH:  tti=1651, preamble=11, offset=1, temp_crnti=0x49
Disconnecting rnti=0x49.
RACH:  tti=6201, preamble=17, offset=1, temp_crnti=0x4a
Disconnecting rnti=0x4a.
RACH:  tti=511, preamble=6, offset=1, temp_crnti=0x4b
Disconnecting rnti=0x4b.
RACH:  tti=5061, preamble=33, offset=1, temp_crnti=0x4c
Disconnecting rnti=0x4c.

I run the docker with the following commands (as written in github):
1. on the first terminal: docker-compose up
2. 2nd terminal: docker-compose -f srsenb.yaml up -d && docker attach srsenb

Is there any steps that i've missed?

Thanks

**Comment by herlesupreeth** [comment]
Please attach a packet capture when you raise a issue so that I can help

**Comment by akseslab** [comment]
Hi Herle,

This is the packet capture:
https://gofile.io/d/HCXiSz

Sorry, i'm not familiar with wireshark packet capturing in docker environment. What interface should i choose when capturing packet from docker-open5gs (there is a lot of virtual interfaces shown in the list)? i'm using "any" options, but i think there should be a specific interface that only captures traffic from docker-open5gs.

Thanks

**Comment by herlesupreeth** [comment]
Packet capture on "any" interface is just fine for me.

Regarding failure to attach of UE, its because you have configured wrong APN on the phone (see picture below). Phone is configured for "srsapn" but the open5gs HSS is configured for "internet" and "ims" APNs

![image](https://user-images.githubusercontent.com/4115839/106611190-f3211300-6567-11eb-8267-0740e8c40c6e.png)

**Comment by akseslab** [comment]
Thanks, it works perfectly
