### ISSUE TITLE
There is no FHOSS anymore?

### ISSUE THREAD

**Issue by mvbs3** [herlesupreeth/docker_open5gs#233]
In other commits of this repository the ims part had an UI to create subscribers at kamallios. Now it has an "PYHSS" container.
This container dont have an User interface?

**Comment by herlesupreeth** [comment]
FHoSS has been completely removed from this repository and replaced with pyHSS. I know its a bit inconvenient to not have a GUI like FHoSS had but pyHSS is more versatile, lightweight, future proofing and does not depend on old java versions.

You can find instruction to provision an IMS user in pyHSS in the README - https://github.com/herlesupreeth/docker_open5gs#provisioning-of-sim-information-in-pyhss-is-as-follows
