### ISSUE TITLE
Authentication failure(MAC failure) open5gs_docker -> OAIGnB -> Quectel RM520N-GL

### ISSUE THREAD

**Issue by warlock1302** [herlesupreeth/docker_open5gs#234]
Hi All,

we are trying to connect open5gs with OaI gnb and Quectel RM520N-GL as UE.
The OaI gnB connect to open5gs but UE authentication is failing. 
USIM and open5gs subscriber Opc, KI DNN/APN match exactly.
Appreciate any pointers on this issue.

![amf_gnb](https://github.com/herlesupreeth/docker_open5gs/assets/97191418/ab3481cb-eecd-4a99-a860-09e0fd5e34e3)
![amf](https://github.com/herlesupreeth/docker_open5gs/assets/97191418/df82922d-ce87-4dfd-8b1c-19c71f4619f6)
<img width="675" alt="webui" src="https://github.com/herlesupreeth/docker_open5gs/assets/97191418/e29c425c-c45b-4446-8977-9cb337568528">
![USIM](https://github.com/herlesupreeth/docker_open5gs/assets/97191418/0f49a70c-1918-43c6-ada8-0143b9377f8a)
<img width="715" alt="mmcli -m" src="https://github.com/herlesupreeth/docker_open5gs/assets/97191418/c9021699-1f89-420e-bdc9-c8232e508545">
<img width="1388" alt="OAI log" src="https://github.com/herlesupreeth/docker_open5gs/assets/97191418/7258c310-ceb4-447c-9261-9b88c0cbf1b2">
[test1.pcap.zip](https://github.com/herlesupreeth/docker_open5gs/files/12743767/test1.pcap.zip)

**Comment by herlesupreeth** [comment]
Thats because OPc is derived from Ki and OP value and you cannot have random OPc value for a given Ki.

I would suggest to re-program the SIM card with following Ki and OP (not OPc) value

KI=8baf473f2f8fd09487cccbd7097c6862
OP=11111111111111111111111111111111
