### ISSUE TITLE
How to Add IMS subscription

### ISSUE THREAD

**Issue by akseslab** [herlesupreeth/docker_open5gs#24]
Hi Herle,
I have followed instruction from Open5GS doc website in sub section: Add IMS subscription use in FoHSS as follows from the Web GUI.

And already at these steps:
And, finally add these IMPUs as implicit set of IMSI derived IMPU in HSS i.e sip:001011234567891@ims.mnc001.mcc001.3gppnetwork.org as follows:

1. Goto to IMPU sip:001011234567891@ims.mnc001.mcc001.3gppnetwork.org
2. In "Add IMPU(s) to Implicit-Set" section give IMPU Identity created above to be added to this IMPU

What is the meaning of this instruction: In "Add IMPU(s) to Implicit-Set" section give IMPU Identity created above to be added to this IMPU...???

Here is the screenshot at hss web console:

![Selection_001](https://user-images.githubusercontent.com/19641669/106700636-d217fb00-6617-11eb-945f-1a6ef88242de.png)

Please inform the next step. Thanks

**Comment by herlesupreeth** [comment]
> What is the meaning of this instruction: In "Add IMPU(s) to Implicit-Set" section give IMPU Identity created above to be added to this IMPU...???

The IMPUs you created tel:xxx and sip:xxx for this particular IMPI, you need provide then in section "Add IMPU(s) to Implicit-Set" above "List IMPUs from Implicit-Set" section as seen in above picture and press "Add" one by one.

**Comment by akseslab** [comment]
Thanks for your explanation.

Could you please check the following settings? Is this correct:
![Selection_002](https://user-images.githubusercontent.com/19641669/106712388-748da980-662b-11eb-9fd2-6a497f61d82a.png)

Thanks again

**Comment by herlesupreeth** [comment]
Looks good. Send me a screenshot of list of IMPUs as well

**Comment by akseslab** [comment]
How to display the list of IMPUs?
Yes, i believe i can use any valid telephone number, i will try for the next subscriber

**Comment by herlesupreeth** [comment]
Go to User Identities --> Public User Identity --> Search --> Press on Search button

**Comment by akseslab** [comment]
![Selection_003](https://user-images.githubusercontent.com/19641669/106718643-ea960e80-6633-11eb-96a5-b5786b8af12b.png)

Is this ok?

**Comment by herlesupreeth** [comment]
All good

**Comment by akseslab** [comment]
thanks
