### ISSUE TITLE
5G-SA-E2E zmq simulation error: Registration Reject (PLMN not allowed)

### ISSUE THREAD

**Issue by r00tb33** [herlesupreeth/docker_open5gs#245]
Hi all,

I am trying to play around with the 5G-SA E2E deployment using zmq driver, everything runs fine but the moment UE initiates "Registration request"  it receives a response of "Registration Reject (PLMN not allowed)".

What could be the reason for reject? 

Do I need to register the UE details in the mongo DB to enable its connectivity?

Herewith attaching the [PCAP](https://file.io/KbfxHlVcLSFa) file!!

Thanks!!

**Comment by herlesupreeth** [comment]
> Do I need to register the UE details in the mongo DB to enable its connectivity?

yes

**Comment by r00tb3** [comment]
> > Do I need to register the UE details in the mongo DB to enable its connectivity?
> 
> yes

Do I need to use the details of URENASIM for srsUE as well when simulating whole thing sing zmq driver?

I don't see any UE details for srsUE_5g_zmq in the repo... if it's there pls point out.

Thanks for the response!!

**Comment by herlesupreeth** [comment]
Here are the UE SIM details to be entered in open5gs Web UI/ mongo DB

https://github.com/herlesupreeth/docker_open5gs/blob/c401f8121a3fe64b819068d91dffe34dcfdd966a/.env#L83C1-L89C13

**Comment by r00tb33** [comment]
> Here are the UE SIM details to be entered in open5gs Web UI/ mongo DB
> 
> https://github.com/herlesupreeth/docker_open5gs/blob/c401f8121a3fe64b819068d91dffe34dcfdd966a/.env#L83C1-L89C13

Thanks!!
