### ISSUE TITLE
Rx interation messages missing in VoLTE call

### ISSUE THREAD

**Issue by ganeshg87** [herlesupreeth/docker_open5gs#253]
Hi @herlesupreeth ,

 I tried VoLTE call with Real Devices with 4G Deployment, audio /video call successful but I dont see Rx messages between PCSCF and PCRF. 
Observed below error logs in PCSCF:

> ^[[0;39;49m^[[0;36;49m94(132) INFO: cdp [receiver.c:807]: receive_loop(): select_recv(): [pcrf.epc.mnc001.mcc001.3gppnetwork.org] read on socket [33] returned 0 > ... dropping
> ^[[0;39;49m^[[0;36;49m94(132) INFO: cdp [receiver.c:222]: disconnect_serviced_peer(): drop_serviced_peer(): [pcrf.epc.mnc001.mcc001.3gppnetwork.org] Disconnecting from peer

am I missing any configuration to trigger Rx messages from PCSCF..?

Thank you
Ganesh

**Comment by ganeshg87** [comment]
please find attached PCSCF pcap traces
[pcscf.zip](https://github.com/herlesupreeth/docker_open5gs/files/13296633/pcscf.zip)

**Comment by herlesupreeth** [comment]
Thanks for the logs. I dont see any diameter message exchanged in the pcap attached. Please do the following and send me the trace

1. Bring down all the components
2. Start wireshark/tcpdump
3. Deploy EPC + IMS components
4. Start eNB
5. Attach UE
6. Attempt a call
7. Stop the trace and attach here

**Comment by ganeshg87** [comment]
@herlesupreeth , thank you for your response.
I have executed attach procedure
 and tested the VoLTE call. please have a look
[call.zip](https://github.com/herlesupreeth/docker_open5gs/files/13307550/call.zip)

**Comment by ganeshg87** [comment]
I see below in pcscf.cfg file related to RX interface, this means Is Rx enabled/disabled?
#!define WITH_RX
#!define WITH_RX_REG
#!define WITH_RX_CALL

**Comment by herlesupreeth** [comment]
In the attached pcap I still dont see any communication between P-CSCF and PCRF, are you sure P-CSCF is running? Please send the logs

> I see below in pcscf.cfg file related to RX interface, this means Is Rx enabled/disabled?
> #!define WITH_RX
> #!define WITH_RX_REG
> #!define WITH_RX_CALL

This means its enabled

**Comment by herlesupreeth** [comment]
In your pcap I see the communication between PCSCF and PCRF (notice that its Diameter over TCP)

![image](https://github.com/herlesupreeth/docker_open5gs/assets/4115839/b63355d0-2a29-4f33-a5ec-e7d7871008c2)

**Comment by ganeshg87** [comment]
Thank you verymuch @herlesupreeth.
got it now.it was great support
