### ISSUE TITLE
PCSCF returns "504 Server Time-Out" when using SIPp UE during registration

### ISSUE THREAD

**Issue by juanantono** [herlesupreeth/docker_open5gs#255]
Hello Herlesupreet, good day

I am trying to register in IMS after establishing the PDU session towards PCSCF. However, once PCSCF sends AAR to PCRF and AAA is received, after 3 seconds PCSCF replies "504 Server Time-Out" to UE. This is the packet capture:

![image](https://github.com/herlesupreeth/docker_open5gs/assets/96539633/d32e4a00-a0d8-4e89-a700-ebfb637a33f1)

[20231114f.zip](https://github.com/herlesupreeth/docker_open5gs/files/13354306/20231114f.zip)

PCSCF logs are here:

 _4(44) NOTICE: <script>: PCSCF: REGISTER sip:172.22.0.21 (sip:001011234567895@192.168.101.4 (172.22.0.21:5060) to sip:001011234567895@192.168.101.4, 1-92@192.168.101.4)
 4(44) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
 4(44) NOTICE: <script>: PCSCF REGISTER:
 Destination URI: <null>
 Request URI: sip:172.22.0.21
 4(44) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
 4(44) NOTICE: <script>: Source IP and Port: (172.22.0.21:5060)
 Route-URI:
 4(44) NOTICE: <script>: Received IP and Port: (172.22.0.21:5060)
 4(44) NOTICE: <script>: Contact header: <sip:001011234567895@192.168.101.4:5060;alias=192.168.101.4~5060~1>
 4(44) INFO: ims_registrar_pcscf [sec_agree.c:264]: cscf_get_security(): No security parameters found
 4(44) INFO: ims_registrar_pcscf [sec_agree.c:296]: cscf_get_security_verify(): No security-verify parameters found
 4(44) ERROR: ims_qos [ims_qos_mod.c:1305]: w_rx_aar_register(): This contact does not exist in PCSCF usrloc - error in cfg file
 4(44) ERROR: ims_qos [ims_qos_mod.c:1458]: w_rx_aar_register(): Error trying to send AAR
 4(44) WARNING: tm [t_lookup.c:1504]: t_unref(): script writer didn't release transaction
 2(42) NOTICE: <script>: PCSCF: BYE sip:001011234567895@192.168.101.4 (sip:001011234567895@192.168.101.4 (192.168.101.4:5060) to sip:001011234567895@192.168.101.4, 1-92@192.168.101.4)
 2(42) NOTICE: <script>: Within DLG_

I have tried to understand this error but I cannot find any information related to "This contact does not exist in PCSCF usrloc"

Thanks in advance!

**Comment by herlesupreeth** [comment]
I believe SIP REGISTER is sent with wrong SIP Request URI. Rather than sip:172.22.0.21 it should be sip:ims.mnc001.mcc001.3gppnetwork.org

**Comment by juanantono** [comment]
Hello Herlesupreet,

thanks! after changing it from IP to domain and adjusting From/To from IP to domain as well, REGISTER has reached up to S-CSCF and 401 is sent back to UE
I am using SIPp and I need to work on the xml files to be able to process the 401 and re submit the REGISTER with authentication data, but that's a different story. Thanks for all your support!
