### ISSUE TITLE
pyhss docker process not working

### ISSUE THREAD

**Issue by shanmukhapothana** [herlesupreeth/docker_open5gs#256]
Hi Team,
I am facing the below issue while deploying SA VONR DEPLOY setup.
using latest commit:
commit a744a91b0903437a9e79eb547e34f3960e122c7b (HEAD -> open5gs_hss_cx, origin/open5gs_hss_cx)

![Screenshot from 2023-11-17 11-55-33](https://github.com/herlesupreeth/docker_open5gs/assets/132892962/481d6861-6b8b-4d3d-bfde-f7b9fac75a2e)

It would be great to help to fix the above issue.

Thank you
Shanmukha.P

**Comment by herlesupreeth** [comment]
Oops, its a mistake on my end. I will fix it. Thanks for bringing it to my notice

**Comment by herlesupreeth** [comment]
Please fetch the latest commits from that branch and give it a try.

**Comment by shanmukhapothana** [comment]
Its working fine now...Thank you
