### ISSUE TITLE
Error : Forbidden-HSS user unknown

### ISSUE THREAD

**Issue by shanmukhapothana** [herlesupreeth/docker_open5gs#258]
Hi Team,
I am facing the below issue while running SA VONR setup.
using latest commit:
commit bf1132f12980440174f46f6213c6ebcc4438dd2d (HEAD -> master, origin/master, origin/HEAD)

**HSS user unknown** issues was facing during running the SA VONR and please find the below logs.

[vonr log.zip](https://github.com/herlesupreeth/docker_open5gs/files/13438273/vonr.log.zip)
[vonr log 1.zip](https://github.com/herlesupreeth/docker_open5gs/files/13438277/vonr.log.1.zip)

It would be great to help to fix the above issue.

Thank you
Shanmukha.P

**Comment by herlesupreeth** [comment]
Looks like you have not configured the SIM details in pyHSS ? Please refer to the steps here - https://github.com/herlesupreeth/docker_open5gs?tab=readme-ov-file#provisioning-of-sim-information-in-pyhss-is-as-follows

**Comment by shanmukhapothana** [comment]
Thank you
