### ISSUE TITLE
getting error while deploying 5G SA deployment

### ISSUE THREAD

**Issue by Deblina96** [herlesupreeth/docker_open5gs#261]
Hello @herlesupreeth sir,
I am trying to deploy sa-deploy.yaml but getting the following error. I am using ubuntu 20.04 version.

# 5G Core Network
docker compose -f sa-deploy.yaml up.
![image](https://github.com/herlesupreeth/docker_open5gs/assets/116576465/c4d9c513-429d-426f-93fc-04619692f5ff)

Kindly, suggest what could be done for it.

**Comment by Deblina96** [comment]
Can anybody please help me to fix the above error.

**Comment by herlesupreeth** [comment]
Can you please post the docker and docker compose version you are using? my suspicion is that you are using an old docker compose

**Comment by Deblina96** [comment]
Hello @herlesupreeth, please find the version below:
![image](https://github.com/herlesupreeth/docker_open5gs/assets/116576465/b8e1b31f-ec03-4721-9907-8eea206ba996)

**Comment by Deblina96** [comment]
Hello @herlesupreeth Sir, 
Could you please provide me the correct version to deploy the file.

**Comment by herlesupreeth** [comment]
I see that you are using latest version so i dont think thats a problem.

Did you modify the deployment file by any chance??

can you send me the output of `git diff` command from docker-open5gs folder

**Comment by Deblina96** [comment]
Dear @herlesupreeth Sir,

Please find the details
[open5gserror.docx](https://github.com/herlesupreeth/docker_open5gs/files/13528056/open5gserror.docx)
.

Also I haven't changed anything in the deployment file.

**Comment by herlesupreeth** [comment]
Any reason why you have changed the test network subnet ? If you have changed the test network subnet, have you ensure you have changed the IP address of all other elements in .env file?

If so, can you paste here the git diff entire output (no need to send as screenshot in docx you can copy paste from terminal output). Also, note that you need to press down arrow key in git diff to see the entire git diff

**Comment by Deblina96** [comment]
Dear @herlesupreeth Sir,

I am doing a project on integration of  OAI NFs with open5gs NFs. I am trying implement a scenario where I am taking NRF from OAI and other NFs from open5gs. In order do that, I changed the IP address accordingly.

I have general question is it even possible to integrate OAI NFs with open5gs NFs ?
Also, in open5gs all the NF are using SCP URI instead of NRF ? why is that ?

**Comment by herlesupreeth** [comment]
> I have general question is it even possible to integrate OAI NFs with open5gs NFs ?

It should be possible if the OAI NF is standard compliant

> Also, in open5gs all the NF are using SCP URI instead of NRF ? why is that ?

SCP is used a proxy by NFs to communicate with NRF. However, it is possible to communicate directly with NRF rather than via SCP in open5gs. Just remove the SCP sections in the NF's configuration file.

**Comment by Deblina96** [comment]
Thank you so much @herlesupreeth sir, I with try with only NRF and see how it comes.

**Comment by Deblina96** [comment]
Hello @herlesupreeth Sir,
I have tried without scp and it worked. But, I have two questions:
1. Though in log its showing that NF registered but in wireshark capture through http2 request its not showing. 
2. Now, when I am trying to connect UE and gNB using UERANSIM it is giving the below error:-

![image](https://github.com/herlesupreeth/docker_open5gs/assets/116576465/e6aa07f9-c6ec-4525-a853-c04a443b0cc2)

**Comment by herlesupreeth** [comment]
For viewing HTTP2 traffic in wireshark you would need to do the steps mentioned here - https://github.com/open5gs/open5gs/discussions/751

> Now, when I am trying to connect UE and gNB using UERANSIM it is giving the below error:-

You would need to attach the pcap taken on the machine you are running docker_open5gs at the time of UE registration
