### ISSUE TITLE
Testing VoLTE Setup with ZMQ deployment

### ISSUE THREAD

**Issue by GinesGarcia** [herlesupreeth/docker_open5gs#265]
Hi,
I have correctly deployed the voLTE scenario using srsRAN with zmq. However, there are no instructions
about how to properly test that everything is correctly working.

I got srsUE connected and there is connectivity between the UE and the eNB.

Are there any instructions to test the VoLTE deployment?

Thanks in advance!
Regards,
Ginés.

**Comment by herlesupreeth** [comment]
With ZMQ you can test only data and not calling. You can test voice call but it would be more of a VoIP call rather than VoLTE call. For VoLTE call there should be a tight integration between radio stack and IMS stack on the UE side.

**Comment by GinesGarcia** [comment]
Hi,
thanks a lot for your reply.

Even though the VoLTE functionality is not available, I should be able to see the UE registration within
the IMS service right? if so, how can I check it?

Regards,
Ginés.

**Comment by herlesupreeth** [comment]
> Even though the VoLTE functionality is not available, I should be able to see the UE registration within
> the IMS service right?

No, there is no SIP client stack included in this repo.

**Comment by GinesGarcia** [comment]
ok thanks
