### ISSUE TITLE
Not getting VoLTE REGISTER in a multi-host setup

### ISSUE THREAD

**Issue by razvancrainea** [herlesupreeth/docker_open5gs#266]
I am using a multi-host setup, using an external eNB, according to the [tutorial](https://github.com/herlesupreeth/docker_open5gs?tab=readme-ov-file#multihost-setup-configuration). I got to the point where I have a registered UE with a working 4G connection in Roaming through the "ims" APN. However, I cannot get the UA to send any REGISTER to the PCSCF, although the VoLTE setting is properly enabled on the device.
It's worth mentioning that I am using the same device (Xiaomi Redmi Note 9T 5G) in a different setup (single host) and it works just fine.
I am attaching a PCAP, with the hope you could guide me to understand what I am missing and how I can fix it.
[no-register.zip](https://github.com/herlesupreeth/docker_open5gs/files/13653929/no-register.zip)

**Comment by herlesupreeth** [comment]
I see only one CCR (Diameter) i the trace attached and that too its for ims APN, this is incorrect. It is as though device is trying to attach to ims APN as though its the default APN for internet access. Please check your APN configuration on the phone, the ims APN should not be selected rather default APN should be selected.

![image](https://github.com/herlesupreeth/docker_open5gs/assets/4115839/cffcff4b-6432-495a-8a01-beeaf1b2ba90)

Also, I would suggest running sudo ufw disable and see if that help. Btw, I dont see any GTP packet in the trace did you apply any filters? If so, next time please take the trace on 'any' (all) interface

**Comment by razvancrainea** [comment]
Many thanks for your quick response. I only had one APN (the ims one), that's why it was selected. I've added a new one (internet) and took another trace. So currently I only have the ims and internet APNs, with the internet being checked. Not sure if it's worth mentioning that their MCC and MNC values are (automatically) set to 999 and 70. I tried setting them to 001 and 01, but this does not seem to work - the settings are either not saved, or the APN disappears after I save.
I don't have any firewall (ufw is not even installed and the iptables table is only populated by the docker forward rules), and the trace was already on the "any" interface. But yes, I also noticed that there are no GTP packets, although I double checked the advertised sgwu and it seems to be correct (it's advertised as the host's IP).
[ims-bad2.zip](https://github.com/herlesupreeth/docker_open5gs/files/13657033/ims-bad2.zip)

Once again, many thanks for your prompt help!

**Comment by herlesupreeth** [comment]
In the above attached pcap I see now that phone does not attach to ims APN which mean VoLTE is not enabled on the phone. If you are using Sysmocom based SIM cards then you can follows the steps mentioned here - https://github.com/herlesupreeth/CoIMS_Wiki to force enable VoLTE on the phone.

**Comment by razvancrainea** [comment]
I am indeed using Sysmocom USIM cards and I can confirm I followed the steps, that's how the VoLTE icon was enabled (beforehand it was not even appearing in the UI). I also installed the CoIMS App and was able to open it, but indeed the "SIM Carrier Id" was -1. "carrier_volte_provisioned_bool" and "App has Carrier Privileges" were both true. But I suspect that's probably why I cannot set the correct MCC and MNC in the phone's APN.

**Comment by herlesupreeth** [comment]
`"SIM Carrier Id" was -1`

This is bad. Maybe there was an issue in programming your SIM card. Because when using 001 01 PLMN the SIM Carrier Id wont be -1.

The following is usually the command i use to program the SIM card
`
./pySim-prog.py -p 0 -x 001 -y 01 -s 8988211900000000025 -i 001010123456790 -k 8baf473f2f8fd09487cccbd7097c6862 --op 11111111111111111111111111111111 -o 8E27B6AF0E692E750F32667A3B14605D -a 11111111 -n exp.zii --msisdn 9076543210 --pcscf pcscf.ims.mnc001.mcc001.3gppnetwork.org --ims-hdomain ims.mnc001.mcc001.3gppnetwork.org --impi 001010123456790@ims.mnc001.mcc001.3gppnetwork.org --impu sip:001010123456790@ims.mnc001.mcc001.3gppnetwork.org`

you can use the above command, just ensure to match ICCID (-s in above command) to your SIM card and also the ADM1 key (-a in above command)

**Comment by razvancrainea** [comment]
Thank you for sharing the command, I was using a simplified version, according to the tutorial! But I will definitely give it another try with the new version in a couple of hours and let you know the outcome.
Once again, your help is really appreciated :)!

**Comment by razvancrainea** [comment]
Hi, @herlesupreeth !

I wanted to start fresh so I cleaned up the PyHSS and started over with a new SIM, programmed according to your instructions. This time the CoIMS app identifies a "SIM Carrier id" equals to 1911. So I'm clearly making progress.
However, I am still not seeing the UE registering to the PCSCF. I've attached a new pcap, hopefully it provides the information I am missing to get this working.

[ims-bad3.zip](https://github.com/herlesupreeth/docker_open5gs/files/13674734/ims-bad3.zip)

Thanks again for your support!

**Comment by herlesupreeth** [comment]
Hmm, phone is still not attaching to IMS APN. Can you make sure whether the VoLTE option is enabled in the phone mobile network settings? (It maybe called "Enhanced 4G or something like that in Xiaomi phones). Also, can you now see IMS APN in the phone's APN settings?

**Comment by razvancrainea** [comment]
I do have the "Use VoLTE" enabled and "Make calls using WI-FI" disabled. But even if I enable the latter one, I get the same behavior. I even tried toggling the setting while fetching the PCAP.
I did not have the "ims" APN configured in Open5GS, could that be a reason why it would not attach? Any way, I've added it, and re-do the PCAP. Not sure what I should look at :(.
[ims-bad4.zip](https://github.com/herlesupreeth/docker_open5gs/files/13682900/ims-bad4.zip)

**Comment by razvancrainea** [comment]
I've taken a new PCAP just when I turn on the "Use VoLTE" switch. I can see the "ims" APN being attached a few times within a couple of seconds, with different IPs being allocated and released:

```
12/18 00:10:28.988: [upf] INFO: [Removed] Number of UPF-sessions is now 0 (../src/upf/context.c:250)
12/18 00:10:29.175: [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:206)
12/18 00:10:29.175: [upf] INFO: UE F-SEID[UP:0x76 CP:0x92f] APN[internet] PDN-Type[1] IPv4[192.168.100.78] IPv6[] (../src/upf/context.c:483)
12/18 00:10:29.175: [upf] INFO: UE F-SEID[UP:0x76 CP:0x92f] APN[internet] PDN-Type[1] IPv4[192.168.100.78] IPv6[] (../src/upf/context.c:483)
12/18 00:10:29.438: [upf] INFO: [Added] Number of UPF-Sessions is now 2 (../src/upf/context.c:206)
12/18 00:10:29.438: [upf] INFO: UE F-SEID[UP:0xb1e CP:0xf0f] APN[ims] PDN-Type[1] IPv4[192.168.101.70] IPv6[] (../src/upf/context.c:483)
12/18 00:10:29.438: [upf] INFO: UE F-SEID[UP:0xb1e CP:0xf0f] APN[ims] PDN-Type[1] IPv4[192.168.101.70] IPv6[] (../src/upf/context.c:483)
12/18 00:10:29.793: [upf] INFO: [Removed] Number of UPF-sessions is now 1 (../src/upf/context.c:250)
12/18 00:10:29.794: [upf] INFO: [Removed] Number of UPF-sessions is now 0 (../src/upf/context.c:250)
12/18 00:10:30.000: [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:206)
12/18 00:10:30.000: [upf] INFO: UE F-SEID[UP:0x40f CP:0x68f] APN[internet] PDN-Type[1] IPv4[192.168.100.79] IPv6[] (../src/upf/context.c:483)
12/18 00:10:30.000: [upf] INFO: UE F-SEID[UP:0x40f CP:0x68f] APN[internet] PDN-Type[1] IPv4[192.168.100.79] IPv6[] (../src/upf/context.c:483)
12/18 00:10:30.242: [upf] INFO: [Added] Number of UPF-Sessions is now 2 (../src/upf/context.c:206)
12/18 00:10:30.243: [upf] INFO: UE F-SEID[UP:0x1f5 CP:0xfae] APN[ims] PDN-Type[1] IPv4[192.168.101.71] IPv6[] (../src/upf/context.c:483)
12/18 00:10:30.243: [upf] INFO: UE F-SEID[UP:0x1f5 CP:0xfae] APN[ims] PDN-Type[1] IPv4[192.168.101.71] IPv6[] (../src/upf/context.c:483)
12/18 00:10:30.628: [upf] INFO: [Removed] Number of UPF-sessions is now 1 (../src/upf/context.c:250)
12/18 00:10:30.629: [upf] INFO: [Removed] Number of UPF-sessions is now 0 (../src/upf/context.c:250)
12/18 00:10:30.815: [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:206)
12/18 00:10:30.815: [upf] INFO: UE F-SEID[UP:0x28e CP:0xad4] APN[internet] PDN-Type[1] IPv4[192.168.100.80] IPv6[] (../src/upf/context.c:483)
12/18 00:10:30.815: [upf] INFO: UE F-SEID[UP:0x28e CP:0xad4] APN[internet] PDN-Type[1] IPv4[192.168.100.80] IPv6[] (../src/upf/context.c:483)
12/18 00:10:31.078: [upf] INFO: [Added] Number of UPF-Sessions is now 2 (../src/upf/context.c:206)
12/18 00:10:31.078: [upf] INFO: UE F-SEID[UP:0xa09 CP:0xce1] APN[ims] PDN-Type[1] IPv4[192.168.101.72] IPv6[] (../src/upf/context.c:483)
12/18 00:10:31.078: [upf] INFO: UE F-SEID[UP:0xa09 CP:0xce1] APN[ims] PDN-Type[1] IPv4[192.168.101.72] IPv6[] (../src/upf/context.c:483)
12/18 00:10:31.433: [upf] INFO: [Removed] Number of UPF-sessions is now 1 (../src/upf/context.c:250)
12/18 00:10:31.434: [upf] INFO: [Removed] Number of UPF-sessions is now 0 (../src/upf/context.c:250)
12/18 00:10:31.640: [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:206)
12/18 00:10:31.640: [upf] INFO: UE F-SEID[UP:0xc36 CP:0xb19] APN[internet] PDN-Type[1] IPv4[192.168.100.81] IPv6[] (../src/upf/context.c:483)
12/18 00:10:31.640: [upf] INFO: UE F-SEID[UP:0xc36 CP:0xb19] APN[internet] PDN-Type[1] IPv4[192.168.100.81] IPv6[] (../src/upf/context.c:483)
12/18 00:10:31.882: [upf] INFO: [Added] Number of UPF-Sessions is now 2 (../src/upf/context.c:206)
12/18 00:10:31.883: [upf] INFO: UE F-SEID[UP:0x4b0 CP:0x997] APN[ims] PDN-Type[1] IPv4[192.168.101.73] IPv6[] (../src/upf/context.c:483)
12/18 00:10:31.883: [upf] INFO: UE F-SEID[UP:0x4b0 CP:0x997] APN[ims] PDN-Type[1] IPv4[192.168.101.73] IPv6[] (../src/upf/context.c:483)
12/18 00:10:32.293: [upf] INFO: [Removed] Number of UPF-sessions is now 1 (../src/upf/context.c:250)
12/18 00:10:32.294: [upf] INFO: [Removed] Number of UPF-sessions is now 0 (../src/upf/context.c:250)
12/18 00:10:32.501: [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:206)
12/18 00:10:32.501: [upf] INFO: UE F-SEID[UP:0x29e CP:0xe47] APN[internet] PDN-Type[1] IPv4[192.168.100.82] IPv6[] (../src/upf/context.c:483)
12/18 00:10:32.501: [upf] INFO: UE F-SEID[UP:0x29e CP:0xe47] APN[internet] PDN-Type[1] IPv4[192.168.100.82] IPv6[] (../src/upf/context.c:483)
12/18 00:10:32.742: [upf] INFO: [Added] Number of UPF-Sessions is now 2 (../src/upf/context.c:206)
12/18 00:10:32.743: [upf] INFO: UE F-SEID[UP:0xd73 CP:0x8de] APN[ims] PDN-Type[1] IPv4[192.168.101.74] IPv6[] (../src/upf/context.c:483)
12/18 00:10:32.743: [upf] INFO: UE F-SEID[UP:0xd73 CP:0x8de] APN[ims] PDN-Type[1] IPv4[192.168.101.74] IPv6[] (../src/upf/context.c:483)
12/18 00:10:33.138: [upf] INFO: [Removed] Number of UPF-sessions is now 1 (../src/upf/context.c:250)
12/18 00:10:33.139: [upf] INFO: [Removed] Number of UPF-sessions is now 0 (../src/upf/context.c:250)
12/18 00:10:33.325: [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:206)
12/18 00:10:33.325: [upf] INFO: UE F-SEID[UP:0x8ba CP:0xc89] APN[internet] PDN-Type[1] IPv4[192.168.100.83] IPv6[] (../src/upf/context.c:483)
12/18 00:10:33.325: [upf] INFO: UE F-SEID[UP:0x8ba CP:0xc89] APN[internet] PDN-Type[1] IPv4[192.168.100.83] IPv6[] (../src/upf/context.c:483)
12/18 00:10:33.588: [upf] INFO: [Added] Number of UPF-Sessions is now 2 (../src/upf/context.c:206)
12/18 00:10:33.588: [upf] INFO: UE F-SEID[UP:0xfc CP:0x378] APN[ims] PDN-Type[1] IPv4[192.168.101.75] IPv6[] (../src/upf/context.c:483)
12/18 00:10:33.588: [upf] INFO: UE F-SEID[UP:0xfc CP:0x378] APN[ims] PDN-Type[1] IPv4[192.168.101.75] IPv6[] (../src/upf/context.c:483)
12/18 00:10:33.973: [upf] INFO: [Removed] Number of UPF-sessions is now 1 (../src/upf/context.c:250)
12/18 00:10:33.974: [upf] INFO: [Removed] Number of UPF-sessions is now 0 (../src/upf/context.c:250)
12/18 00:10:34.180: [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:206)
12/18 00:10:34.180: [upf] INFO: UE F-SEID[UP:0x3b CP:0x16d] APN[internet] PDN-Type[1] IPv4[192.168.100.84] IPv6[] (../src/upf/context.c:483)
12/18 00:10:34.180: [upf] INFO: UE F-SEID[UP:0x3b CP:0x16d] APN[internet] PDN-Type[1] IPv4[192.168.100.84] IPv6[] (../src/upf/context.c:483)
12/18 00:10:34.422: [upf] INFO: [Added] Number of UPF-Sessions is now 2 (../src/upf/context.c:206)
12/18 00:10:34.423: [upf] INFO: UE F-SEID[UP:0x378 CP:0x166] APN[ims] PDN-Type[1] IPv4[192.168.101.76] IPv6[] (../src/upf/context.c:483)
12/18 00:10:34.423: [upf] INFO: UE F-SEID[UP:0x378 CP:0x166] APN[ims] PDN-Type[1] IPv4[192.168.101.76] IPv6[] (../src/upf/context.c:483)
12/18 00:10:34.838: [upf] INFO: [Removed] Number of UPF-sessions is now 1 (../src/upf/context.c:250)
12/18 00:10:34.839: [upf] INFO: [Removed] Number of UPF-sessions is now 0 (../src/upf/context.c:250)
12/18 00:10:35.025: [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:206)
12/18 00:10:35.025: [upf] INFO: UE F-SEID[UP:0x9f1 CP:0xbf1] APN[internet] PDN-Type[1] IPv4[192.168.100.85] IPv6[] (../src/upf/context.c:483)
12/18 00:10:35.025: [upf] INFO: UE F-SEID[UP:0x9f1 CP:0xbf1] APN[internet] PDN-Type[1] IPv4[192.168.100.85] IPv6[] (../src/upf/context.c:483)
12/18 00:10:35.287: [upf] INFO: [Added] Number of UPF-Sessions is now 2 (../src/upf/context.c:206)
12/18 00:10:35.288: [upf] INFO: UE F-SEID[UP:0xbf9 CP:0xf60] APN[ims] PDN-Type[1] IPv4[192.168.101.77] IPv6[] (../src/upf/context.c:483)
12/18 00:10:35.288: [upf] INFO: UE F-SEID[UP:0xbf9 CP:0xf60] APN[ims] PDN-Type[1] IPv4[192.168.101.77] IPv6[] (../src/upf/context.c:483)
12/18 00:10:35.673: [upf] INFO: [Removed] Number of UPF-sessions is now 1 (../src/upf/context.c:250)
12/18 00:10:35.674: [upf] INFO: [Removed] Number of UPF-sessions is now 0 (../src/upf/context.c:250)
12/18 00:10:35.875: [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:206)
12/18 00:10:35.875: [upf] INFO: UE F-SEID[UP:0xea8 CP:0x653] APN[internet] PDN-Type[1] IPv4[192.168.100.86] IPv6[] (../src/upf/context.c:483)
12/18 00:10:35.875: [upf] INFO: UE F-SEID[UP:0xea8 CP:0x653] APN[internet] PDN-Type[1] IPv4[192.168.100.86] IPv6[] (../src/upf/context.c:483)
12/18 00:10:36.122: [upf] INFO: [Added] Number of UPF-Sessions is now 2 (../src/upf/context.c:206)
12/18 00:10:36.123: [upf] INFO: UE F-SEID[UP:0x35b CP:0x29] APN[ims] PDN-Type[1] IPv4[192.168.101.78] IPv6[] (../src/upf/context.c:483)
12/18 00:10:36.123: [upf] INFO: UE F-SEID[UP:0x35b CP:0x29] APN[ims] PDN-Type[1] IPv4[192.168.101.78] IPv6[] (../src/upf/context.c:483)
12/18 00:10:36.518: [upf] INFO: [Removed] Number of UPF-sessions is now 1 (../src/upf/context.c:250)
12/18 00:10:36.519: [upf] INFO: [Removed] Number of UPF-sessions is now 0 (../src/upf/context.c:250)
12/18 00:10:36.705: [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:206)
12/18 00:10:36.705: [upf] INFO: UE F-SEID[UP:0x834 CP:0x363] APN[internet] PDN-Type[1] IPv4[192.168.100.87] IPv6[] (../src/upf/context.c:483)
12/18 00:10:36.705: [upf] INFO: UE F-SEID[UP:0x834 CP:0x363] APN[internet] PDN-Type[1] IPv4[192.168.100.87] IPv6[] (../src/upf/context.c:483)
```

I would assume this is not the expected behavior, but unfortunately I lack any kind of expertise on this :(.

[ims-bad5.zip](https://github.com/herlesupreeth/docker_open5gs/files/13697924/ims-bad5.zip)

**Comment by herlesupreeth** [comment]
This is good news that UE is attaching to IMS APN now. But it seems eNB is rejecting creation of bearer for IMS signalling. May I know which eNB you are using? Are you using the srsLTE from this repo? or a separate installation? If its a separate installation please paste here the rb.conf file.

**Comment by razvancrainea** [comment]
@herlesupreeth I am using an external eNB, a Baicells pBS2120, so I am not using srsLTE. Not sure how to get the config of the Baicells though, but if you think it could help, I can check how to get something useful.
Is there any error indication I could probably look into the eNB logs?

Thanks a lot for your support!

**Comment by herlesupreeth** [comment]
> Is there any error indication I could probably look into the eNB logs?

From what I see in pcap, I would look for configuration related to QCI allowed etc. Because when eNB is instructed by EPC to create a bearer of QCI=5 for IMS signalling it replying saying there was a failure in radio procedure.

**Comment by razvancrainea** [comment]
Will check on that soon (out of station right now), thank you for the hint!

One more thing to double check - according to the tutorial, the 2 APNs (internet and ims) are created with the default QCI which is 9. According to different snapshots, I saw that a common config is the following one:
```
-------------------------------------------------------------------------------------------------------------------------
| APN      | QCI | ARP | Capability | Vulnerablility | MBR DL/UL(Kbps)     | GBR DL/UL(Kbps) | PGW IP        |
-------------------------------------------------------------------------------------------------------------------------
| internet | 9   | 8   | Disabled   | Disabled       | unlimited/unlimited |                 |               |           
-------------------------------------------------------------------------------------------------------------------------
| ims      | 5   | 1   | Enabled    | Enabled        | 128/128             | 128/128         |               |
|          | 1   | 2   | Enabled    | Enabled        | 128/128             | 128/128         |               |
|            Downlink permit out ip from any 1-65535 to any 1-65535
|            Uplink permit out ip from any 1-65535 to any 1-65535
-------------------------------------------------------------------------------------------------------------------------
```

Is this what I should be using in pyHSS as well as Open5GS subscriber settings?

**Comment by herlesupreeth** [comment]
`ims      | 5   | 1   | Enabled    | Enabled        | 128/128             | 128/128   `

This is wrong. It should be set to Disabled for QCI 5 and ARP 1 and have it set to Enabled for QCI1 and ARP 2

`Is this what I should be using in pyHSS as well as Open5GS subscriber settings?`

This setting is only required in open5gs

**Comment by razvancrainea** [comment]
Thank you, will adjust accordingly and update!

**Comment by razvancrainea** [comment]
I've made some progress - modified the Integrity algorithm in eNB to 128-EIA2/AES and adjusted the APN values in Open5GS - now the "ims" attach gets stabilized immediately, but still no REGISTER being sent :(
```
mme        | 12/18 15:42:35.951: [emm] INFO: [001010123456744] Attach complete (../src/mme/emm-sm.c:1298)
mme        | 12/18 15:42:35.951: [emm] INFO:     IMSI[001010123456744] (../src/mme/emm-handler.c:283)
mme        | 12/18 15:42:35.951: [emm] INFO:     UTC [2023-12-18T13:42:35] Timezone[0]/DST[0] (../src/mme/emm-handler.c:290)
mme        | 12/18 15:42:35.951: [emm] INFO:     LOCAL [2023-12-18T15:42:35] Timezone[7200]/DST[0] (../src/mme/emm-handler.c:294)
mme        | 12/18 15:42:35.999: [mme] INFO: [Added] Number of MME-Sessions is now 2 (../src/mme/mme-context.c:4447)
sgwc       | 12/18 15:42:36.000: [sgwc] INFO: [Added] Number of SGWC-Sessions is now 2 (../src/sgwc/context.c:879)
sgwc       | 12/18 15:42:36.000: [sgwc] INFO: UE IMSI[001010123456744] APN[ims] (../src/sgwc/s11-handler.c:237)
sgwu       | 12/18 15:42:36.000: [sgwu] INFO: UE F-SEID[UP:0x1c6 CP:0xf52] (../src/sgwu/context.c:169)
sgwu       | 12/18 15:42:36.000: [sgwu] INFO: [Added] Number of SGWU-Sessions is now 2 (../src/sgwu/context.c:174)
smf        | 12/18 15:42:36.001: [smf] INFO: [Added] Number of SMF-Sessions is now 2 (../src/smf/context.c:3057)
smf        | 12/18 15:42:36.001: [smf] INFO: UE IMSI[001010123456744] APN[ims] IPv4[192.168.101.2] IPv6[] (../src/smf/s5c-handler.c:255)
upf        | 12/18 15:42:36.009: [upf] INFO: [Added] Number of UPF-Sessions is now 2 (../src/upf/context.c:206)
upf        | 12/18 15:42:36.009: [upf] INFO: UE F-SEID[UP:0x1b9 CP:0xc8b] APN[ims] PDN-Type[1] IPv4[192.168.101.2] IPv6[] (../src/upf/context.c:483)
upf        | 12/18 15:42:36.009: [upf] INFO: UE F-SEID[UP:0x1b9 CP:0xc8b] APN[ims] PDN-Type[1] IPv4[192.168.101.2] IPv6[] (../src/upf/context.c:483)
smf        | 12/18 15:42:36.010: [smf] WARNING: Unknown PCO ID:(0x2) (../src/smf/context.c:3000)
```

I did notice the latter warning, but from what I could read, it is harmless.

**Comment by herlesupreeth** [comment]
Restart the phone and give it a try again

**Comment by razvancrainea** [comment]
Still no luck :(. The latest pcap is taken from the boot of the phone. I did notice that by default it does not attach to the "ims" APN though, I need to toggle the "Use VoLTE" switch to do it.
[ims-bad7.zip](https://github.com/herlesupreeth/docker_open5gs/files/13705149/ims-bad7.zip)

Thanks again!

**Comment by herlesupreeth** [comment]
Now, eNB seems to accept the bearer creation for QCI 5 but not sure why REGISTER is not sent

Couple of things I missed earlier:

`ims      | 5   | 1   | Enabled    | Enabled        | 128/128             | 128/128   `

You should not set MBR DL/UL(Kbps) and GBR DL/UL(Kbps) for QCI 5 and ARP 1

Also, can you set the MTU to 1500 in smf.yaml file and give it a try?

**Comment by razvancrainea** [comment]
Updated the Open5GS accordingly
![ims](https://github.com/herlesupreeth/docker_open5gs/assets/1511224/27be55ee-98c5-4929-a5bc-6fb3703b7f90)
Also modified the MTU to 1500 directly in the container and restarted. Unfortunately, without any luck, no REGISTER coming :(.

Attached is a new pcap taken from the latest attepmpt.
[ims-bad8.zip](https://github.com/herlesupreeth/docker_open5gs/files/13715879/ims-bad8.zip)

**Comment by razvancrainea** [comment]
Indeed, the MTU was not changed, I had to modify the `smf/smf_4g.yaml` file.

Attached is the new pcap, with the 1500 MTU, but still no change. I will check how to get eNB logs and get back when I have updates.
[ims-bad9.zip](https://github.com/herlesupreeth/docker_open5gs/files/13716216/ims-bad9.zip)

Thanks a lot for your time!

**Comment by razvancrainea** [comment]
Attached is a new zip that contains RRC information replicated over UDP from 192.168.150.1 to 192.168.150.2 UDP port 4337
[ims-bad10.zip](https://github.com/herlesupreeth/docker_open5gs/files/13716383/ims-bad10.zip)

**Comment by herlesupreeth** [comment]
Thanks a lot for all the traces. I still dont know why UE is not sending SIP REGISTER.

I have some questions:

> I got to the point where I have a registered UE with a working 4G connection in Roaming through the "ims" APN. 

Are you testing roaming by any chance? is your EPC and eNB running with same PLMN as the programmed SIM card?

> It's worth mentioning that I am using the same device (Xiaomi Redmi Note 9T 5G) in a different setup (single host) and it works just fine.

Can you please elaborate on what you mean by single host setup? Did you try with srsLTE eNB?

**Comment by razvancrainea** [comment]
> Are you testing roaming by any chance? is your EPC and eNB running with same PLMN as the programmed SIM card?

When I opened the ticket, 4G was working only in roaming - but that's because I did not program the SIM card correctly. Once I did that, I am no longer Roaming.

> Can you please elaborate on what you mean by single host setup? Did you try with srsLTE eNB?
I was referring to the terminology of the [tutorial](https://github.com/herlesupreeth/docker_open5gs/tree/master?tab=readme-ov-file#single-host-setup-configuration), single host vs multihost. I have a completely different setup, which is using an USRP B210 ran by srsLTE eNB, all on a single machine - that one is working fine, and my device registers properly on it. I only mentioned it to rule out any issues with the device/phone.

For the setup I am troubleshooting, the one running the Baicells, I don't think I can use srsLTE, as it is a dedicated hardware with an embedded software eNB. I don't think I can change it. Do correct me if I am wrong :).

As you probably noticed, I am a newby in LTE, my background is limited to SIP - this is actually why I am trying to create this setup, to have an environment that I can use to enhance the IMS/SIP stack. So apologies for my lack of knowledge.
When I initially opened the ticket, I thought I was missing something obvious (and apparently I was missing a lot of stuff), but apparently things got more complex. Many thanks for helping me take this journey!

If you are out of ideas, feel free to close the ticket, as the things are probably OK on the open5GS side. I will try to poke the guys from Baicells to see if they can spot any issues. I will update if I get any useful information.

Once again, many thanks for your help and support!

**Comment by herlesupreeth** [comment]
> For the setup I am troubleshooting, the one running the Baicells, I don't think I can use srsLTE, as it is a dedicated hardware with an embedded software eNB. I don't think I can change it. Do correct me if I am wrong :).

You are right. You cant run srsLTE eNB there. If the phone registers correctly when using srsLTE eNB and does not send SIP REGISTER when using Baicells then its definitely an eNB setting in Baicells which is missing.

**Comment by herlesupreeth** [comment]
I would probably check whether the following field is sent in SIB1 message from Baicells. Sometimes UEs dont want to attach to IMS if this field is not set.

![image](https://github.com/herlesupreeth/docker_open5gs/assets/4115839/b44a39e7-1117-42ab-9ebf-f1102b1f96b3)
