### ISSUE TITLE
error when running srsenb

### ISSUE THREAD

**Issue by sajem2020** [herlesupreeth/docker_open5gs#27]
I could run kamailio from https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/ but I have error when running srsenb.
I have used the config file from " https://github.com/herlesupreeth/Open5gs_Config"
error
Setting frequency: DL=2685.0 Mhz, UL=2565.0 MHz for cc_idx=0
connect(): Connection refused
Failed to initiate SCTP socket. Attempting reconnection in 10 seconds

==== eNodeB started ===
Type <t> to view trace
connect(): Connection refused
Failed to initiate SCTP socket. Attempting reconnection in 10 seconds

**Comment by herlesupreeth** [comment]
Please raise this issue in open5gs if you are not using this repository.

To answer to above issue, you have a wrong configuration in enb.conf and mme.yaml

**Comment by sajem2020** [comment]
my enb.conf and mme.yaml are :

[mme.zip](https://github.com/herlesupreeth/docker_open5gs/files/6030266/mme.zip)
[enb.zip](https://github.com/herlesupreeth/docker_open5gs/files/6030273/enb.zip)

when I run srslte with the confign file of open5gs, there is no error
https://open5gs.org/open5gs/docs/guide/02-building-open5gs-from-sources/
thank you

**Comment by herlesupreeth** [comment]
You have wrong settings in enb.conf, the mme address should be the IP address of the machine running open5gs MME and gtp and s1c bind address should be the IP address of the machine running eNB

![image](https://user-images.githubusercontent.com/4115839/108959083-34db4000-7674-11eb-99e8-22ba65c0e23f.png)
