### ISSUE TITLE
srsGNB ERROR: Failed to create SCTP gateway.

### ISSUE THREAD

**Issue by athiravinod5gtechie** [herlesupreeth/docker_open5gs#274]
[outputofpcp_in txt_format.txt](https://github.com/herlesupreeth/docker_open5gs/files/13940540/outputofpcp_in.txt_format.txt)
[docker ps.txt](https://github.com/herlesupreeth/docker_open5gs/files/13940404/docker.ps.txt)
[amf_logs.txt](https://github.com/herlesupreeth/docker_open5gs/files/13940520/amf_logs.txt)

[sa-up-terminal.txt](https://github.com/herlesupreeth/docker_open5gs/files/13940405/sa-up-terminal.txt)
[terminal_issue.txt](https://github.com/herlesupreeth/docker_open5gs/files/13940406/terminal_issue.txt)
Hi @herlesupreeth ,

I am trying to do 5g sa deployment with srsran. While executing # srsRAN ZMQ gNB (RF simulated)
docker compose -f srsgnb_zmq.yaml up -d && docker container attach srsgnb_zmq Command i am facing the issue:
```

****--== srsRAN gNB (commit 55c984b55) ==--
[sa-up-terminal.txt](https://github.com/herlesupreeth/docker_open5gs/files/13940389/sa-up-terminal.txt)

Failed to bind SCTP socket to 172.22.0.37:0. Success
srsGNB ERROR: Failed to create SCTP gateway.****

docker images and process (attached )
issue terminal output and output of docker compose -f sa-deploy.yaml up (attached)
pcap trace (attached)
amf logs (attached)
[amf_logs.txt](https://github.com/herlesupreeth/docker_open5gs/files/13940507/amf_logs.txt)


[docker ps.txt](https://github.com/herlesupreeth/docker_open5gs/files/13940323/docker.ps.txt)
[terminal_issue.txt](https://github.com/herlesupreeth/docker_open5gs/files/13940390/terminal_issue.txt)
Would you please guide me to resolve this issue?
Thanks,
Athira

**Comment by athiravinod5gtechie** [comment]
[docker ps.txt](https://github.com/herlesupreeth/docker_open5gs/files/13940409/docker.ps.txt)

**Comment by athiravinod5gtechie** [comment]
[sa-up-terminal.txt](https://github.com/herlesupreeth/docker_open5gs/files/13940411/sa-up-terminal.txt)

**Comment by athiravinod5gtechie** [comment]
[terminal_issue.txt](https://github.com/herlesupreeth/docker_open5gs/files/13940413/terminal_issue.txt)

**Comment by herlesupreeth** [comment]
hmmm, can you paste here the version of docker-ce and docker compose you have installed on that machine?

Also, can you ensure whether you have installed `libsctp-dev` on the host machine where you are running docker_open5gs?

NOTE: you would need to run 5GC first and wait for some time until AMF is completely up (around 10 seconds or so) and then start gNB

**Comment by athiravinod5gtechie** [comment]
Hi @herlesupreeth ,
**Details :**
Docker version 24.0.5, build 24.0.5-0ubuntu1~20.04.1
docker-compose version 1.25.0, build 0a186604
**libsctp-dev is installed**
ii  libsctp-dev:amd64                      1.0.18+dfsg-1                     amd64        user-space access to Linux kernel SCTP - development files
Tried after AMF is up , still same issue is coming up. 
Requesting for support 
Thanks,
Athira Vinod

**Comment by herlesupreeth** [comment]
Did you change any IP in .env file? or do any modifications to files in docker_open5gs ??

And, your host machine where you are running docker_open5gs is a linux machine running Ubuntu right? (not a windows machine right?)

Also, can you send me the output of below commands?

```
ip a
sudo modprobe sctp
sudo netstat -tuplnSv | grep 38412
```
