### ISSUE TITLE
about configuration doc of yaml

### ISSUE THREAD

**Issue by horser1** [herlesupreeth/docker_open5gs#28]
@herlesupreeth hello ,thanks for your sharing
should I fill all yaml doc, including MCC, MNC,  *_IP, *_IF, EPC_DOMAIN and so on. But I don't know what  do *_IF and *_DOMAIN means..
![图片](https://user-images.githubusercontent.com/48501653/109645118-5d41cd80-7b91-11eb-9dc6-5dd6a944a839.png)
thanks

**Comment by herlesupreeth** [comment]
Nope, the only place where you need to personalize is the .env file, that too only MNC and MCC. Keep the rest as is it

**Comment by horser1** [comment]
thanks for your timely reply 👍

**Comment by horser1** [comment]
hello , I find no .env file 
![图片](https://user-images.githubusercontent.com/48501653/109648130-35ecff80-7b95-11eb-8435-d04566e3a650.png)

**Comment by horser1** [comment]
hello ,when I do`docker-compose -f srsenb.yaml build --no-cache`
![图片](https://user-images.githubusercontent.com/48501653/109756373-c6bdec80-7c22-11eb-8215-5d708822ba68.png)
I have config the host machine's nameservers, but it's no use. 
I run 'apt update' it with no problem in my host machine.
![图片](https://user-images.githubusercontent.com/48501653/109756685-582d5e80-7c23-11eb-99ff-87fa91fc2ab9.png)

**Comment by herlesupreeth** [comment]
Definitely a dns issue completely unrelated to srsenb.

I see on your host that the mirrors for ubuntu are with link http://mirrors.aliyun.com/ubuntu where as the ubuntu bionic image is looking for http:://security.ubuntu.com/ubuntu and this is not resolved
