### ISSUE TITLE
Getting the issue of sgwc Exited.

### ISSUE THREAD

**Issue by shanmukhapothana** [herlesupreeth/docker_open5gs#280]
Hi Team,
I am using docker_open5gs (open5gs_hss_cx branch) to testing the Volte.

while running the core network by using the following the command **docker compose -f 4g-volte-deploy.yaml up**

And by checking the status of the containers **we are facing the sgwc exited** and we disable the firewall also. 

as we observed in the logs:
**FATAL: epoll_init: Assertion `context->epfd >= 0' failed. (../lib/core/ogs-epoll.c:77)**

kindly find the attached log and please help me out of this issue.
 
[sgwu.log](https://github.com/herlesupreeth/docker_open5gs/files/14107716/sgwu.log)
[sgwc.log](https://github.com/herlesupreeth/docker_open5gs/files/14107718/sgwc.log)
![image001](https://github.com/herlesupreeth/docker_open5gs/assets/132892962/7d58b009-de36-4e0b-9280-48d840030a2d)

**Comment by herlesupreeth** [comment]
Thank you for spotting this issue. I have pushed the fix to that branch just now, please pull the latest commits and give it a try

**Comment by Sivanesh1992** [comment]
hi @herlesupreeth 

after add below changes in sgwu.yml

logger:
    file: /open5gs/install/var/log/open5gs/sgwu.log

global:
  max:
    ue: MAX_NUM_UE

parameter:

sgwu:
    gtpu:
      server:
        - address: SGWU_IP
          advertise: SGWU_ADVERTISE_IP
    pfcp:
      server:
        - address: SGWU_IP
      client:
        sgwc:
          - address: SGWC_IP

i am getting same error .  i need to rebuild core network again?

![image](https://github.com/herlesupreeth/docker_open5gs/assets/96040330/6ffede9f-fca5-45d8-a8b4-426e7e34476d)

**Comment by shanmukhapothana** [comment]
Its working fine now...Thank you.
