### ISSUE TITLE
VoNR IMS registration SUBSCRIBE fails

### ISSUE THREAD

**Issue by alexjiao2021** [herlesupreeth/docker_open5gs#283]
Hi @herlesupreeth 
I tried latest docker files of open5gs and Kamailio IMS, I used **sa-vonr-deploy.yaml**. UE can pass the authentication procedure in IMS, but when UE send SUBSCRIBE message, network responded with "403 Forbidden - You must register first with a S-CSCF".
![vonr_subscribe_forbidden](https://github.com/herlesupreeth/docker_open5gs/assets/84055495/a31e56af-3842-41c7-9bcf-42c1c3859274)

Could you please take a look?
pcap log: 
[vonr.zip](https://github.com/herlesupreeth/docker_open5gs/files/14333034/vonr.zip)

**Comment by herlesupreeth** [comment]
It looks like a bug in kamailio. Can you please enable debug mode by changing to the following in pcscf.cfg file??

`#!define WITH_DEBUG`

and then do a fresh IMS registration with that Samsung device and send me only the PCSCF logs 

`docker logs pcscf`

**Comment by alexjiao2021** [comment]
@herlesupreeth 
Here is P-CSCF logs:
[pcscf.txt](https://github.com/herlesupreeth/docker_open5gs/files/14361620/pcscf.txt)
Thanks.

**Comment by alexjiao2021** [comment]
Sorry, last log is not complete, below is complete one:
[pcscf_logs.txt](https://github.com/herlesupreeth/docker_open5gs/files/14362005/pcscf_logs.txt)

**Comment by herlesupreeth** [comment]
Sorry for the long delay, can try applying the below diff to the latest commits of this repo and give it a try?

Dont forget to recompile the base image of kamailio

```
diff --git a/ims_base/Dockerfile b/ims_base/Dockerfile
index a45191c..6557e89 100644
--- a/ims_base/Dockerfile
+++ b/ims_base/Dockerfile
@@ -34,12 +34,12 @@ RUN apt-get update && \
                                        gcc flex bison libmysqlclient-dev make libssl-dev libcurl4-openssl-dev \
                                        libxml2-dev libpcre2-dev bash-completion g++ autoconf libmnl-dev \
                                        libsctp-dev libradcli-dev libradcli4 libjson-c-dev pkg-config iproute2 net-tools \
-                                       iputils-ping
+                                       iputils-ping libgcrypt20-dev
 
 # Fetch Kamailio code (branch 5.3)
 RUN mkdir -p /usr/local/src/ && cd /usr/local/src/ && \
-       git clone https://github.com/kamailio/kamailio && \
-       cd kamailio && git checkout 4df92312166d8aad700007ef0898d0a7c6ba40b7
+       git clone https://github.com/herlesupreeth/kamailio && \
+       cd kamailio && git checkout remove_username_match
 
 # Build and Install Kamailio
 RUN cd /usr/local/src/kamailio && make cfg
diff --git a/pcscf/pcscf.cfg b/pcscf/pcscf.cfg
index 9d9a3a8..8dbbc9a 100644
--- a/pcscf/pcscf.cfg
+++ b/pcscf/pcscf.cfg
@@ -116,7 +116,7 @@ alias=pcscf.IMS_DOMAIN
 
 #
 # Enabled Features for this host:
-##!define WITH_DEBUG
+#!define WITH_DEBUG
 #!define WITH_NAT
 #!define WITH_NATPING
 #!define FORCE_RTPRELAY
```

**Comment by alexjiao2021** [comment]
@herlesupreeth 
Sorry, the diff file seems not applied correctly:
`alex@alex-virtual-machine:~/docker_open5gs$ sudo git apply ims.diff
error: patch failed: ims_base/Dockerfile:34
error: ims_base/Dockerfile: patch does not apply
error: patch failed: pcscf/pcscf.cfg:116
error: pcscf/pcscf.cfg: patch does not apply`

Any suggestions please?

**Comment by herlesupreeth** [comment]
First pull the latest changes for the branch you are using (I pushed a fix for another issue this morning) and then do `git apply ims.diff`

**Comment by alexjiao2021** [comment]
Pulled the latest changes:
```
alex@alex-virtual-machine:~/docker_open5gs$ sudo git pull
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 42 (delta 29), reused 42 (delta 29), pack-reused 0
Unpacking objects: 100% (42/42), 3.43 KiB | 54.00 KiB/s, done.
From https://github.com/herlesupreeth/docker_open5gs
   d531b57..b538301  master         -> origin/master
   2ebad49..99a0877  latest_pyhss   -> origin/latest_pyhss
   adc8abe..3a774ef  open5gs_hss_cx -> origin/open5gs_hss_cx
Updating d531b57..b538301
Fast-forward
 amf/amf.yaml    | 2 --
 ausf/ausf.yaml  | 2 --
 bsf/bsf.yaml    | 2 --
 hss/hss.yaml    | 2 --
 mme/mme.yaml    | 2 --
 nrf/nrf.yaml    | 2 --
 nssf/nssf.yaml  | 2 --
 pcf/pcf.yaml    | 2 --
 pcrf/pcrf.yaml  | 2 --
 scp/scp.yaml    | 2 --
 sgwc/sgwc.yaml  | 2 --
 sgwu/sgwu.yaml  | 2 --
 smf/smf.yaml    | 5 ++---
 smf/smf_4g.yaml | 5 ++---
 udm/udm.yaml    | 2 --
 udr/udr.yaml    | 2 --
 upf/upf.yaml    | 2 --
 17 files changed, 4 insertions(+), 36 deletions(-)
```
Still got error when applying the patch:
```
alex@alex-virtual-machine:~/docker_open5gs$ sudo git apply ims.diff
error: patch failed: ims_base/Dockerfile:34
error: ims_base/Dockerfile: patch does not apply
error: patch failed: pcscf/pcscf.cfg:116
error: pcscf/pcscf.cfg: patch does not apply
```

**Comment by herlesupreeth** [comment]
Then, I would suggest applying those changes seen in the diff manually and giving it a try

**Comment by alexjiao2021** [comment]
Thanks, issue is fixed.
