### ISSUE TITLE
SMS over IMS issue in 5G SA

### ISSUE THREAD

**Issue by alexjiao2021** [herlesupreeth/docker_open5gs#286]
Hi @herlesupreeth 
I tried connect iPhone and OnePlus phone to the 5G SA network, both registered in IMS successfully.
When I tried send SMS from iPhone (MSISDN 1234567890) to OnePlus (MSISDN 1234567891), only send SMS message once, but OnePlus keep receiving the message. Then I try send SMS from OnePlus to iPhone, no message is received on iPhone.
Could you please help take a look? Thanks!
Here is pcap log:
[iphone14pro_oneplus10pro_sms_over_ims_nr.zip](https://github.com/herlesupreeth/docker_open5gs/files/14468462/iphone14pro_oneplus10pro_sms_over_ims_nr.zip)

**Comment by alexjiao2021** [comment]
Update:
Changed OnePlus UE to Samsung UE, send SMS from iPhone to Samsung once, still repeating received message on Samsung.
Send SMS from Samsung to iPhone once, received only once on iPhone.
PCAP log here:
[iphone14pro_samsung_s23_sms_over_ims_nr.zip](https://github.com/herlesupreeth/docker_open5gs/files/14471432/iphone14pro_samsung_s23_sms_over_ims_nr.zip)

**Comment by alexjiao2021** [comment]
SMS between Android UE works OK, seems to be iPhone UE issue for MO SMS case.

**Comment by herlesupreeth** [comment]
Its good that SMS works. I remember testing SMS from Oneplus 5 to iPhone and it worked just fine for me (before switching to latest kamailio). I will let you know if i face same issue, if so I will try to fix it.  Thanks for reporting the issue

**Comment by herlesupreeth** [comment]
I tried sending SMS from iPhone to Oneplus and I had same experience of iPhone sending again and again SMS. Couldn't fix the issue as nothing seems to be wrong in the message send to iPhone

**Comment by alexjiao2021** [comment]
Thanks!
