### ISSUE TITLE
Add multiple user on open5gs without using WebUI

### ISSUE THREAD

**Issue by henintsoa98** [herlesupreeth/docker_open5gs#309]
I use 10 sysmocom SIM, so I want to create Subscriber on open5gs (http://<DOCKER_IP:9999>) by using script without passing by WebUI. \
I found some tools like [open5gs-dbctl](https://github.com/open5gs/open5gs/blob/main/misc/db/open5gs-dbctl) or [Open5GS.py](https://github.com/open5gs/open5gs/tree/main/misc/db/python). \
I would like to ask some question :
1. I want to know how to add one user on script by CLI? so I can copy it on other sim.
2. And I want to kwow on where docker processus is the this database, and this port?

**Comment by herlesupreeth** [comment]
Hey, I accepted a pull request now which allows adding Subscriber information via open5gs-dbctl. Please find its instructions here - https://github.com/herlesupreeth/docker_open5gs?tab=readme-ov-file#or-using-cli

**Comment by henintsoa98** [comment]
Thank you, this will help us a lot
