### ISSUE TITLE
Dockerized Volte in openstack

### ISSUE THREAD

**Issue by modyngs** [herlesupreeth/docker_open5gs#31]
Dear @herlesupreeth @miaoski 
Hi
I have used this repo to implement VOLTE. So i followed the same rules as in instruction. ( DOCKER IP ADDRESSES ARE REMAINED AS DEFAULT)

****** My setup is openstack vm (CORE + IMS) with 8 core 16GB ram 50GB Hard internal Ip addr is 192.168.1.169  and Floating Ip add of 46.100.56.23 ( i rent openstack panel, So 192.168.1.169 is not my local ip and its not in my local Network. It means 46.100.56.23 is dedicated Ip address) and **run your docker instruction over that!**

****** For eNB i have a Pc in my local network with 192.168.1.10 ip addr with SRSLTE project installed and tested ( My local Network Does Not have Dedicated Ip addr. )
 

But i can not connect srsenb to the MME it sayed connection refuse

i also followed https://github.com/herlesupreeth/Open5gs_Config/issues/4#issuecomment-737031208 comment but still eNB is not connecting to The Core with specified configuration! ( SPGW ip addresses in CORE+IMS VM is as default configs and default ip without any change  in .env )

Should i change any config in order to have connection between eNB and Core? could u please mention it

Thanks
Best regards

**Comment by modyngs** [comment]
**FOR CORE+IMS** Notting has been changed in config file:
All setting and IPs are as Default

**FOR eNB** Just Have been changed IPs in eNB
mme_addr = 46.100.56.23
gtp_bind_addr = 192.168.1.10
s1c_bind_addr = 192.168.1.10



Do i need to set route or changng SPGW_U/C in CORE VM (.env file)?

**Comment by modyngs** [comment]
One Note That i could access WebUI and FoHSS through 46.100.56.23:3000 on my Local PC (which installed SRSLTE  eNB on it)
But could not connect eNB to Dockerized VOLTE Core !

**Comment by herlesupreeth** [comment]
i recently updated the README for connection external eNB to dockerized EPC + IMS solution here - https://github.com/herlesupreeth/docker_open5gs#configuration . Please refer it and do the necessary changes

**Comment by modyngs** [comment]
Thanks,
Best regards
