### ISSUE TITLE
OAI e/gNB

### ISSUE THREAD

**Issue by modyngs** [herlesupreeth/docker_open5gs#32]
Dear @herlesupreeth 
Hi,
Have u ever tried Combination of OAI NSA (RAN) with your Dockerized VOLTE (CORE)?
I can see there is oai file in your repo, but its just eNB in docker

Have you ever tested Dockerized VOLTE with their RAN (NSA Mode) on Bare Metal ( i mean not dockerized version and just native ubuntu on diffrent pcs)?

Thanks
Best regards

**Comment by herlesupreeth** [comment]
Hi @modyngs , Unfortunately no. I tried OAI eNB in docker as you can see in this repo but i am afraid it was not as stable as I expected
