### ISSUE TITLE
No IMS registration

### ISSUE THREAD

**Issue by kamgaarnold** [herlesupreeth/docker_open5gs#327]
Hello @herlesupreeth. Hope you doing great
Actually i'm new to the setup using SDR to build a network. So i decided to use the Kamailo (the same link on your github)to build the network and perform a VoLTE call (which is not working yet)and the following have already been compeleted:

1) i was able to do a successful attach and i'll add the PCAP Here.
2) To perform the IMS, i downloaded the CoIMS app in the case of samsung and i had to add certificate to the sim so it could be accessed. Initially when i put the SIM, the app was saying "carrier priviledges not allowed" but when certificates was added it got solved. but volte provisionned was still disabled
3) I also saw one of your comments on a post to use IPHONE because it will not use the coIMS app. i used the iphone and VoLTE was autolmatically activated on the phone but could not see anything in the logs.

Please can you help guide me on this?

Thanks
[5_27_2024.zip](https://github.com/herlesupreeth/docker_open5gs/files/15480205/5_27_2024.zip)

**Comment by herlesupreeth** [comment]
Hey @kamgaarnold I see that you had wrong APN configured first and then changed to "F2G" and UE was able to connect to the 4G network, but I dont see UE requesting a PDN connection towards "ims' APN i.e. there should be another PDN connectivity request after the highlighted packet in below screenshot

![image](https://github.com/herlesupreeth/docker_open5gs/assets/4115839/99bd0e6d-9995-4e77-8553-52798c0f2d73)

May I know which UE it is in the trace? iphone or samsung phone?

**Comment by kamgaarnold** [comment]
Hi @herlesupreeth. Thanks for the quick reply. Yes I changed the apn from internet to F2G in both the Phyhss and open5gs
The pcap attach in my first comment is for the samsung s10.
When using apple I had an issue because the pcap log was complain about "unknown PLMN". But the Volte was enable. Besides I was using an iphone8 and couldn't add an APN. 
Yes and as you said there is no PDN connectivity for the ims which is where I'm stucked for now. 
I can see that all the core éléments are initialized but no PDNConnectivity is coming in for qci-5.

Thankw

**Comment by kamgaarnold** [comment]
> Hey @kamgaarnold I see that you had wrong APN configured first and then changed to "F2G" and UE was able to connect to the 4G network, but I dont see UE requesting a PDN connection towards "ims' APN i.e. there should be another PDN connectivity request after the highlighted packet in below screenshot
> 
> ![image](https://private-user-images.githubusercontent.com/4115839/334693598-99bd0e6d-9995-4e77-8553-52798c0f2d73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODAwODYsIm5iZiI6MTcxNjk3OTc4NiwicGF0aCI6Ii80MTE1ODM5LzMzNDY5MzU5OC05OWJkMGU2ZC05OTk1LTRlNzctODU1My01Mjc5OGMwZjJkNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMTA0OTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDA5Zjc5Yjk3N2NhZjEwZjNiMWMwYjZkMTU4NjAyNzBhYjM1ZGU5YzI4NmM1NTBiY2U3NzM5ZjkxMzRhZDgwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hELp3yipZmTirl-DdIw2EXwTUThvTnBCt9uRUe4fZSs)
> 
> May I know which UE it is in the trace? iphone or samsung phone?
Hi @herlesupreeth. Thanks for the quick reply. It is a samsung phone. Photo is attached
![IMG-20240527-WA0027](https://github.com/herlesupreeth/docker_open5gs/assets/171120720/241c9e88-2301-48df-bd2f-98b418ca4ff3)

**Comment by herlesupreeth** [comment]
> The pcap attach in my first comment is for the samsung s10.

CoIMS method sadly doesnt work on Samsung device running Android 10 and above. The reason you dont see PDN connectivity request for ims APN is because VoLTE is not enabled on that device.

**Comment by kamgaarnold** [comment]
> > The pcap attach in my first comment is for the samsung s10.
> 
> CoIMS method sadly doesnt work on Samsung device running Android 10 and above. The reason you dont see PDN connectivity request for ims APN is because VoLTE is not enabled on that device.

@herlesupreeth  thanks for letting me know that Android does not support CoIMS and it makes sense also because the VoLTE is not enable as shown on the photo. 
Please do you advice any other UE i can use? I tried using a oneplus but it does not recognise my sim.

**Comment by kamgaarnold** [comment]
Hello @herlesupreeth.
Please in order to have the PDN, do we need to masquerade the Sgi interface in the case of docker_5gs?
By the way what UE do you recommend for this setup please.
Thanks

**Comment by herlesupreeth** [comment]
> Please do you advice any other UE i can use? I tried using a oneplus but it does not recognise my sim.

You can use any other phone apart from Samsung devices. Just keep note that its better to go with a phone which has Qualcomm chipset in it.

> Please in order to have the PDN, do we need to masquerade the Sgi interface in the case of docker_5gs?

I dont think those two are related

**Comment by kamgaarnold** [comment]
Hello @herlesupreeth. please i've been stocked on this IMS issue. Actually i tried today and i see "extended service request" followed by CSFB.
I used the kamailo setup. so i don't know if there is an issue or i'm missing something?
The attach is ok with QCI-9 but for ims i get nothing.
[6_19_2024.zip](https://github.com/user-attachments/files/15908593/6_19_2024.zip)

**Comment by herlesupreeth** [comment]
> The attach is ok with QCI-9 with both APN added on the UE but i don't get any PDN for ims hence no sip registration.

sadly its a UE issue and nothing can be done. I would suggest to try with any other phone than Samsung

**Comment by kamgaarnold** [comment]
> suggest

Alright. I tried with an iphone 13, but i still get CSFB 🥺

**Comment by kamgaarnold** [comment]
> > The attach is ok with QCI-9 with both APN added on the UE but i don't get any PDN for ims hence no sip registration.
> 
> sadly its a UE issue and nothing can be done. I would suggest to try with any other phone than Samsung

@herlesupreeth I tried with an iphone13 but it still does CSFB 🥺

**Comment by herlesupreeth** [comment]
> I tried with an iphone13 but it still does CSFB 🥺 eventhough VoLTE is enabled

please restart the phone and try to attach with iPhone 13 and send me the pcap

**Comment by kamgaarnold** [comment]
Alright. let me try and attach the PCAP.
Thanks

**Comment by kamgaarnold** [comment]
[Hurlee.zip](https://github.com/user-attachments/files/15938138/Hurlee.zip)
Hello @herlesupreeth. i attached 3 PCAP in the folder.
Thanks. i'll keep checking but still facing CSFB.
I'm not sure if something is missen in my config. If you need something more, i can share with you

**Comment by herlesupreeth** [comment]
I think your APN configuration in open5gs is wrong. You should have internet APN first and then ims APN and i think you have the other way around

![image](https://github.com/herlesupreeth/docker_open5gs/assets/4115839/1f73bc77-a87d-489a-8c26-f22effa5c8cc)

**Comment by kamgaarnold** [comment]
@herlesupreeth if you go through the zip file, the 3rd pcap has internet as default. The other 2 you can disregard because I set ims as défault when doing a scénario to see if the UE still attach.

Thanks

**Comment by herlesupreeth** [comment]
hmm.. then I didnt see UE attempting a PDN connection ims APN. Can you reprogram the SIM to 00101 and set MNC and MCC accordingly in env file and give it a try ?

**Comment by kamgaarnold** [comment]
@herlesupreeth ok i'll do that. but the quick question i have is if all my scenario keep doing CSFB, then it probably means that the IMS is not up and then the UE prefers to fall to 3G. Is there something i need to check in any config file concerning the ims?

**Comment by herlesupreeth** [comment]
Aha, I now see ims PDN connectivity request from UE and thats good news. Can you please take the pcap on the entire machine running docker_open5gs when the UE attempts to connect to network. The pcap you took has only S1AP packet and no GTP packets

> But there is no dedicated bearer activated so no call will go through.

Dedicated bearer is created only during a VoLTE call and not before

**Comment by kamgaarnold** [comment]
@herlesupreeth I don't get it. It's true we can't see gtp packet. I'm not sure on how to do what you're suggesting. Can you guide a little. 
In the enb.conf what line do I need to uncomment to see gtp packet?

**Comment by herlesupreeth** [comment]
Use tcpdump to take trace on the host machine where you are running docker_open5gs (please look up on internet how to do so)

> In the enb.conf what line do I need to uncomment to see gtp packet?

Its not a setting in eNB.

**Comment by kamgaarnold** [comment]
Hello @herlesupreeth . i attach the pcap here. i succeeded to see the SIP. but now when i use 2 Devices with 2 IMSI'S i can't perform a call. Is there any work around to perform this?

Thanks
[6_28_2024.zip](https://github.com/user-attachments/files/16038937/6_28_2024.zip)

**Comment by herlesupreeth** [comment]
You have incorrectly provisioned the SCSCF URI in the HSS. Its should be `sip:scscf.ims.mnc001.mcc001.3gppnetwork.org:6060`

and NOT `sip:scscf.ims.mnc01.mcc001.3gppnetwork.org:6060` (Notice the extra leading zero after mnc)

![image](https://github.com/herlesupreeth/docker_open5gs/assets/4115839/4df2f476-c6eb-4faa-8731-1517f15d62a6)

**Comment by kamgaarnold** [comment]
@herlesupreeth that got updated already. When I analysed the logs I did correct it.
But when making a complete call I need to provision another sim and try? Because I've been trying that but facing some difficulties

**Comment by herlesupreeth** [comment]
> But when making a complete call I need to provision another sim and try?

yes, without that you will receive 404 from IMS as it doesnt know the user you are trying to call

**Comment by herlesupreeth** [comment]
It does not matter, the other user must be registered at the IMS  in order for call to be successful. Please read refer to IMS material about how IMS works and how VoLTE calling works

**Comment by kamgaarnold** [comment]
@herlesupreeth ok thanks.
I'll do that ans keep you posted.

**Comment by kamgaarnold** [comment]
/home/volte1/Logs/01_07_2024_sipokfor113145/callfrom1003to113145_successful.pcapng
@herlesupreeth  some good new here. It is successful

**Comment by kamgaarnold** [comment]
<img width="690" alt="image" src="https://github.com/herlesupreeth/docker_open5gs/assets/171120720/f54ea02b-66e1-4a21-bc60-fdb5908ed8f1">

@herlesupreeth having some good news.
Thanks
