### ISSUE TITLE
Samsung VoNR/PLMN ID restrictions

### ISSUE THREAD

**Issue by driesken** [herlesupreeth/docker_open5gs#329]
Hello @herlesupreeth 

We're planning to request a 5G permit for our campus. The regulator offers the possibility to either use PLMN ID 206 90 / 206 91 or the regular 999 XX.

I've read somewhere that Samsung devices have restrictions regarding VoLTE support. Is VoNR also restricted as such?

Is this whitelisting/blacklisting based on the PLMN ID? Would requesting one based on my country (206 Belgium) have an advantage?

Best regards

**Comment by herlesupreeth** [comment]
Hey @driesken If it were to be me I would not use Samsung devices to test VoLTE/VoNR as there are no methods to force enable VoLTE/VoNR on those devices.

> I've read somewhere that Samsung devices have restrictions regarding VoLTE support. Is VoNR also restricted as such?

If VoLTE is not enabled then you can be sure that VoNR wont be enabled either

> Is this whitelisting/blacklisting based on the PLMN ID?

VoLTE/VoNR being enabled/disabled solely depends on the settings given to handset vendors by the operator who owns a PLMN ID

In case of Samsung devices, Samsung maintains a seperate list (apart from Google outlined settings) of settings to enable per operator which cant be overriden unless an Android app is a System app

**Comment by driesken** [comment]
Thanks for your advice. I'll look out for some recent Xiaomi/Oneplus models to try and validate with first. I do have access to a few Samsung models though.

> which cant be overriden unless an Android app is a System app

Could you clarify that a bit please? Would CoIMS on a rooted Samsung add some possibilities?

**Comment by herlesupreeth** [comment]
> Could you clarify that a bit please? Would CoIMS on a rooted Samsung add some possibilities?

Prior to Android 10, Samsung allowed calling up their IMS settings app from CoIMS but from Android 10 onwards only a system app is allowed to call IMS settings app. If the phone is rooted then you probably wont need CoIMS I guess, but I dont know how to force enable VoLTE/VoNR on a rooted phone

**Comment by driesken** [comment]
Thanks a lot @herlesupreeth!
