### ISSUE TITLE
how to configure the pyhss so my phone can be connected to internet or do sms

### ISSUE THREAD

**Issue by exkazuto** [herlesupreeth/docker_open5gs#331]
hello, so im new to this, my teacher ask me to install this docker_open5gs without telling me how, and only tell me to follow the steps on this github.

i've installed all of the requirements, im doing single host with 4g only, and now i can open the pyHSS web. so could you tell me what to do next after i do all of the steps, i've configured the apn ( for internet and ims),auc,subscriber,ims subsriber on pyHSS web. Now i dont know what to do next to connect my phone

thank you

**Comment by herlesupreeth** [comment]
Follow the README

1. First bring up the 4G Core along with IMS
2. Next start the eNB
3. Program a SIM card with the details you entered in pyHSS
4. Put that SIM in phone and try attaching

**Comment by exkazuto** [comment]
okay thank you, can i ask one more question

insted of pyHSS web, is there a way to enter open5gs HSS when i run this?

# 4G Core Network + IMS + SMS over SGs
docker compose -f 4g-volte-deploy.yaml up

**Comment by herlesupreeth** [comment]
you can access both at the same time 

```
# open5gs webui
http://<DOCKER_HOST_IP>:9999

# pyhss webui
http://<DOCKER_HOST_IP>:8080/docs/
```

**Comment by exkazuto** [comment]
okay thanks a lot
