### ISSUE TITLE
When docker-compose runs the root directory, an error is reported

### ISSUE THREAD

**Issue by zinopop** [herlesupreeth/docker_open5gs#34]
ERROR: for smf  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

ERROR: for pcrf  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

ERROR: for hss  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

How to solve this problem

**Comment by herlesupreeth** [comment]
Please post your docker and docker-compose version here

**Comment by zinopop** [comment]
> 请在此处发布您的docker和docker-compose版本

1.24.1

**Comment by zinopop** [comment]
> > 请在此处发布您的docker和docker-compose版本
> 
> 1.24.1

Resolved, is the reason for low version
