### ISSUE TITLE
 VONR with Open5GS 5G + Kamailio IMS 

### ISSUE THREAD

**Issue by ajaydas03** [herlesupreeth/docker_open5gs#356]
Hi Everyone,

Can anybody tell me, VONR is proper functioning with open5GS 5G and IMS, also how the connections need to make to make the successful call or registration.

Please tell me how the open5GS and IMS nodes are connected/linked, so i can also make the connection to test VONR.

Thanks

**Comment by herlesupreeth** [comment]
Its not completely ready yet. You can check out the pull requests where there is work being done.

**Comment by ajaydas03** [comment]
Thanks Supreeth.
