### ISSUE TITLE
APN Error "Unknown column 'nbiot' in 'field list"

### ISSUE THREAD

**Issue by MAlexVR** [herlesupreeth/docker_open5gs#360]
Dear all, I'm having trouble withthe latest repo update when I try to register a new APN:

{
  "result": "Failed",
  "reason": "A database operational error occurred: (MySQLdb.OperationalError) (1054, \"Unknown column 'nbiot' in 'field list'\")\n[SQL: INSERT INTO apn (apn_id, apn, ip_version, pgw_address, sgw_address, charging_characteristics, apn_ambr_dl, apn_ambr_ul, qci, arp_priority, arp_preemption_capability, arp_preemption_vulnerability, charging_rule_list, nbiot, nidd_scef_id, nidd_scef_realm, nidd_mechanism, nidd_rds, nidd_preferred_data_mode, last_modified) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]\n[parameters: (1, 'internet', 0, 'string', 'string', 'stri', 0, 0, 0, 0, 1, 1, 'string', 1, 'string', 'string', 0, 0, 0, '2024-08-19T20:31:40Z')]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)"
}

**Comment by herlesupreeth** [comment]
With the recent changes the schema for pyHSS DB has changed. So sadly you would have to drop the database and recreate it.

```
docker exec -ti mysql bash
mysql
drop database ims_hss_db;
```

then, stop all components and redeploy
