### ISSUE TITLE
UL Simulation Not Working..

### ISSUE THREAD

**Issue by YokeshwaranM2002** [herlesupreeth/docker_open5gs#369]
when i am trying UL IP simulation UE is sending the packets, But it is not receiving in the CN terminal.
CN:  iperf -s -u -i 1
UE: iperf -c 10.45.0.2 -u -t 30 -b 2M -i 1 -fm -B 127.0.0.1 -p 5001  [ UE IP address: 10.45.0.2, ENB IP address: 127.0.0.1 ].
I need UL and UL , DL  simultaneous simulation commands for iperf.

**Comment by YokeshwaranM2002** [comment]
![ue_iperf](https://github.com/user-attachments/assets/35901801-c4e0-437d-976c-866a24f50ee9)
![iperf](https://github.com/user-attachments/assets/8b3c7deb-a8d2-4543-82e8-d201af8c7389)
![ifconfig](https://github.com/user-attachments/assets/5dd24061-253b-4550-b4a1-56363adec929)
please, help me is this correct or not, commands for UL IP Simulation

**Comment by herlesupreeth** [comment]
First, please describe your setup in order to debug. Second, why is your ENB_IP 127.0.0.1. Are you running in another machine?

Also, attach take a pcap when you attach UE to ENB and post it here

**Comment by YokeshwaranM2002** [comment]
In single machine only both ENB and CN setup was done. MME IP: 127.0.0.2, UPF:127.0.0.7, SMF:127.0.0.4.
[logs.zip](https://github.com/user-attachments/files/17014832/logs.zip)

**Comment by YokeshwaranM2002** [comment]
DL Simulation is working.
 DL : EPC -> iperf -c 10.45.0.21 -t300 -u -b 70M
        UE ->    iperf -B 10.45.0.21 -u -s -i 1 -fm -p 5001
i need to know for which entity or interface (IP) i need to send the packet from UE
