### ISSUE TITLE
VOLTE on openstack

### ISSUE THREAD

**Issue by modyngs** [herlesupreeth/docker_open5gs#37]
Dear @herlesupreeth 
Hi,

internet access problem was solved as in here https://github.com/herlesupreeth/docker_open5gs/issues/33#issuecomment-846935267 

So now UE Connects to the Network and has internet access, and also try to connect to IMS network
But Volte is not accessible!
can you please kindly check this?

Setup is as follows:
```
     UE            =====>>>>>>       SRSLTE    ===>>> ISP DHCP IP add. ===>>>     OPENSTACK (Floating)     ==>>>   VM
192.168.100.2       =====>>>>>>  192.168.1.3  ===>>>     5.74.x.x            ===>>>    46.102.143.93  ==>>>      10.10.10.78

```
Logs_pcap_confs:
[RAN.zip](https://github.com/herlesupreeth/docker_open5gs/files/6531421/RAN.zip)
[EPC.zip](https://github.com/herlesupreeth/docker_open5gs/files/6531471/EPC.zip)

**Comment by modyngs** [comment]
is there sth wrong between ICSCF and PCSCF?

**Comment by modyngs** [comment]
When i send SIP request from UE
PCRF warning appear

pcrf         | 05/25 16:17:01.985: [pcrf] WARNING: Not supported(260) (../src/pcrf/pcrf-rx-path.c:364)
pcrf         | 05/25 16:17:01.986: [pcrf] WARNING: Not supported(524) (../src/pcrf/pcrf-rx-path.c:353)
pcrf         | 05/25 16:17:01.986: [pcrf] WARNING: Not supported(524) (../src/pcrf/pcrf-rx-path.c:353)
pcrf         | 05/25 16:17:01.986: [pcrf] WARNING: Not supported(511) (../src/pcrf/pcrf-rx-path.c:353)
pcrf         | 05/25 16:17:01.986: [pcrf] WARNING: Not supported(291) (../src/pcrf/pcrf-rx-path.c:364)
pcrf         | 05/25 16:17:01.986: [pcrf] WARNING: Not supported(276) (../src/pcrf/pcrf-rx-path.c:364)
pcrf         | 05/25 16:17:01.986: [pcrf] WARNING: Not supported(27) (../src/pcrf/pcrf-rx-path.c:364)
pcscf        | 94(127) INFO: cdp [authstatemachine.c:270]: auth_client_statefull_sm_process(): after callback of event 7
p

**Comment by herlesupreeth** [comment]
> pcrf | 05/25 16:17:01.985: [pcrf] WARNING: Not supported(260) (../src/pcrf/pcrf-rx-path.c:364)
> pcrf | 05/25 16:17:01.986: [pcrf] WARNING: Not supported(524) (../src/pcrf/pcrf-rx-path.c:353)
> pcrf | 05/25 16:17:01.986: [pcrf] WARNING: Not supported(524) (../src/pcrf/pcrf-rx-path.c:353)
> pcrf | 05/25 16:17:01.986: [pcrf] WARNING: Not supported(511) (../src/pcrf/pcrf-rx-path.c:353)
> pcrf | 05/25 16:17:01.986: [pcrf] WARNING: Not supported(291) (../src/pcrf/pcrf-rx-path.c:364)
> pcrf | 05/25 16:17:01.986: [pcrf] WARNING: Not supported(276) (../src/pcrf/pcrf-rx-path.c:364)
> pcrf | 05/25 16:17:01.986: [pcrf] WARNING: Not supported(27) (../src/pcrf/pcrf-rx-path.c:364)

These are warning logs, which you can safely ignore

**Comment by herlesupreeth** [comment]
> is there sth wrong between ICSCF and PCSCF?

I dont see any diameter message exchange between fhoss and I,S-CSCF in the trace attached
