### ISSUE TITLE
srsRAN setup tutorial not compatible 

### ISSUE THREAD

**Issue by JelleB-2055020** [herlesupreeth/docker_open5gs#370]
Is the 'srsRAN gNB with srsUE' tutorial on their website (https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#) compatible with this repo? I can't seem to get the 'ZeroMQ-based setup' part of the tutorial working. There is a clear difference in the ip addresses they use and I can't find to which IP addresses in this repo they should map. Adding the network namespaces to the UE using the compose file also gives broken routing etc. (but I assume its due to the ips not matching correctly)

Is it even necessary to do that setup part? I actually assumed the repo would have handled all these things and it would be plug 'n play from then on. 

Thanks!
-Total noob trying to learn about srsRAN and Open5GS

**Comment by herlesupreeth** [comment]
> Is it even necessary to do that setup part? I actually assumed the repo would have handled all these things and it would be plug 'n play from then on.

ZMQ setup in this repo should work as is mentioned in README. You shouldn't have to do any modification

If you are still facing issues then please post the logs of srsRAN and a pcap

**Comment by JelleB-2055020** [comment]
Yes, the setup works if I just run it as provided in the README. However, in order to 'use' the UE (e.g. make the UE do a ping to 8.8.8.8 for example), the srsRAN docs seem to require that you use a separate network namespace which as far as I can tell is not present in this repo. That's why I was following that tutorial. However, due to difference between the IPs they use and the way this repo is set up, I can't seem to get this working. 

So really, my question is whether that netns setup is needed and you seem to indicate it isn't. I can thus safely assume that if i run something on the UE, it passes through the 5G network?

**Comment by herlesupreeth** [comment]
> However, in order to 'use' the UE (e.g. make the UE do a ping to 8.8.8.8 for example), the srsRAN docs seem to require that you use a separate network namespace which as far as I can tell is not present in this repo.

Ah, you dont need a separate namespace because docker itself acts as separate namespace. All you need to do is `ping 8.8.8.8 -I ue_interface_name`

If you are using iperf you can use the option `-B` to provide the IP of the interface to use

**Comment by JelleB-2055020** [comment]
Ohh thank you, I get it now. Thanks so much!
