### ISSUE TITLE
No UE_AMBR information

### ISSUE THREAD

**Issue by ljysdfz** [herlesupreeth/docker_open5gs#38]
![image](https://user-images.githubusercontent.com/3489980/119853612-effcc900-bf42-11eb-8c7a-4a1bebc5ac63.png)
![image](https://user-images.githubusercontent.com/3489980/119853761-0dca2e00-bf43-11eb-9faf-cef119e37e77.png)

Hi~ Dude, long time no see.
I've just installed the latest docker_open5gs
I figured that the registration between the UE and gNB had broken down.
The most possible cause is that the UE_AMBR info has not been filled.
But I'm not aware why it has not been configured.
The former versions I've been using have got a complete UE profile.
Could you help me tackle this problem?

**Comment by herlesupreeth** [comment]
With using the latest upstream code of open5gs, the DB schema changed so I would suggest to bring down the stack and execute the following command to drop the volume (Beware below command will wipe out your UE information in open5gs)

`docker volume rm docker_open5gs_mongodbdata`

 then, try running the stack again. Add UE details and try attaching

**Comment by ljysdfz** [comment]
@herlesupreeth 
Thank you buddy
Could you show me an available tag without this shortcoming？

**Comment by herlesupreeth** [comment]
I you want to use an older open5gs tag, then please checkout the older tag in base/Dockerfile , i believe DB schema changed in v2.2.0 tag, then re-compile base image and components

https://github.com/herlesupreeth/docker_open5gs/blob/021a71bbe78d1433f29bb12cf91359efc53a5589/base/Dockerfile#L64
