### ISSUE TITLE
Restrictions on MSISDN

### ISSUE THREAD

**Issue by modyngs** [herlesupreeth/docker_open5gs#39]
Hi,

Is there any restriction on MSISDN to be set For FOHSS or Cx interface?
Ex. Length, first Numbers, ...

Suppose PLMN is "65432"
654 is MCC and 32 in MNC

is there any relation Between PLMN and MSISDN For your Dockerized instruction?
Should it be "01" in the beginning? or we can use "98741" for MSISDN?

Thanks 
Best regards

**Comment by herlesupreeth** [comment]
Please read the 3gpp specification. There is no relation between PLMN and MSISDN, as far as I remember there is a limit on length (10 digit or something). It need not start with 0

**Comment by modyngs** [comment]
Thanks 

According to http://www.3gpp.org/wiki/index.php?title=Current%20Capacity%20of%20IMSI%2C%20MSISDN%2C%20and%20IPv6%20Identifiers 

The MSISDN is also 15 digits. The Country Code is 1 to 3 digits, and the National Destination Code (NDC) and Subscriber Number (SN) together are 12 to 14 digits. So again, the MSISDN could contain the 12 digits needed for MTC.

Best regards
