### ISSUE TITLE
SA VoNR docker won't start after setting up AMF ports

### ISSUE THREAD

**Issue by Stromduster** [herlesupreeth/docker_open5gs#390]
I'm trying to use the sa-vonr-deploy branch, in use with an external gNodeB (ORS68 from Rapidspace). Following the tutorial, i uncommented the below lines about ports on AMF and UPF:
![Capture du 2024-11-18 13-46-18](https://github.com/user-attachments/assets/58a60c6a-aa6c-44a7-a6b4-4c0c2734fb24)

Afterwards, the docker launch ends with a parsing error : 
test@lab5G-open5GS:~/docker_open5gs$ sudo docker-compose -f sa-vonr-deploy.yaml up
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./sa-vonr-deploy.yaml", line 197, column 5
expected <block end>, but found '<block mapping start>'
  in "./sa-vonr-deploy.yaml", line 220, column 6

If I skip this part, the dockers will start, but it results in the AMF aborting all SCTP INIT attempts from the gNodeB : 
![Capture du 2024-11-18 13-57-51](https://github.com/user-attachments/assets/0879c784-8567-4200-a4ef-0ee79cc5ca14)

Could someone give me a clue about how getting it to work ? Thanks in advance.

**Comment by herlesupreeth** [comment]
Can you post here the sa-vonr-deploy.yaml you modified ? Also, can you let me know the docker-ce and docker compose version you are running?

**Comment by Stromduster** [comment]
Hi @herlesupreeth. The requested docker version : 
cogisys@lab5G-open5GS-fork:~/docker_open5gs$ docker --version
Docker version 24.0.7, build 24.0.7-0ubuntu2~22.04.1

cogisys@lab5G-open5GS-fork:~/docker_open5gs$ docker compose version
Docker Compose version v2.3.3

And the sa-vonr-deploy.yaml in attachment.
[sa-vonr-deploy.yaml.txt](https://github.com/user-attachments/files/17827682/sa-vonr-deploy.yaml.txt)

**Comment by herlesupreeth** [comment]
The indentation of "ports" section under amf and upf is wrong. Please align it (yaml files are very sensitive to spaces)

**Comment by Stromduster** [comment]
Thanks for the information, I didn't know it was space-senstive. I tried again with a copy/paste from the repo, and I had the same issue. 
Howerver, I was able to make it work : there is an extra space between the sharp character and "ports" in the sa-vonr-deploy.yaml from the repo. I removed it and it starts.

Thanks again for your help.
