### ISSUE TITLE
MySQL database integrity error when adding a subscriber with pyHSS

### ISSUE THREAD

**Issue by Stromduster** [herlesupreeth/docker_open5gs#395]
I'm using the sa-vonr-deploy.yaml, with an Ubuntu 20.04 host, docker 27.3.1 and docker compose v2.29.7. When trying to add a subscriber with the pyHSS WebUI (http://@IP:8080/docs/), I've got a database integrity error : 
400 Bad request : 
{
  "result": "Failed",
  "reason": "A database integrity error occurred: (MySQLdb.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`ims_hss_db`.`subscriber`, CONSTRAINT `subscriber_ibfk_1` FOREIGN KEY (`auc_id`) REFERENCES `auc` (`auc_id`))')\n[SQL: INSERT INTO subscriber (imsi, enabled, auc_id, default_apn, apn_list, msisdn, ue_ambr_dl, ue_ambr_ul, nam, roaming_enabled, roaming_rule_list, subscribed_rau_tau_timer, serving_mme, serving_mme_timestamp, serving_mme_realm, serving_mme_peer, last_modified) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]\n[parameters: ('001010000000985', 1, 1, 1, '1,2', '0600000985', 0, 0, 0, 1, None, 300, None, None, None, None, '2024-11-22T14:56:04Z')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)"
}

I noticed i've got many errors regarding access to the MySQL DB at docker launch : 
pcscf      |  1(44) ERROR: db_mysql [km_my_con.c:217]: db_mysql_new_connection(): driver error: Access denied for user 'pcscf'@'pcscf.docker_open5gs_default' (using password: YES)

Did I miss something on setup ?

Edit : I did miss something : auc_id. Still curious about the pcscf error.

**Comment by herlesupreeth** [comment]
> 400 Bad request :
> {
> "result": "Failed",
> "reason": "A database integrity error occurred: (MySQLdb.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (ims_hss_db.subscriber, CONSTRAINT subscriber_ibfk_1 FOREIGN KEY (auc_id) REFERENCES auc (auc_id))')\n[SQL: INSERT INTO subscriber (imsi, enabled, auc_id, default_apn, apn_list, msisdn, ue_ambr_dl, ue_ambr_ul, nam, roaming_enabled, roaming_rule_list, subscribed_rau_tau_timer, serving_mme, serving_mme_timestamp, serving_mme_realm, serving_mme_peer, last_modified) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]\n[parameters: ('001010000000985', 1, 1, 1, '1,2', '0600000985', 0, 0, 0, 1, None, 300, None, None, None, None, '2024-11-22T14:56:04Z')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)"
> }


Most likely the database schema changed I guess. Did you update (pull latest commits) recently?

> I noticed i've got many errors regarding access to the MySQL DB at docker launch :
> pcscf | 1(44) ERROR: db_mysql [km_my_con.c:217]: db_mysql_new_connection(): driver error: Access denied for user 'pcscf'@'pcscf.docker_open5gs_default' (using password: YES)

Did pcscf run correctly even after those error or the container stopped?

**Comment by Stromduster** [comment]
> > 400 Bad request :
> > {
> > "result": "Failed",
> > "reason": "A database integrity error occurred: (MySQLdb.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (ims_hss_db.subscriber, CONSTRAINT subscriber_ibfk_1 FOREIGN KEY (auc_id) REFERENCES auc (auc_id))')\n[SQL: INSERT INTO subscriber (imsi, enabled, auc_id, default_apn, apn_list, msisdn, ue_ambr_dl, ue_ambr_ul, nam, roaming_enabled, roaming_rule_list, subscribed_rau_tau_timer, serving_mme, serving_mme_timestamp, serving_mme_realm, serving_mme_peer, last_modified) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]\n[parameters: ('001010000000985', 1, 1, 1, '1,2', '0600000985', 0, 0, 0, 1, None, 300, None, None, None, None, '2024-11-22T14:56:04Z')]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)"
> > }
> 
> Most likely the database schema changed I guess. Did you update (pull latest commits) recently?
> 
> > I noticed i've got many errors regarding access to the MySQL DB at docker launch :
> > pcscf | 1(44) ERROR: db_mysql [km_my_con.c:217]: db_mysql_new_connection(): driver error: Access denied for user 'pcscf'@'pcscf.docker_open5gs_default' (using password: YES)
> 
> Did pcscf run correctly even after those error or the container stopped?

I'll pull the last commit. Plus, I was not on the right branch.

The container has stopped, I can't find it with docker ps command (I-CSCF and S-CSCF container have started though).

**Comment by herlesupreeth** [comment]
Then, I would suggest pasting here the entire log when you try to deploy the containers

**Comment by Stromduster** [comment]
I guess it's related to https://github.com/herlesupreeth/docker_open5gs/issues/396
