### ISSUE TITLE
Starting dns       ... error

### ISSUE THREAD

**Issue by Sningi** [herlesupreeth/docker_open5gs#4]
╰─ docker-compose up                 
Starting pgw ... 
Starting mysql ... 
Starting sgw   ... 
Starting rtpengine ... 
Starting dns       ... error
Starting pgw       ... done
Starting mysql     ... done
Starting sgw       ... done
Starting rtpengine ... done
7a819cf68f10b4a405c7150d45a40754553585bc50a6631d8c975105606d1/merged/etc/timezone" caused: not a directory: unknown: Are you tryinStarting mongo     ... done
Starting hss       ... done
Starting pcrf      ... done
Starting mme       ... done

ERROR: for dns  Cannot start service dns: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/etc/timezone" to rootfs at "/var/lib/docker/overlay2/4857a819cf68f10b4a405c7150d45a40754553585bc50a6631d8c975105606d1/merged/etc/timezone" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by herlesupreeth** [comment]
Which OS are you using? I am trying to set the time same as the host machine running the container

**Comment by Sningi** [comment]
OS:  Arch Linux  
Kernel:  x86_64 Linux 5.8.6-arch1-1 
Uptime:  1m 
Packages:  783 
Shell:  zsh 5.8 
Disk:  77G / 230G (35%) 
CPU:  AMD Ryzen 7 3700X 8-Core @ 16x 3.6GHz 
GPU:  GeForce RTX 2060 SUPER 
RAM:  688MiB / 32121MiB

**Comment by herlesupreeth** [comment]
Please remove the following lines wherever you find in docker-compose.yaml and srsenb.yaml  

```
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

**Comment by herlesupreeth** [comment]
Will close the issue as the above fix should solve this issue, please feel free to re-open if you face further issues
