### ISSUE TITLE
General Troubleshooting 

### ISSUE THREAD

**Issue by BryanCoxwell** [herlesupreeth/docker_open5gs#40]
Hi,

I'm having trouble getting anything to register to the IMS and I'm still trying to narrow down what the issue could be. I've tried a Samsung S20, a few Samsung S9's, and an iPhone X and one thing I've noticed is that none of the phones even send a SIP register message. Is it safe to assume then that the issue is somewhere between the UE and the eNodeB?

I'm using an external eNodeB with all docker containers running on one machine. The MME's S1 port is published to the host and I don't have any problems getting phones to attach to the network, it's just that once they do they never attempt to register to the IMS. 

I've also used the CoIMS app for the Samsungs and it seems to be working properly (it reports having carrier privileges). 

Attached is a PCAP of the attach process. Thanks in advance, any help would be greatly appreciated.

[open5gs_pcap.pcapng.log](https://github.com/herlesupreeth/docker_open5gs/files/6583398/open5gs_pcap.pcapng.log)

**Comment by herlesupreeth** [comment]
Hi Bryan,

On the Samsung it can be a bit tricky, however on the iphone X IMS registration should definitely work.

Can you make you have VoLTE enabled on iPhone X in the following menu?

`Settings--> Mobile Data Options -->Voice & Data --> (VoLTE Enabled)`

Even after enabling if it doesnt work. Then try restarting the phone and then attempt to attach again

**Comment by BryanCoxwell** [comment]
Hi Supreeth, thanks for getting back to me.

VoLTE is enabled and I tried a few restarts to try to get it to attach and it's still not attaching. I'm going to try to reprogram the SIM then give it another shot. 

I'm looking through the packet capture though and in the E-RABSetupRequest, Activate default EPS Bearer context request it's showing primary and secondary DNS's of 8.8.8.8 and 8.8.4.4. Shouldn't that be set to the IP of the DNS docker container?

**Comment by herlesupreeth** [comment]
If you are seeing the following the that means phone is indeed trying to connect to 'ims'. Please send the pcap for this. Regarding DNS its totally fine

> I'm looking through the packet capture though and in the E-RABSetupRequest, Activate default EPS Bearer context

**Comment by BryanCoxwell** [comment]
Well that's good news then. I took a PCAP of the iphone attach procedure and also included the logs from the containers. Nothing really jumps out at me as being wrong. I checked and confirmed that none of the containers had crashed so that can be ruled out at least. It looks like it gets through the E-RAB setup okay and then just stops. Is there something else I'm missing?

Thanks as always for your help!
[Iphone_attach.zip](https://github.com/herlesupreeth/docker_open5gs/files/6590019/Iphone_attach.zip)

**Comment by herlesupreeth** [comment]
Alright, I saw the trace you attached and you are right. iPhone didnt send SIP Register. This happens usually when there are too many repeated failed attempts at registering to IMS. I would suggest to restart the iPhone and then try re-attaching

**Comment by herlesupreeth** [comment]
Btw, can you send me the trace without filtering?

**Comment by BryanCoxwell** [comment]
Hi, thanks for taking a look. I reran the test with the same setup and attached the PCAP without filtering. 

I _think_ this may be a SIM card issue and unrelated to Open5GS or Kamailio or FHoSS. It looks like my SIM cards (Sysmocom SJA2) doesn't actually have the ISIM application. I'm going to try to play around with the settings in the USIM application and see what happens, but it seems like that would cause the phone to not even attempt an IMS registration, correct?

Thanks again for your help!
[IphoneAttach6.10.zip](https://github.com/herlesupreeth/docker_open5gs/files/6629331/IphoneAttach6.10.zip)

**Comment by herlesupreeth** [comment]
Sysmocom SJA2 has an ISIM application, but in order to activate it you need to program the bare minimum EFs in ISIM

P-CSCF address, IMPI, IMPU, Domain.

Btw, the attached zip file didnt contain the pcap

**Comment by BryanCoxwell** [comment]
I'm having trouble uploading the file for some reason. But if that is the case and the SIM needs the P-CSCF address, IMPI, IMPU, and Domain then I assume that's the issue. For some reason the SJA2 cards don't list the ISIM application when I run sysmoISIM-tool, and pySim-shell doesn't let me select ADF.ISIM (gives an "unknown file" error). 

But since that's unrelated to Open5GS I'm going to close this issue. Appreciate the help though!
