### ISSUE TITLE
VONR:The Real UEs AND Real gNB show a successful registration, and SMSoIP works fine.But The Real UEs call do not complete.

### ISSUE THREAD

**Issue by jiangfeiyu1314** [herlesupreeth/docker_open5gs#403]
Hi @herlesupreeth,

Thank you for the wonderful setup and guides. 
The Real UEs show a successful registration, and SMSoIP works fine.But The Real UEs call do not complete.

REAL UES : honor v30,band N79
Error:SIP Status 580 Precondition Failure

Would you please help me solve this problem?
Thanks
Best regards
[sa-vonr-deploy&gnb_pcap.zip](https://github.com/user-attachments/files/18273223/sa-vonr-deploy.gnb_pcap.zip)

![图片](https://github.com/user-attachments/assets/d211f3a7-c4fb-491f-acd9-0c23a830c771)

**Comment by NUCLEAR-WAR** [comment]
@jiangfeiyu1314 I dont see any QoS Requests from the P-CSCF in your trace, can you verify if you are using the correct experimental branch ? after cloning you need to manually switch to "exp_5g_ims_pyhss" branch.

**Comment by jiangfeiyu1314** [comment]
@NUCLEAR-WAR I manually switched to "exp_5g_ims_pyhss" branch,The Real UEs call  complete,Thank you!
