### ISSUE TITLE
About mysql max connections

### ISSUE THREAD

**Issue by bluehat-f** [herlesupreeth/docker_open5gs#42]
In mysql container, mysql max connections num is shown as 151.  But I notice that there is a cmd(mysql -u root -e "SET GLOBAL max_connections=200;") in "mysql_init.sh". The max connections num should be set to 200. What's wrong?
![image](https://user-images.githubusercontent.com/84237986/124739516-82ce5180-df4c-11eb-8f06-b5763c95d5a1.png)

![image](https://user-images.githubusercontent.com/84237986/124740857-bfe71380-df4d-11eb-9a20-195c8765aa8b.png)

**Comment by herlesupreeth** [comment]
@bluehat-f Thanks for bringing this up.. Will fix that..everytime mysql is restarted it resets back to default value

**Comment by herlesupreeth** [comment]
It been fixed in most recent commit, please re-compile mysql alone and give it a try

**Comment by bluehat-f** [comment]
Thanks Supreeth's quick feedback. 
Unfortunately, the file "/etc/mysql/mysql.conf.d/mysqld.cnf" in my environment seems a little different. I use ubuntu18.04 and mysql 5.7.33, the setting line is "#max_connections        = 100".

![image](https://user-images.githubusercontent.com/84237986/124750225-cbd7d300-df57-11eb-8a64-d126af1f8909.png)

**Comment by herlesupreeth** [comment]
You use add the following line to mysql_init.sh file as follows in the below mentioned sections

```
...
sed -i "s/127.0.0.1/0.0.0.0/g" /etc/mysql/mysql.conf.d/mysqld.cnf
sed -i "s/# max_connections        = 151/max_connections        = 250/g" /etc/mysql/mysql.conf.d/mysqld.cnf

echo 'max_connections=250' >>

cat > ~/.my.cnf <<EOF
[mysql]
user=root
password=ims
EOF
...
```

**Comment by bluehat-f** [comment]
Got it. Thanks.
