### ISSUE TITLE
Docker compose failing

### ISSUE THREAD

**Issue by EmanueleGallone** [herlesupreeth/docker_open5gs#44]
Hi,
I tried using your docker-compose setup within a VM;
And it just hangs on 
`
scscf     |DEBUG: ims_dialog [dlg_handlers.c:1923]: print_all_dlgs(): ******************** 5(48) DEBUG: ims_dialog [dlg_handlers.c:1924]: print_all_dlgs(): printing 4096 dialogs
scscf        |  5(48) DEBUG: ims_dialog [dlg_handlers.c:1934]: print_all_dlgs(): ******************** 5(48) DEBUG: ims_auth [authorize.c:187]: reg_await_timer(): Looking for expired/useless at 79562467
scscf        |  5(48) DEBUG: ims_auth [authorize.c:232]: reg_await_timer(): [DONE] Looking for expired/useless at 79562467
[...]
` printing this statement every 10 seconds (see the tail of the log, below).

This is the entire log file (Very long): [free5gs_log.txt](https://github.com/herlesupreeth/docker_open5gs/files/6872272/free5gs_log.txt)

I can see some anomalies:

- Line 3507 (Cannot stat file /proc/226/fd/0: Permission denied) regarding mysql
- Line 9293 (scscf ERROR: cdp [receiver.c:922]: peer_connect(): peer_connect(): Error opening connection to to 172.22.0.18 port 3868 >Connection refused)
- Line 9583 (Exception in FHOSS)

**Comment by herlesupreeth** [comment]
> scscf |DEBUG: ims_dialog [dlg_handlers.c:1923]: print_all_dlgs(): ******************** 5(48) DEBUG: ims_dialog [dlg_handlers.c:1924]: print_all_dlgs(): printing 4096 dialogs scscf | 5(48) DEBUG: ims_dialog [dlg_handlers.c:1934]: print_all_dlgs(): ******************** 5(48) DEBUG: ims_auth [authorize.c:187]: reg_await_timer(): Looking for expired/useless at 79562467 scscf | 5(48) DEBUG: ims_auth [authorize.c:232]: reg_await_timer(): [DONE] Looking for expired/useless at 79562467 [...] printing this statement every 10 seconds (see the tail of the log, below).

Those are debug logs and not errors

I believe from the logs the setup is ready. Only if you post a pcap then I can tell whether all components came up as expected or not

**Comment by EmanueleGallone** [comment]
You're right. I don't get why it doesn't return the control by adding the `-d` flag though.
By using new shells I can setup the gnb and the UE. The only thing missing is to add the UE information within the HSS.

Can you confirm that I just need to add the following data to the mongodb?
```
UE1_IMSI=001011234567895
UE1_KI=8baf473f2f8fd09487cccbd7097c6862
UE1_OP=11111111111111111111111111111111
```

**Comment by herlesupreeth** [comment]
> Can you confirm that I just need to add the following data (described in .env file) to the mongodb?

I would suggest to add them via open5gs WebUI, its accessible via the host ip of machine running the core network at port 3000. And, yes those are the credentials needed to be added in order for you to use UERANSIM UE

**Comment by EmanueleGallone** [comment]
Yes I'm using the WebUI, but still, it returns the Network failing authentication check


gnb: 
![immagine](https://user-images.githubusercontent.com/26747011/126893813-f9c69783-4026-420c-a6aa-9d572592548c.png)


UE:
![immagine](https://user-images.githubusercontent.com/26747011/126893830-9b19ca33-3122-4e06-a734-3971873b2a9b.png)

**Comment by herlesupreeth** [comment]
You inserted the OP value with USIM  type set to OPc.

OP and OPc are two different things, change the value of USIM Type in open5gs WebUI to OP

**Comment by EmanueleGallone** [comment]
Thank you. Now it works. Closing!
