### ISSUE TITLE
[Question] Add more UEs

### ISSUE THREAD

**Issue by EmanueleGallone** [herlesupreeth/docker_open5gs#45]
Hi,
Using the non-docker instance of open5GS and UERANSIM you can define more UEs using, for example:
` nr-ue -c config/open5gs-ue.yml -n 3`

 Do you know how to use this feature using this docker setup?

**Comment by herlesupreeth** [comment]
yes, append -n 3 or how many ever UEs you want in the following section

https://github.com/herlesupreeth/docker_open5gs/blob/9f0cbb7a99a6442962373f79f41dd23689de67d8/ueransim/ueransim_image_init.sh#L39

Then, recompile UERANSIM docker image
