### ISSUE TITLE
VoLTE calls muted and dropped after 15 minutes

### ISSUE THREAD

**Issue by hygorjardim** [herlesupreeth/docker_open5gs#46]
First of all, thank you very much for sharing your repository and for your dedication to updating it and also answering several questions about it.

I'm having some problems during VoLTE calls, as far as I could read in the Issues reported it looks like a bad configuration of my environment. Any comments will be greatly appreciated.

### My Environment

- **Docker Version:** 20.10.7, build f0df350
- **Compose Version:** 1.29.2, build 5becea4c
- **Branch docker_open5gs:** master
- **Deployment Environment:** Xeon(R) Gold 6240, hyperthreading disabled, bare-metal
- **Kernel:** 5.8.0-59-lowlatency
- **Core and RAN at same machine**

### Describe the Issue

I'm having several issues related to radio instability using srsRAN with USRP's, so I increased tx/rx_gain in enb.conf and change from EARFCN to 2460 in an attempt to be more stable, but it didn't work.

Even with the unstable environment on the RAN side, devices can make Attach, PDN's requests for `internet` and `ims` as well as register and invites to Fhoss.

Call invitations are received on both devices, but without audio and with a limited duration.

**To Reproduce**
1. docker-compose up -d dns mongo webui hss sgwc sgwu smf upf nrf mme pcrf rtpengine mysql  fhoss icscf scscf pcscf
2. Create profile, subscribers and APN with PCC in HSS (https://github.com/herlesupreeth/docker_open5gs/issues/15#issuecomment-759208730)
3. Create IMSU, IMPI and IMPU's to both subscribers
4. Make a call after Attach procedure and IMS register

**Expected behavior**
VoLTE with audio lasting 1h or more as reported in https://github.com/herlesupreeth/docker_open5gs/issues/7#issuecomment-717229399

**Screenshots**
![volte-call-drops-15min](https://user-images.githubusercontent.com/19941789/127780752-97b7feda-b444-437d-97b9-b81c5cbab537.jpg)

**Erros and doubts**
1. I noticed an error in rtpengine related to the kernel I'm using, what would be the suggested version for this application?
``` log
modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/5.8.0-59-lowlatency
exec rtpengine --interface=172.22.0.16 --listen-ng=172.22.0.16:2223 --listen-cli=172.22.0.16:9901 --pidfile=/run/ngcp-rtpengine-daemon.pid --port-min=49000 --port-max=50000 --table=0 --tos=184 --foreground
[1627773637.447521] ERR: [core] FAILED TO CREATE KERNEL TABLE 0 (No such file or directory), KERNEL FORWARDING DISABLED
```
2. I didn't run all the elements of docker-compose.yaml, what elements would be needed for IMS/VoLTE?

**Logs**
Here some pcaps, sorry if all logs are not present, the next test will try to include the others.
[6-test-volte-call-correct-qci-arp.zip](https://github.com/herlesupreeth/docker_open5gs/files/6913169/6-test-volte-call-correct-qci-arp.zip)

**Comment by herlesupreeth** [comment]
Hi there,

Can you please take a single pcap on the machine where you are running docker_open5gs, then attempt to attach UEs and try a call?it would help me in narrowing the issue.

**Comment by herlesupreeth** [comment]
> I noticed an error in rtpengine related to the kernel I'm using, what would be the suggested version for this application?

You can ignore those errors, its just that RTPEngine will run in user space when kernel forwarding is not available

> I didn't run all the elements of docker-compose.yaml, what elements would be needed for IMS/VoLTE?

I think no other components are required

**Comment by hygorjardim** [comment]
Hi, thanks for the reply.

Today I had several interference issues on the RAN side and I am moving some of the equipment to a RF isolated room, as soon as possible I will attach the pcaps.

**Comment by hygorjardim** [comment]
### My Environment

- **Docker Version:** 20.10.7, build f0df350
- **Compose Version:** 1.29.2, build 5becea4c
- **Branch docker_open5gs:** master
- **Deployment Environment:** Xeon(R) Gold 6240, hyperthreading disabled, bare-metal
- **Kernel:** 5.8.0-59-lowlatency
- **Core and RAN at same machine**
- **srsRAN** EARFCN  2460
### Describe the Issue

I restarted the server and the devices and repeated the test a few times, tests 16 and 17 are some tests that gave some kind of connection failure, test 18 was where I succeeded in establishing the VoLTE call lasting only 28 seconds .

### Tests and logs 

Nº | MO/MT | Antenna | VoLTE | Log
-- | -- | -- | -- | --
16  | sip:001010000034312 to sip:001010000034313 | Log-periodic | Failure | [test-16.pcap](https://github.com/herlesupreeth/docker_open5gs/files/6927082/serverone-test-16.pcap.zip)
17  | sip:001010000034312 to sip:001010000034313 | Log-periodic | Failure | [test-17.pcap](https://github.com/herlesupreeth/docker_open5gs/files/6927235/serverone-test-17.pcap.zip)
18  | sip:001010000034312 to sip:001010000034313 | Omnidirectional | Success | [test-18.pcap](https://github.com/herlesupreeth/docker_open5gs/files/6927315/serverone-test-18.pcap.zip)

Any comments will be greatly appreciated.

**Comment by hygorjardim** [comment]
I have a question about SQN, until a few versions ago I needed to manually copy from the hss webui to the IMPI form in fhoss. I noticed that this information is now filled in automatically. What was the change?

**Comment by herlesupreeth** [comment]
For the case of test-16.pcap, i suspect your eNB link at issue as the INVITE was sent to called party but no response after that. So technically the call was not established at all
![image](https://user-images.githubusercontent.com/4115839/128457974-42cf72ca-1cf3-4d63-bbd2-4a068bfde773.png)


Same is the case for test-17.pcap

![image](https://user-images.githubusercontent.com/4115839/128458089-9f42ebb8-b54f-4806-9db6-05f53a339fa7.png)

In test-18.pcap, you did not attempt to place a call

> I have a question about SQN, until a few versions ago I needed to manually copy from the hss webui to the IMPI form in fhoss. I noticed that this information is now filled in automatically. What was the change?

The fix is that Fhoss just accepts the SQN sent by UE in case of an SQN mismatch
