### ISSUE TITLE
ENB running outside docker machine and SIP REGISTER not initiated from UE

### ISSUE THREAD

**Issue by rajkumarv-bcw** [herlesupreeth/docker_open5gs#47]
VOLTE register and call was successfully established if I run the SRSENB and DOCKER in the same machine. SIP REGISTER message is not initiated if i run the SRSENB in another machine 

SRSENB                     : 192.168.168.81
DOCKER MACHINE IP: 192.168.168.7

Attaching the PCAP. Kindly help of this 
[docker_enb_NOSIP.zip](https://github.com/herlesupreeth/docker_open5gs/files/6923680/docker_enb_NOSIP.zip)

**Comment by herlesupreeth** [comment]
Paste here your .env contents

**Comment by rajkumarv-bcw** [comment]
> Paste here your .env contents

[env.zip](https://github.com/herlesupreeth/docker_open5gs/files/6923943/env.zip)

**Comment by herlesupreeth** [comment]
```
# UPF
UPF_IP=172.23.0.8
UPF_ADVERTISE_IP=192.168.168.7
```

This is wrong, since you are using only 4G/4G-5G Hybrid Core, UPF_ADVERTISE_IP should be same as UPF_IP i.e.

```
# UPF
UPF_IP=172.23.0.8
UPF_ADVERTISE_IP=172.23.0.8
```

**Comment by rajkumarv-bcw** [comment]
Thanks for the quick help. I'll change this configuration

**Comment by rajkumarv-bcw** [comment]
Steps followed: 
Changed the .env (UPF_ADVERTISE_IP=172.23.0.8) 
set -a
source .env
docker-compose -f nsa-deploy.yaml build --no-cache
docker-compose build --no-cache dns mysql pcscf scscf icscf
docker system prune -f
docker-compose up

UE initiates REGISTER and not failed to find scscf. Attaching the PCAP 
[scscf_fwd_error.zip](https://github.com/herlesupreeth/docker_open5gs/files/6924298/scscf_fwd_error.zip)

scscf        |  5(42) DEBUG: ims_auth [authorize.c:232]: reg_await_timer(): [DONE] Looking for expired/useless at 113147362
pcscf        | 104(140) NOTICE: <script>: PCSCF: REGISTER sip:ims.mnc001.mcc404.3gppnetwork.org (sip:404010000049944@ims.mnc001.mcc404.3gppnetwork.org (192.168.101.2:32771) to sip:404010000049944@ims.mnc001.mcc404.3gppnetwork.org, cYQORHLA-21ieQa5MWcWrQ..@192.168.101.2)
pcscf        | 104(140) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
pcscf        | 104(140) NOTICE: <script>: PCSCF REGISTER:
pcscf        |  Destination URI: <null>
pcscf        |  Request URI: sip:ims.mnc001.mcc404.3gppnetwork.org
pcscf        | 104(140) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
pcscf        | 104(140) NOTICE: <script>: Source IP and Port: (192.168.101.2:32771)
pcscf        |  Route-URI:
pcscf        | 104(140) NOTICE: <script>: Received IP and Port: (172.23.0.21:5060)
pcscf        | 104(140) NOTICE: <script>: Contact header: <sip:404010000049944@192.168.101.2:5060>;+sip.instance="<urn:gsma:imei:35158111-979597-0>";q=1.0;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";video;+g.3gpp.smsip
pcscf        | 104(140) INFO: ims_registrar_pcscf [sec_agree.c:296]: cscf_get_security_verify(): No security-verify parameters found
icscf        | 32(65) INFO: ims_icscf [cxdx_uar.c:71]: create_uaa_return_code(): created AVP successfully : [uaa_return_code]
icscf        | 10(43) INFO: ims_icscf [cxdx_avp.c:137]: cxdx_get_avp(): cxdx_get_server_name: Failed finding avp
icscf        | 10(43) INFO: ims_icscf [cxdx_avp.c:137]: cxdx_get_avp(): cxdx_get_capabilities: Failed finding avp
icscf        | 10(43) INFO: ims_icscf [cxdx_avp.c:137]: cxdx_get_avp(): cxdx_get_result_code: Failed finding avp
icscf        | 10(43) INFO: ims_icscf [cxdx_uar.c:71]: create_uaa_return_code(): created AVP successfully : [uaa_return_code]
icscf        | 10(43) ERROR: <core> [core/resolve.c:1715]: sip_hostport2su(): could not resolve hostname: "scscf.ims.mnc001.mcc001.3gppnetwork.org"
icscf        | 10(43) ERROR: tm [ut.h:310]: uri2dst2(): failed to resolve "scscf.ims.mnc001.mcc001.3gppnetwork.org"
icscf        | 10(43) ERROR: tm [t_fwd.c:1728]: t_forward_nonack(): failure to add branches
icscf        | 10(43) ERROR: tm [tm.c:1679]: _w_t_relay_to(): t_forward_noack failed

**Comment by rajkumarv-bcw** [comment]
scscf.ims.mnc001.mcc001.3gppnetwork.org --> MCC supposed to be 404

**Comment by herlesupreeth** [comment]
Are you using cx_test branch?

Can you post here the content of 'scscf' tables in icscf database?

**Comment by rajkumarv-bcw** [comment]
> Are you using cx_test branch?
I'm using cx_test branch
 
> Can you post here the content of 'scscf' tables in icscf database?
mysql> select * from nds_trusted_domains;
+----+-----------------------------------+
| id | trusted_domain                    |
+----+-----------------------------------+
|  1 | ims.mnc001.mcc001.3gppnetwork.org |
+----+-----------------------------------+


mysql> select * from s_cscf ;
+----+-----------------------+--------------------------------------------------+
| id | name                  | s_cscf_uri                                       |
+----+-----------------------+--------------------------------------------------+
|  1 | First and only S-CSCF | sip:scscf.ims.mnc001.mcc001.3gppnetwork.org:6060 |
+----+-----------------------+--------------------------------------------------+

mysql> select * from nds_trusted_domains ;
Empty set (0.00 sec)

mysql> select * from s_cscf;
Empty set (0.00 sec)

I have deleted both entries and facing the same error.

**Comment by herlesupreeth** [comment]
Try executing the following manually the icscf container

```
mysql -u root -h ${MYSQL_IP} icscf -e "INSERT INTO s_cscf (name, s_cscf_uri) VALUES ('First and only S-CSCF', 'sip:scscf.$IMS_DOMAIN:6060');"

mysql -u root -h ${MYSQL_IP} icscf -e "INSERT INTO nds_trusted_domains (trusted_domain) VALUES ('$IMS_DOMAIN');"
```

**Comment by rajkumarv-bcw** [comment]
Thanks a lot. It worked. Connected 5 UE and I tried to list the REGISTERED users from SCSCF database and its showing empty

mysql -u root -h $MYSQL_IP
use scscf;
select * from subscriber ; //(and all items) 
Empty set (0.00 sec)

**Comment by herlesupreeth** [comment]
Because no data is written in SCSCF database as far as I know

**Comment by rajkumarv-bcw** [comment]
I'm can run SRS-eNB and the docker_open5gs in separate machine. Great Thanks for your support.
