### ISSUE TITLE
External UERANSIM

### ISSUE THREAD

**Issue by sumitsimplex** [herlesupreeth/docker_open5gs#48]
Hi Supreeth, I am trying to externalize UERANSIM from open5gs environment. I have updated the env to docker host ip and advertise IPs. Also uncommented to expose ports. The problem I am facing is UERANSIM being unable to make connection and times out.

[2021-08-06 14:13:14.547] [sctp] [info] Trying to establish SCTP connection... (172.18.56.177:38412)
[2021-08-06 14:18:18.562] [sctp] [error] Connecting to 172.18.56.177:38412 failed. SCTP could not connect: Connection timed out

P.S. For this I have created a new image for UERANSIM which I have tested with internal networking.
[OPEN5GS-extUERANSIM.docx](https://github.com/herlesupreeth/docker_open5gs/files/6946189/OPEN5GS-extUERANSIM.docx)

**Comment by myonlystarWang** [comment]
Hi
   I met the same issue,but finally solved.
   My network topology is as follows:
```
   ((open5gs+kamalio docker)deployed in VM1) <--------------------->(UERANSIM deployed in VM2)
       VM ip: 192.168.120.130/24                                        VM ip: 192.168.120.126/24 
```
  Thats is in the open5gs-gnb.yaml of UERANSIM,you should modify the linkIp ngapIp gtpIp to your real used ip(for your case,it should be 172.18.56.*)

**Comment by sumitsimplex** [comment]
Thank you  for your answer. My setup is slightly different.

    ((open5gs docker-compose))  <---DOCKER_HOST---->  ((UERANSIM docker-compose with "bridge" n/w mode))
    "Subnet": "172.22.0.0/24"      172.18.56.177        "Subnet": "172.17.0.0/16", "Gateway": "172.17.0.1"

I can ping docker host from UERANSIM container.
    
    # ping 172.18.56.177
    PING 172.18.56.177 (172.18.56.177) 56(84) bytes of data.
    64 bytes from 172.18.56.177: icmp_seq=1 ttl=37 time=2.96 ms
    64 bytes from 172.18.56.177: icmp_seq=2 ttl=37 time=2.35 ms_

Also I did set all three values along with the amfConfigs, here...
    
    mcc: '001'          # Mobile Country Code value
    mnc: '01'           # Mobile Network Code value (2 or 3 digits)
    
    nci: '0x000000010'  # NR Cell Identity (36-bit)
    idLength: 32        # NR gNB ID length in bits [22...32]
    tac: 1              # Tracking Area Code
    
    linkIp: 172.17.0.2   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
    ngapIp: 172.17.0.2   # gNB's local IP address for N2 Interface (Usually same with local IP)
    gtpIp: 172.17.0.2    # gNB's local IP address for N3 Interface (Usually same with local IP)
    
    # List of AMF address information
    amfConfigs:
      - address: 172.18.56.177
        port: 38412
    
    # List of supported S-NSSAIs by this gNB
    slices:
      - sst: 1
    
    # Indicates whether or not SCTP stream number errors should be ignored.
    ignoreStreamIds: true

But I can't understand what I am doing wrong that SCTP connection doesn't work for me?

    # build/nr-gnb -c config/open5gs-gnb.yaml
    UERANSIM v3.1.9
    [2021-08-07 18:46:05.259] [sctp] [info] Trying to establish SCTP connection... (172.18.56.177:38412)
    [2021-08-07 18:51:09.640] [sctp] [error] Connecting to 172.18.56.177:38412 failed. SCTP could not connect: Connection timed out

**Comment by myonlystarWang** [comment]
OK, I see.
What about your open5gs docker-compose.yaml setting?
In the amf setting:
Did you uncomment the #port  #38412?

**Comment by herlesupreeth** [comment]
Rightly pointed out. You need to uncomment ports 38412 under amf section of your docker compose file

**Comment by sumitsimplex** [comment]
I did that already. All required ports are mapped.
<img width="508" alt="Screenshot 2021-08-08 at 09 46 29" src="https://user-images.githubusercontent.com/26219747/128626451-3c8441cd-df1e-466e-aabb-ade8b7d29c5f.png">

**Comment by sumitsimplex** [comment]
> OK, I see.
> What about your open5gs docker-compose.yaml setting?
> In the amf setting:
> Did you uncomment the #port #38412?

yes

**Comment by herlesupreeth** [comment]
I can think of two things

1. If you are using Windows to run the containers by any change then its not possible due to lack of SCTP support
2. Can you run the below command on the host machine and send me the output?

`sudo netstat -tuplnS | grep 38412`

**Comment by sumitsimplex** [comment]
Yes I am using windows. May be it's windows that lack support for sctp.
So netstat doesn't work as it in windows, lacks some flags but looking at the output for netstat -n don't think it has port 38412 anywhere. But also I can't even see 3000 which is webui which is working fine.

**Comment by ljysdfz** [comment]
> Hi I met the same issue,but finally solved. My network topology is as follows:
> 
> ```
>    ((open5gs+kamalio docker)deployed in VM1) <--------------------->(UERANSIM deployed in VM2)
>        VM ip: 192.168.120.130/24                                        VM ip: 192.168.120.126/24 
> ```
> 
> Thats is in the open5gs-gnb.yaml of UERANSIM,you should modify the linkIp ngapIp gtpIp to your real used ip,for me it is 192.168.120.126(for your case,it should be 172.18.56.*)

I had followed the aforementioned steps but failed.
Could you please send me your project or configuration yaml files for reference? 
My email is lijy790@qq.com.
Thank you in advance.

**Comment by herlesupreeth** [comment]
Closing this as the repo is not tested in Windows OS
