### ISSUE TITLE
Can UERANSIM test for VoNR now?

### ISSUE THREAD

**Issue by myonlystarWang** [herlesupreeth/docker_open5gs#50]
Hi,
   Can `UERANSIM `test for VoNR now?Or just for testing 5G traffic with this docker?
   Thanks for your good work!!

**Comment by herlesupreeth** [comment]
Hi, Unfortunately there are no opensource IMS which talks SBI interface to PCF and HSS/UDM. And i dont think there is any support for VoNR in open5gs

**Comment by herlesupreeth** [comment]
You can test normal internet traffic using UERANSIM

**Comment by myonlystarWang** [comment]
Thanks for the response!
I have tested the traffic before yet.
