### ISSUE TITLE
CPE without APN can not attach to open5gs

### ISSUE THREAD

**Issue by myonlystarWang** [herlesupreeth/docker_open5gs#53]
Hi,
    I had to open another issue for CPE without APN can not attach to open5gs,that is I have a CPE with setting `PLMN `460 06.The CPE attached failed with default APN `46006` when I try it with docker_open5gs(the same as #52 ).But I actually added `APN `configuration in `docker/open5gs/smf/smf.aml `and in `docker/open5gs/upf/upf.aml`,pcap file and config file as below:
[docker_open5gs_profile_20210809.zip](https://github.com/herlesupreeth/docker_open5gs/files/6952006/docker_open5gs_profile_20210809.zip)
[cpe_set_apn46006_but_reject-marked.txt](https://github.com/herlesupreeth/docker_open5gs/files/6952073/cpe_set_apn46006_but_reject-marked.txt)
(You need to change the .txt to .pcap,and because the original captured packet file was too large, I could not upload it even after compression, so I filtered and saved the packet according to this rule `s1ap || gtpv2 || pfcp || diameter || diameter.3gpp || sip || gtp`)
From the pcap file I can not see the APN name in `initial attach PDN conectivity request` even though there was set the default APN 46006.
But, when I change the APN settings of CPE to `internet`,the CPE can attach successfully but with no traffic(No traffic issue we can talk about it later).ande the pcap file as below:
[cpe_set_internet_apn_succ_but_no_traffic.zip](https://github.com/herlesupreeth/docker_open5gs/files/6952078/cpe_set_internet_apn_succ_but_no_traffic.zip)
From the pcap file I also can not see the APN name in `initial attach PDN conectivity request`,but how did it do it?
I'm a little confused,I was hoping you could give me some pointers.
Thanks in advance!

**Comment by herlesupreeth** [comment]
First of all, open5gs WebUI does not have 46006 APN profile set for this UE (check out the reject cause)
![image](https://user-images.githubusercontent.com/4115839/128665758-6d005383-db35-4822-881c-ad9ca1281469.png)

Second, the settings in your smf.yaml and upf.yaml is wrong. The 'addr' field for each subnet should be as follows

`addr: 172.20.49.1/24`

Notice the .1/24 of the subnet, you were defining it .0/24. So change the addr parameters under subnets in both smf.yaml and upf.yaml

Third, in your upf_init.sh file you have disabled NAT for ogstun3, this is the reason you dont have internet on your CPE, you need to enabled NAT by removing  `--nat_rule 'no'`

`python3 /mnt/upf/tun_if.py --tun_ifname ogstun3 --ipv4_range 172.20.249.0/24 --ipv6_range 2001:230:dafe::/48 --nat_rule 'no'`

**Comment by myonlystarWang** [comment]
Thanks very much!!! I have modified this params already and wait for test.
I have one more questions:
The `--nat_rule 'no'`,when should I use it and when should I not?
On my previous configuration, after I added the static route,I found that I could not ping ue from the PDN computer(192.168.120.200),but UE can ping the computer(192.168.120.200) successfully.I wonder if this has something to do with the `--nat_rule 'no'`?

**Comment by myonlystarWang** [comment]
I have modified the params of smf.yaml and upf.yaml as below:
[changed_profile.zip](https://github.com/herlesupreeth/docker_open5gs/files/6952848/changed_profile.zip)
But unfortunately the uplink&downlink traffic doesn't work again.This is the pcap file:
[change_smf&upf_setting_without_staticroute.zip](https://github.com/herlesupreeth/docker_open5gs/files/6952854/change_smf.upf_setting_without_staticroute.zip)
I can see the ping request send from 172.22.0.6 to 172.22.0.8,but do not send form 172.22.0.8 to 192.168.120.121 as before.
Is there anything else in my configuration that is not correct?

**Comment by herlesupreeth** [comment]
It looks like NATing is still not happening

![image](https://user-images.githubusercontent.com/4115839/128676755-fb4d763b-a113-42e3-ab56-e46d47b85d05.png)

> The --nat_rule 'no',when should I use it and when should I not?

NAT is not used only for IMS and used in rest of the scenarios

**Comment by myonlystarWang** [comment]
```
python3 /mnt/upf/tun_if.py --tun_ifname ogstun --ipv4_range 172.20.49.0/24 --ipv6_range 2001:230:cafe::/48
python3 /mnt/upf/tun_if.py --tun_ifname ogstun2 --ipv4_range 172.20.149.0/24 --ipv6_range 2001:230:babe::/48 --nat_rule 'no'
python3 /mnt/upf/tun_if.py --tun_ifname ogstun3 --ipv4_range 172.20.249.0/24 --ipv6_range 2001:230:dafe::/48 --nat_rule 'no'
```
I use the APN 46006, so should I delete the `--nat_rule 'no'` last line?

**Comment by herlesupreeth** [comment]
> I use the APN 46006, so should I delete the --nat_rule 'no' last line?

Yes

**Comment by myonlystarWang** [comment]
I delete the `--nat_rule 'no'` in the last line of` ../upf/tun_if.py ` and have a try with the order of commands `reboot` `set -a`  `source .env` `docker-compose up`,then connect to EnodeB, turn on the CPE.
Everything works fine!! Thank you very much for pointing the `nat `and `subnet `problem!!
