### ISSUE TITLE
srsLTE eNB build failed

### ISSUE THREAD

**Issue by akseslab** [herlesupreeth/docker_open5gs#56]
Hi Herle,

I'm facing this issue during build and run srsLTE eNB process.
The command docker-compose -f srsenb.yaml build --no-cache, produce the following error:
make[2]: *** [src/oglGraph/CMakeFiles/oglGraph.dir/build.make:76: src/oglGraph/CMakeFiles/oglGraph.dir/GLFont.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/oglGraph/CMakeFiles/oglGraph.dir/build.make:63: src/oglGraph/CMakeFiles/oglGraph.dir/dlgMarkers.cpp.o] Error 1
make[2]: *** [src/oglGraph/CMakeFiles/oglGraph.dir/build.make:89: src/oglGraph/CMakeFiles/oglGraph.dir/OpenGLGraph.cpp.o] Error 1
make[2]: *** [src/oglGraph/CMakeFiles/oglGraph.dir/build.make:102: src/oglGraph/CMakeFiles/oglGraph.dir/glew/glew.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:446: src/oglGraph/CMakeFiles/oglGraph.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
The command '/bin/sh -c git clone https://github.com/myriadrf/LimeSuite.git &&     cd LimeSuite &&     git checkout tags/v20.10.0 -b v20.10.0 &&     mkdir builddir && cd builddir && cmake .. &&     make -j`nproc` && make install && ldconfig &&     cd ../udev-rules && sh ./install.sh' returned a non-zero code: 2
ERROR: Service 'srsenb' failed to build : Build failed

I've test the command on fresh install Ubuntu 18.04 and Ubuntu 20.04, and both of them produce same error message. Could you please give some advises?

Thanks,
Erik

**Comment by herlesupreeth** [comment]
I completely rebuilt the image from scratch myself and I didnt face this issue. Sorry cant help you on this.
