### ISSUE TITLE
IMS + 5GNR SA

### ISSUE THREAD

**Issue by n-gerasimov** [herlesupreeth/docker_open5gs#59]
Hi,

Just wondering if anyone has tried setting up Open5GS (docker deployment) with Kamailio IMS for Standalone 5G?
I have done the configuration of all the core functions and registration and authentication are completed, but since PDU session establishment with DNN IMS, it seems like nothing is going further and the UE gets released.
Up to now, only UE with data-cetnric capabilities (which doesn't care about IMS bearer) can successfully attach and establish data transfer with the Internet. 

BR,
Nikita

**Comment by bluehat-f** [comment]
It seems open5gs has supported VoNR. Any one tested open5gs with Kamailio IMS?
