### ISSUE TITLE
Invalid port "3868/sctp"

### ISSUE THREAD

**Issue by anhtrung87vn** [herlesupreeth/docker_open5gs#6]
Hi,

When I execute the command docker-compose up, it appears issues as below:
Could you advise how to fix it?

ERROR: for pgw  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

ERROR: for hss  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

ERROR: for pcrf  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

ERROR: for pgw  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

ERROR: for pcrf  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

ERROR: for hss  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 952, in up
    start=not no_start
  File "/usr/lib/python2.7/dist-packages/compose/project.py", line 455, in up
    get_deps,
  File "/usr/lib/python2.7/dist-packages/compose/parallel.py", line 70, in parallel_execute
    raise error_to_reraise
ValueError: Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

**Comment by herlesupreeth** [comment]
can you please tell me your host config and linux distribution being used?

**Comment by herlesupreeth** [comment]
can you update the docker-ce and docker-compose to the following versions and give it a try?

```
docker-compose --version
docker-compose version 1.26.0, build d4451659
```
```
docker --version
Docker version 19.03.13, build 4484c46d9
```

**Comment by anhtrung87vn** [comment]
Thank you,

I upgrade the docker-compose to the docker-compose version 1.26.0 and it worked well.
But there are some error trace after starting. It is a normal behavior?
mysql        | invoke-rc.d: policy-rc.d denied execution of stop.
mysql        | update-alternatives: using /etc/mysql/mysql.cnf to provide /etc/mysql/my.cnf (my.cnf) in auto mode
mysql        | Renaming removed key_buffer and myisam-recover options (if present)
mysql        | Cannot stat file /proc/225/fd/0: Permission denied
mysql        | Cannot stat file /proc/225/fd/1: Permission denied
mysql        | Cannot stat file /proc/225/fd/2: Permission denied
mysql        | Cannot stat file /proc/225/fd/3: Permission denied
mysql        | Cannot stat file /proc/225/fd/4: Permission denied
mysql        | Cannot stat file /proc/225/fd/5: Permission denied
mysql        | Cannot stat file /proc/225/fd/6: Permission denied
mysql        | Cannot stat file /proc/225/fd/7: Permission denied
mysql        | Cannot stat file /proc/225/fd/8: Permission denied
mysql        | Cannot stat file /proc/225/fd/9: Permission denied
mysql        | Cannot stat file /proc/225/fd/10: Permission denie
....
scscf        | 28(81) INFO: cdp [receiver.c:874]: peer_connect(): peer_connect(): Trying to connect to 172.22.0.11 port 3868
scscf        | 28(81) ERROR: cdp [receiver.c:922]: peer_connect(): peer_connect(): Error opening connection to to 172.22.0.11 port 3868 >Connection refused
icscf        | 28(73) INFO: cdp [peerstatemachine.c:524]: I_Snd_Conn_Req(): I_Snd_Conn_Req(): Peer hss.ims.mnc001.mcc001.3gppnetwork.org 
scscf        | 29(82) DEBUG: ims_registrar_scscf [ims_registrar_scscf_mod.c:528]: child_init(): Initialization of module in child [127] 
scscf        | 29(82) DEBUG: ims_registrar_scscf [registrar_notify.c:2269]: notification_event_process(): Running notification_event_process
icscf        | 28(73) INFO: cdp [receiver.c:874]: peer_connect(): peer_connect(): Trying to connect to 172.22.0.11 port 3868
icscf        | 28(73) ERROR: cdp [receiver.c:922]: peer_connect(): peer_connect(): Error opening connection to to 172.22.0.11 port 3868 >Connection refused
scscf        | 33(86) DEBUG: ims_registrar_scscf [ims_registrar_scscf_mod.c:528]: child_init(): Initialization of module in child [-2] 
scscf        | 36(89) DEBUG: ims_registrar_scscf [ims_registrar_scscf_mod.c:528]: child_init(): Initialization of module in child [6] 
scscf        | 32(85) DEBUG: ims_registrar_scscf [ims_registrar_scscf_mod.c:528]: child_init(): Initialization of module in child [127] 
....
pcscf        | 99(154) ERROR: <script>: Preloading NAT-PING. Rows: 0

**Comment by herlesupreeth** [comment]
Those permission denied for mysql are normal but for cdp peer I suspect something is wrong. Do one thing execute the following

Stop the docker-compose, then run

`docker system prune -f`

Then, try to run it again

**Comment by anhtrung87vn** [comment]
Hi @herlesupreeth ,

I have the same issue after executing "docker system prune -f" command.

**Comment by herlesupreeth** [comment]
A complete log (please dont paste it here, send as separate text file) and pcap would be helpful

**Comment by anhtrung87vn** [comment]
I will do it again and send it to you tomorrow, thank you.

**Comment by anhtrung87vn** [comment]
Hi @herlesupreeth ,

Please get log from attachment.
[open5gs_container.log](https://github.com/herlesupreeth/docker_open5gs/files/5318821/open5gs_container.log)

and Pcap file from the link https://gofile.io/d/A5rQGT

**Comment by herlesupreeth** [comment]
I dont see any issue in the log, all components came up properly.. SCTP is working properly itself and so is all other components

**Comment by herlesupreeth** [comment]
Please feel free to re-open if you face further issues regarding SCTP and its port
