### ISSUE TITLE
srsenb docker up failed

### ISSUE THREAD

**Issue by ahnaseri** [herlesupreeth/docker_open5gs#60]
Hi 

In running srsenb docker i get following error :

srsenb    | Trying to open RF device 'UHD'
srsenb    | [INFO] [UHD] linux; GNU C++ version 9.3.0; Boost_107100; UHD_4.1.0.4-release
srsenb    | [INFO] [LOGGING] Fastpath logging disabled at runtime.
srsenb    | [WARNING] [B200] EnvironmentError: IOError: Could not find path for image: usrp_b200_fw.hex
srsenb    | 
srsenb    | Using images directory: <no images directory located>
srsenb    | 
srsenb    | Set the environment variable 'UHD_IMAGES_DIR' appropriately or follow the below instructions to download the images package.
srsenb    | 
srsenb    | Please run:
srsenb    | 
srsenb    |  "/lib/x86_64-linux-gnu/uhd/utils/uhd_images_downloader.py"

somehow in docker can not find image of USRP B210, I test several thing but can not manage to solve it.
anybody have similar issue??

**Comment by herlesupreeth** [comment]
Please mention which is your host machine OS and other environment details you are running the docker on

**Comment by ahnaseri** [comment]
Tnx @herlesupreeth 

My OS is Ubuntu 18.04 
I install a raw Ubutnu 18.04 from base on my PC then followed your instruction to install docker-ce, docker-compose and then instruction to build docker image

My network interface is LAN and use USRP B210 as Hardware

i've also installed UHD on my machine

**Comment by herlesupreeth** [comment]
Thank you. Can you please post the entire log when you execute the below command

`docker-compose -f srsenb.yaml build --no-cache`

**Comment by ahnaseri** [comment]
there is the log of command
[log.txt](https://github.com/herlesupreeth/docker_open5gs/files/7496606/log.txt)

**Comment by herlesupreeth** [comment]
I dont see any issue with building of srsRAN image. If you have plugged in your SDR please unplug it and then plug it back again. And, then run srsRAN eNB and send me the logs

**Comment by ahnaseri** [comment]
and the log of  `docker-compose -f srsenb.yaml up -d ` : 

srsenb    | ---  Software Radio Systems LTE eNodeB  ---
srsenb    | 
srsenb    | Couldn't open , trying /root/.config/srsran/enb.conf
srsenb    | Couldn't open /root/.config/srsran/enb.conf either, trying /etc/srsran/enb.conf
srsenb    | Reading configuration file /etc/srsran/enb.conf...
srsenb    | Couldn't open rb.conf, trying /root/.config/srsran/rb.conf
srsenb    | Couldn't open /root/.config/srsran/rb.conf either, trying /etc/srsran/rb.conf
srsenb    | WARNING: cpu0 scaling governor is not set to performance mode. Realtime processing could be compromised. Consider setting it to performance mode before running the application.
srsenb    | 
srsenb    | Built in Release mode using commit 5275f3336 on branch master.
srsenb    | 
srsenb    | Opening 1 channels in RF device=default with args=default
srsenb    | Available RF device list: UHD  soapy  zmq 
srsenb    | Trying to open RF device 'UHD'
srsenb    | [INFO] [UHD] linux; GNU C++ version 9.3.0; Boost_107100; UHD_4.1.0.4-release
srsenb    | [INFO] [LOGGING] Fastpath logging disabled at runtime.
srsenb    | [WARNING] [B200] EnvironmentError: IOError: Could not find path for image: usrp_b200_fw.hex
srsenb    | 
srsenb    | Using images directory: <no images directory located>
srsenb    | 
srsenb    | Set the environment variable 'UHD_IMAGES_DIR' appropriately or follow the below instructions to download the images package.
srsenb    | 
srsenb    | Please run:
srsenb    | 
srsenb    |  "/lib/x86_64-linux-gnu/uhd/utils/uhd_images_downloader.py"
srsenb    | Opening USRP channels=1, args: 
srsenb    | [INFO] [UHD RF] RF UHD Generic instance constructed
srsenb    | [WARNING] [B200] EnvironmentError: IOError: Could not find path for image: usrp_b200_fw.hex
srsenb    | 
srsenb    | Using images directory: <no images directory located>
srsenb    | 
srsenb    | Set the environment variable 'UHD_IMAGES_DIR' appropriately or follow the below instructions to download the images package.
srsenb    | 
srsenb    | Please run:
srsenb    | 
srsenb    |  "/lib/x86_64-linux-gnu/uhd/utils/uhd_images_downloader.py"
srsenb    | /srsRAN/lib/src/phy/rf/rf_uhd_imp.cc:930: uhd_init failed, freeing...
srsenb    | [ERROR] [UHD RF] LookupError: KeyError: No devices found for ----->
srsenb    | Empty Device Address
srsenb    | Unable to open RF device 'UHD'
srsenb    | Trying to open RF device 'soapy'
srsenb    | No Soapy devices found.
srsenb    | Unable to open RF device 'soapy'
srsenb    | Trying to open RF device 'zmq'
srsenb    | [zmq] Error: No device 'args' option has been set. Please make sure to set this option to be able to use the ZMQ no-RF module
srsenb    | Unable to open RF device 'zmq'
srsenb    | /srsRAN/lib/src/phy/rf/rf_imp.c:145: Failed to open a RF frontend device. Please check the available srsRAN CMAKE options to verify what RF frontend devices have been detected in your system
srsenb    | Error initializing radio.

**Comment by herlesupreeth** [comment]
Thanks a lot for testing it out. I have pushed the fixes onto the relevant branches, please take the latest changes and recompile the image. It should solve it.

**Comment by ahnaseri** [comment]
Thanks you, the problem solved !!!

But now in adding user to FoHSS, when i log in to hss web console , in user identities tab there is no create button to add new user (such below picture)

![image](https://user-images.githubusercontent.com/12709903/141134607-46fd6794-7b98-4057-a2d7-0fb1f0e90645.png)

**Comment by herlesupreeth** [comment]
I just now recompiled the fhoss image and i see create option

![image](https://user-images.githubusercontent.com/4115839/141496586-e519e881-16c4-4b04-8b23-6b74ca01a2c3.png)

**Comment by ahnaseri** [comment]
Tnx @herlesupreeth  for your reply. the problem solved.

but another problem happend in using VOLTE.
I added two subscriber as you said but at the beginning i got this in docker log : 

mme          | 11/14 10:45:22.114: [emm] INFO: [001010123456789] Extended service request (../src/mme/emm-sm.c:390)
mme          | 11/14 10:45:22.114: [emm] INFO:     M-TMSI:[0xe000d3a6] IMSI:[001010123456789] (../src/mme/emm-handler.c:635)
mme          | 11/14 10:45:22.114: [emm] WARNING: No P-TMSI : UE[001010123456789] (../src/mme/emm-sm.c:474)

and after that phone get Service Reject

**Comment by ahnaseri** [comment]
maybe p-tmsi that assigned to phone in Attach Accept not Updated in MME

**Comment by ahnaseri** [comment]
Tnx @herlesupreeth  for your answer.

Problem solved. FHoSS user must be hssAdmin not hss

**Comment by ahnaseri** [comment]
but there is another problem with volte.

I have two phone and both have VOLTE sign top of screen. but when making call i got following messages : 

mme          | 11/16 15:37:48.428: [emm] INFO: [001010123456063] Extended service request (../src/mme/emm-sm.c:390)
mme          | 11/16 15:37:48.428: [emm] INFO:     M-TMSI:[0xdc000cd3] IMSI:[001010123456063] (../src/mme/emm-handler.c:635)
mme          | 11/16 15:37:48.428: [emm] WARNING: No P-TMSI : UE[001010123456063] (../src/mme/emm-sm.c:474)



and then i get "Service Reject (UE Identity can not be derived by the network)"

**Comment by herlesupreeth** [comment]
> mme | 11/16 15:37:48.428: [emm] INFO: [001010123456063] Extended service request (../src/mme/emm-sm.c:390)

If the logs says this, then that means UE tried to do calls over IMS but failed and then tries for Circuit Switched fallback. Or tries to do call over Circuit Switched network

**Comment by ahnaseri** [comment]
Tnx for your tips @herlesupreeth 

I search over logs and pcaps and found that after Session Termination Request from PCSCF to PCRF, VoLTE call not anymore working and go for CSFB

![image](https://user-images.githubusercontent.com/12709903/142186326-055c7e12-0aa9-4323-aa5e-d1f063cbce23.png)

here is pcap files :
[log-call-fail.zip](https://github.com/herlesupreeth/docker_open5gs/files/7553964/log-call-fail.zip)

**Comment by herlesupreeth** [comment]
![image](https://user-images.githubusercontent.com/4115839/142196830-97c4a88f-c8dd-4a9a-8d8a-2a1111f2cd73.png)

In the log-call-fail2.pcapng, i see that you are trying to call to same number as the device is assigned. Ofcourse it will fail (tel 12345 belong to UE registered with IP 192.168.101.2)

**Comment by ahnaseri** [comment]
yeah i call myself and get line is busy ...
I also call another party 12346 (not attached yet and i get user not found as expected) and another one that is not in HSS (and i get HSS user unknown) .... everything is ok  and expected but after some calls we have Session Termination Request ...
