### ISSUE TITLE
IMS VoIP Server error on LIR select next S-CSCF

### ISSUE THREAD

**Issue by MauricioV** [herlesupreeth/docker_open5gs#61]
Hi,

I´m doing a test based on docker_open5gs files isolating the IMS core  components (pcscf, icscf, scscf, fohss, mysql, dns, rtpengine, ims_base), to have a testbed on GNS3. 

Since the tests are performed on a network outside the core network (TEST_NETWORK = 172.22.0.0 / 24), I have enabled the NAT related parameters in the pcscf. On the other hand, I intend to use the HOMER SIP Capture docker images to take QoS traces, so I need to make modifications to the RTPENGINE configuration to activate HOMER support.

In the tests that I have carried out based on the attached files, according to the scenario raised, when making the call between alice and bob. I get the error "Server error on LIR select next S-CSCF". I attach the SIP traces (pcap) and the corresponding log. From what I can see, in the icscf the error is the following on the log file (IMS.log):

Line 1514 ERROR: <script>: $ru => sip:bob@ims.mnc001.mcc001.3gppnetwork.org

[docker_ims.zip](https://github.com/herlesupreeth/docker_open5gs/files/7515015/docker_ims.zip)
[IMS.log](https://github.com/herlesupreeth/docker_open5gs/files/7515016/IMS.log)
[PCAP-IMS.zip](https://github.com/herlesupreeth/docker_open5gs/files/7515019/PCAP-IMS.zip)

Greetings

**Comment by herlesupreeth** [comment]
![image](https://user-images.githubusercontent.com/4115839/141272031-c4d043fa-76b4-4469-94eb-23128285b879.png)

Please check the authentication mechanism set for bob in HSS.

**Comment by MauricioV** [comment]
Hi, I check the authentication mechanism but the problem persist:

This is the hss information for Alice:
![Alice](https://user-images.githubusercontent.com/6804880/141308213-56117bed-dde3-4b98-a977-407911ffe9ec.png)

This is the hss information for Bob:
![Bob](https://user-images.githubusercontent.com/6804880/141308268-97edf7a2-3241-4c8b-9bbe-42af2394aaaa.png)

And this is the PCAP:
[PCAP11112021.zip](https://github.com/herlesupreeth/docker_open5gs/files/7520792/PCAP11112021.zip)
[IMS11112021.log](https://github.com/herlesupreeth/docker_open5gs/files/7520800/IMS11112021.log)

I'm using Boghe IMS as client
![Boghe Alice](https://user-images.githubusercontent.com/6804880/141309048-76477ea0-8d5a-4204-a54d-e23593734fee.png)
![Boghe Bob](https://user-images.githubusercontent.com/6804880/141309064-e65ca62c-6077-466a-85a1-57a8309b7205.png)
![Boghe network](https://user-images.githubusercontent.com/6804880/141309180-51ee5976-db35-42e6-9022-9ed6278a6e97.png)

**Comment by herlesupreeth** [comment]
Now the REGISTER for bob is successful. The call is failing because your UE is behind a NAT.

**Comment by MauricioV** [comment]
I´m using this configuration on the P-CSCF:

# IP-Adress for incoming SIP-Traffic, in the following format:

# SIP / UDP
#listen=udp:PCSCF_IP:5060
listen=udp:PCSCF_IP:5060 advertise PCSCF_PUB_IP:5060
# SIP / TCP
#listen=tcp:PCSCF_IP:5060
listen=tcp:PCSCF_IP:5060 advertise PCSCF_PUB_IP:5060
# SIP / TCP/TLS
#listen=tls:PCSCF_IP:5061

# IPSEC / UDP
##!define IPSEC_LISTEN_ADDR "PCSCF_IP"
#!define IPSEC_LISTEN_ADDR "PCSCF_PUB_IP"
#!define IPSEC_CLIENT_PORT 5100
#!define IPSEC_SERVER_PORT 6100
#!define IPSEC_MAX_CONN 10

# IP used in Rx_AAR_Register - IP of this P-CSCF, to be used in the flow for the AF-signaling
##!define RX_AF_SIGNALING_IP "PCSCF_IP"
# Uncomment the below line only when UE is behind double NAT (e.g. VoIP calling over WiFi/ CN behind a NAT)
#!define RX_AF_SIGNALING_IP "PCSCF_PUB_IP"

alias=pcscf.IMS_DOMAIN

#!define MY_WS_PORT 80
#!define MY_WSS_PORT 443

#!define PCSCF_URL "sip:pcscf.IMS_DOMAIN:5060"

#!define TCP_PROCESSES 8

#!subst "/NETWORKNAME/IMS_DOMAIN/"
#!subst "/HOSTNAME/pcscf.IMS_DOMAIN/"
#!subst "/PCRF_REALM/EPC_DOMAIN/"

# SIP-Address of capturing node, if not set, capturing is disabled.
##!define CAPTURE_NODE "sip:127.0.0.1:9060"

# Allowed IPs for XML-RPC-Queries
##!define XMLRPC_WHITELIST_1 "127.0.0.1"
##!define XMLRPC_WHITELIST_2 "127.0.0.1"
##!define XMLRPC_WHITELIST_3 "127.0.0.1"

# Databases:
#!define DB_URL "mysql://pcscf:heslo@MYSQL_IP/pcscf"
##!define DB_URL2 "con2=>mysql://pcscf:heslo@MYSQL_IP/pcscf"

#!define SQLOPS_DBURL "pcscf=>mysql://pcscf:heslo@MYSQL_IP/pcscf"

#! Optional: Server-URL for Websocket-Requests
##!define WEBSOCKET_WEBSERVER "phone.ng-voice.com"

##!define TRF_FUNCTION "trf.IMS_DOMAIN"

#
# Several features can be enabled using '#!define WITH_FEATURE' directives:
#
# *** To run in debug mode: 
#     - define WITH_DEBUG
#
# *** To enable nat traversal execute:
#     - define WITH_NAT
#     - define the connection to the RTP-Proxy: RTPPROXY_ADDRESS
#
# *** To force alls calls through the RTP-Proxy
#     - this will automagically enable NAT-Traversal
#     - define FORCE_RTPRELAY
#
# *** To enable IPv4/IPv6 Translation (RTPProxy)
#     - this will automagically enable NAT-Traversal
#     - define WITH_RTPIPV4
#
# *** To enable TCP support execute:
#     - define WITH_TCP
#
# *** To enable TLS support execute:
#     - adjust CFGDIR/tls.cfg as needed
#     - define WITH_TLS
#     - this will automagically enable TCP
#
# *** To enable XMLRPC support execute:
#     - define WITH_XMLRPC
#     - this will automagically enable TCP
#
# *** To enable anti-flood detection execute:
#     - adjust pike and htable=>ipban settings as needed (default is
#       block if more than 16 requests in 2 seconds and ban for 300 seconds)
#     - define WITH_ANTIFLOOD
#
# *** To enable the Rx-Interface:
#     - Configure Rx-Diameter-Interface in pcscf.xml
#     - define WITH_RX
#
# *** To enable a Homer SIP-Capter-Node:
#     - define CAPTURE_NODE with a proper address
#
# *** To enable support for the SEMS-SBC
#     - define WITH_SBC
#     - configure dispatcher-list with a set of SBC's

#
# Enabled Features for this host:
##!define WITH_DEBUG
#!define WITH_NAT
#!define WITH_NATPING
#!define FORCE_RTPRELAY
##!define WITH_TLS
##!define WITH_XMLRPC
##!define WITH_IPBLOCK
##!define WITH_ANTIFLOOD
##!define WITH_RX
##!define WITH_RX_REG
##!define WITH_RX_CALL
#!define WITH_TCP
##!define WITH_RTPIPV4
##!define WITH_SBC
##!define WITH_SBC_CALL
##!define WITH_REGINFO
##!define WITH_RTPPING
##!define WITH_WEBSOCKET
#!define WITH_IPSEC
#!define WITH_IMS_HDR_CACHE
#!define WITH_PING_UDP
#!define WITH_PING_TCP

**Comment by MauricioV** [comment]
Dear Herle I'm using the following configuration on the pcscf, it´s ok?

1.	# IP-Adress for incoming SIP-Traffic, in the following format:
2.	 
3.	# SIP / UDP
4.	#listen=udp:PCSCF_IP:5060
5.	listen=udp:PCSCF_IP:5060 advertise PCSCF_PUB_IP:5060
6.	# SIP / TCP
7.	#listen=tcp:PCSCF_IP:5060
8.	listen=tcp:PCSCF_IP:5060 advertise PCSCF_PUB_IP:5060
9.	# SIP / TCP/TLS
10.	#listen=tls:PCSCF_IP:5061
11.	 
12.	# IPSEC / UDP
13.	##!define IPSEC_LISTEN_ADDR "PCSCF_IP"
14.	#!define IPSEC_LISTEN_ADDR "PCSCF_PUB_IP"
15.	#!define IPSEC_CLIENT_PORT 5100
16.	#!define IPSEC_SERVER_PORT 6100
17.	#!define IPSEC_MAX_CONN 10
18.	 
19.	# IP used in Rx_AAR_Register - IP of this P-CSCF, to be used in the flow for the AF-signaling
20.	##!define RX_AF_SIGNALING_IP "PCSCF_IP"
21.	# Uncomment the below line only when UE is behind double NAT (e.g. VoIP calling over WiFi/ CN behind a NAT)
22.	#!define RX_AF_SIGNALING_IP "PCSCF_PUB_IP"
23.	 
24.	alias=pcscf.IMS_DOMAIN
25.	 
26.	#!define MY_WS_PORT 80
27.	#!define MY_WSS_PORT 443
28.	 
29.	#!define PCSCF_URL "sip:pcscf.IMS_DOMAIN:5060"
30.	 
31.	#!define TCP_PROCESSES 8
32.	 
33.	#!subst "/NETWORKNAME/IMS_DOMAIN/"
34.	#!subst "/HOSTNAME/pcscf.IMS_DOMAIN/"
35.	#!subst "/PCRF_REALM/EPC_DOMAIN/"
36.	 
37.	# SIP-Address of capturing node, if not set, capturing is disabled.
38.	##!define CAPTURE_NODE "sip:127.0.0.1:9060"
39.	 
40.	# Allowed IPs for XML-RPC-Queries
41.	##!define XMLRPC_WHITELIST_1 "127.0.0.1"
42.	##!define XMLRPC_WHITELIST_2 "127.0.0.1"
43.	##!define XMLRPC_WHITELIST_3 "127.0.0.1"
44.	 
45.	# Databases:
46.	#!define DB_URL "mysql://pcscf:heslo@MYSQL_IP/pcscf"
47.	##!define DB_URL2 "con2=>mysql://pcscf:heslo@MYSQL_IP/pcscf"
48.	 
49.	#!define SQLOPS_DBURL "pcscf=>mysql://pcscf:heslo@MYSQL_IP/pcscf"
50.	 
51.	#! Optional: Server-URL for Websocket-Requests
52.	##!define WEBSOCKET_WEBSERVER "phone.ng-voice.com"
53.	 
54.	##!define TRF_FUNCTION "trf.IMS_DOMAIN"
55.	 
56.	#
57.	# Several features can be enabled using '#!define WITH_FEATURE' directives:
58.	#
59.	# *** To run in debug mode:
60.	#     - define WITH_DEBUG
61.	#
62.	# *** To enable nat traversal execute:
63.	#     - define WITH_NAT
64.	#     - define the connection to the RTP-Proxy: RTPPROXY_ADDRESS
65.	#
66.	# *** To force alls calls through the RTP-Proxy
67.	#     - this will automagically enable NAT-Traversal
68.	#     - define FORCE_RTPRELAY
69.	#
70.	# *** To enable IPv4/IPv6 Translation (RTPProxy)
71.	#     - this will automagically enable NAT-Traversal
72.	#     - define WITH_RTPIPV4
73.	#
74.	# *** To enable TCP support execute:
75.	#     - define WITH_TCP
76.	#
77.	# *** To enable TLS support execute:
78.	#     - adjust CFGDIR/tls.cfg as needed
79.	#     - define WITH_TLS
80.	#     - this will automagically enable TCP
81.	#
82.	# *** To enable XMLRPC support execute:
83.	#     - define WITH_XMLRPC
84.	#     - this will automagically enable TCP
85.	#
86.	# *** To enable anti-flood detection execute:
87.	#     - adjust pike and htable=>ipban settings as needed (default is
88.	#       block if more than 16 requests in 2 seconds and ban for 300 seconds)
89.	#     - define WITH_ANTIFLOOD
90.	#
91.	# *** To enable the Rx-Interface:
92.	#     - Configure Rx-Diameter-Interface in pcscf.xml
93.	#     - define WITH_RX
94.	#
95.	# *** To enable a Homer SIP-Capter-Node:
96.	#     - define CAPTURE_NODE with a proper address
97.	#
98.	# *** To enable support for the SEMS-SBC
99.	#     - define WITH_SBC
100.	#     - configure dispatcher-list with a set of SBC's
101.	 
102.	#
103.	# Enabled Features for this host:
104.	##!define WITH_DEBUG
105.	#!define WITH_NAT
106.	#!define WITH_NATPING
107.	#!define FORCE_RTPRELAY
108.	##!define WITH_TLS
109.	##!define WITH_XMLRPC
110.	##!define WITH_IPBLOCK
111.	##!define WITH_ANTIFLOOD
112.	##!define WITH_RX
113.	##!define WITH_RX_REG
114.	##!define WITH_RX_CALL
115.	#!define WITH_TCP
116.	##!define WITH_RTPIPV4
117.	##!define WITH_SBC
118.	##!define WITH_SBC_CALL
119.	##!define WITH_REGINFO
120.	##!define WITH_RTPPING
121.	##!define WITH_WEBSOCKET
122.	#!define WITH_IPSEC
123.	#!define WITH_IMS_HDR_CACHE
124.	#!define WITH_PING_UDP
125.	#!define WITH_PING_TCP

**Comment by MauricioV** [comment]
I have found that this error is due to the IMS client, doubango Boghe does not support NAT traversal when registering both Alice and Bob. I have done tests using Jitsi and Zoiper without problems and in the same way I have integrated Homer SIP Capture, this issue can now be closed.
![Call trace](https://user-images.githubusercontent.com/6804880/143439930-65151cb3-8f11-4d49-bda0-346a2c06b3de.png)
![QoS](https://user-images.githubusercontent.com/6804880/143439938-87babaf0-0102-4e44-a48d-4c08a0c7caa4.png)
