### ISSUE TITLE
SRSENB is generating errors during installation

### ISSUE THREAD

**Issue by boukar10** [herlesupreeth/docker_open5gs#64]
Hello,

I'm using Ubuntu 20.4 installed on a PC with 2 ethernet port.

I install the VoLTE based on procedure https://open5gs.org/open5gs/docs/tutorial/03-VoLTE-dockerized/
when I send the command docker-compose up I can see all nodes are started and I can see also the following errors:

fhoss | ERROR 2003 (HY000): Can't connect to MySQL server on '172.22.0.17:3306' (111)
pcscf | 0(35) ERROR: <script>: event_route[htable:mod-init]
icscf | 28(57) ERROR: cdp [receiver.c:922]: peer_connect(): peer_connect(): Error opening connection to to 172.22.0.18 port 3868 >Connection refused
pcscf | 94(129) ERROR: cdp [peerstatemachine.c:637]: I_Snd_CER(): I_Snd_CER(): Error on finding local host address > Socket operation on non-socket
scscf | 28(61) ERROR: cdp [receiver.c:922]: peer_connect(): peer_connect(): Error opening connection to to 172.22.0.18 port 3868 >Connection refused
pcrf | 12/27 19:03:44.160: [diam] ERROR: pid:Worker#4[TCP] in client_worker@server.c:184: ERROR: in '(fd_cnx_receive(c, &ts, &rcv_data.buffer, &rcv_data.length))' : Connection timed out
pcscf | 98(133) ERROR: <script>: Preloading NAT-PING. Rows: 0

Please do you know how to fix these errors
When I try to install srsLTE I'm getting following error
-- Configuring incomplete, errors occurred!
See also "/srsRAN/build/CMakeFiles/CMakeOutput.log".
See also "/srsRAN/build/CMakeFiles/CMakeError.log".
ERROR: Service 'srsenb' failed to build: The command '/bin/sh -c git clone https://github.com/srsran/srsRAN.git && cd srsRAN && git checkout tags/release_21_04 && mkdir build && cd build && cmake ../ && make -jnproc && make install && ldconfig' returned a non-zero code: 1
Please can you help me ?
I attach also the logs from the screen.

Best Regards

[srsenb.txt](https://github.com/herlesupreeth/docker_open5gs/files/7785315/srsenb.txt)
[docker-compose--UP.txt](https://github.com/herlesupreeth/docker_open5gs/files/7785316/docker-compose--UP.txt)

**Comment by herlesupreeth** [comment]
```
CMake Error at CMakeLists.txt:479 (message):
  no SIMD instructions found

```
i am suspecting you are running on non-intel machine..I havent tried on ARM so you may have to modify the Dockerfile of srslte to suit your host machine instruction set/architecture

**Comment by herlesupreeth** [comment]
Apart from that all other components came up properly so please ignore the errors

**Comment by boukar10** [comment]
Hi @herlesupreeth 
Thank you very much, I will give it a try on an Intel Machine.
Best Regards

**Comment by boukar10** [comment]
Hi @herlesupreeth 
I got a Core i5 computer on which I installed Ubuntu 20.4.3 
I install docker-ce:  Docker version 20.10.12, build e91ed57 and docker-compose version 1.26.0, build d4451659

When I run the command docker build --no-cache --force-rm -t docker_open5gs . I'm getting the error below

Configuring core-config-private.h using configuration
Configuring core-config.h using configuration
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency talloc found: NO (tried pkgconfig)

lib/core/meson.build:307:0: ERROR: Dependency "talloc" not found, tried pkgconfig

A full log can be found at /open5gs/build/meson-logs/meson-log.txt
Removing intermediate container 0972dd972f32
The command '/bin/sh -c git clone --recursive https://github.com/open5gs/open5gs && cd open5gs &&     git checkout main && meson build --prefix=`pwd`/install &&     ninja -C build && cd build && ninja install' returned a non-zero code: 1
root@gobevolte:/home/gobesoft/docker_open5gs/base# docker-compose --version
I attach also the complete logs .
Please can you help me?
Best Regards
[Logs.txt](https://github.com/herlesupreeth/docker_open5gs/files/7797395/Logs.txt)

**Comment by boukar10** [comment]
Hi folks,
please do you know if there is any issue with the installation script?
the command docker build --no-cache --force-rm -t docker_open5gs . is generating errors.
Regards

**Comment by herlesupreeth** [comment]
It has been fixed in latest commit, please pull the latest changes and re-try the build command

**Comment by boukar10** [comment]
> It has been fixed in latest commit, please pull the latest changes and re-try the build command

Hi @herlesupreeth 
Thank you very much. It's working fine now.
Thank you
