### ISSUE TITLE
"docker-compose -f srsenb.yaml up" fails

### ISSUE THREAD

**Issue by jlrosa** [herlesupreeth/docker_open5gs#65]
Hello Supreeth,

After building the srsENB container following the command in the readme
`docker-compose -f srsenb.yaml build --no-cache`

I tried to start the container
`docker-compose -f srsenb.yaml up -d && docker attach srsenb`

And got the following error:
```[INFO] [UHD] linux; GNU C++ version 9.3.0; Boost_107100; UHD_4.1.0.4-release
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=1, args:
[INFO] [UHD RF] RF UHD Generic instance constructed
/srsRAN/lib/src/phy/rf/rf_uhd_imp.cc.776: USRP reported the following error: LookupError: KeyError: No devices found for ----->
Empty Device Address
/srsRAN/lib/src/phy/rf/rf_uhd_imp.cc.946: uhd_init failed, freeing...
No Soapy devices found.
[zmq] Error: RF device args are required for ZMQ no-RF module
/srsRAN/lib/src/phy/rf/rf_imp.c.129: No compatible RF frontend found
Error initializing radio.
```

Am I missing some configuration? Or doing something wrong.

Thanks!

**Comment by herlesupreeth** [comment]
There are no SDR devices connected to the machine where you are running the docker-compose -f srsenb.yaml up -d && docker attach srsenb command

If it is connected, then i would suggest to unplug it and then re-plug it back and then execute the above command

**Comment by jlrosa** [comment]
My bad, I was assuming this was a simulator as well. Thanks!
