### ISSUE TITLE
Does UERANSIM supports VoLTE?

### ISSUE THREAD

**Issue by WingPig99** [herlesupreeth/docker_open5gs#67]
Hey developer,

I've encountered a problem recently. I wrote a VoLTE client and it works with SRSRAN. But when I try to use UERANSIM to replace SRSRAN. It goes wrong with `SIP/2.0 403 Can't register to QoS for signalling`. I've traced the log. It seems some issue happened at pcrf, the detail as follows:

```
# docker-compose logs -f pcscf pcrf
pcrf         | 01/25 00:08:21.566: [pcrf] WARNING: Cannot find Gx Sesson for IPv4:192.168.100.10 (../src/pcrf/pcrf-rx-path.c:166)
pcrf         | 01/25 00:08:21.569: [pcrf] ERROR: No Gx Session (../src/pcrf/pcrf-rx-path.c:192)
pcscf        | 94(128) INFO: cdp [authstatemachine.c:270]: auth_client_statefull_sm_process(): after callback of event 7
pcscf        | 92(126) ERROR: <script>: Diameter: AAR failed on subscription to signalling
```

I also attached the detailed logs and sip message. Any insights would be very much appreciated.

[sip.txt](https://github.com/herlesupreeth/docker_open5gs/files/7929708/sip.txt)
[pcscf-pcrf.txt](https://github.com/herlesupreeth/docker_open5gs/files/7929709/pcscf-pcrf.txt)

**Comment by herlesupreeth** [comment]
I dont think UERANSIM (its a 5G gNB and UE stack) supports VoLTE or VoNR. Since VoLTE is for 4G calling and in 5G its VoNR. Open5gs does support VoNR and as part of that PCRF is not involved (its a 4g element)

The main elements in 5G Core that enable VoNR are amf, bsf, pcf, smf, upf, nrf

The part which is not supported in UERANSIM for VoNR is the QoS part.

**Comment by herlesupreeth** [comment]
However somehow you can simulate/emulate VoNR in the following fashion

1. Make a PDN connection for ims APN from UERANSIM UE
2. Then use your VoLTE client to trigger SIP registration using the IP address received for ims PDN connection

**Comment by WingPig99** [comment]
Hey Herlesupreeth,

Thank you for the information. Yes, I tried this. It seems it doesn't work.

> Make a PDN connection for ims APN from UERANSIM UE
> Then use your VoLTE client to trigger SIP registration using the IP address received for ims PDN connection

As followed, I got an IP `192.168.101.11` and triggered SIP registration using this IP address. I still got *"403 Can't register to QoS for signalling"*.
```
// log of UERANSIM
[app] [info] Connection setup for PDU session[1] is successful, TUN interface[uesimtun0, 192.168.100.11] is up.
[app] [info] Connection setup for PDU session[2] is successful, TUN interface[uesimtun1, 192.168.101.11] is up.

# ifconfig
uesimtun0: flags=369<UP,POINTOPOINT,NOTRAILERS,RUNNING,PROMISC>  mtu 1400
        inet 192.168.100.11  netmask 255.255.255.255  destination 192.168.100.11
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

uesimtun1: flags=369<UP,POINTOPOINT,NOTRAILERS,RUNNING,PROMISC>  mtu 1400
        inet 192.168.101.11  netmask 255.255.255.255  destination 192.168.101.11
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

# ip route
172.22.0.21 dev uesimtun1 scope link

# SIP response
SIP/2.0 403 Can't register to QoS for signalling
Via: SIP/2.0/UDP 192.168.101.11:5060;branch=z9hG4bK-pc7rab;rport=5060;received=192.168.101.11
From: <sip:466920123456721@ims.mnc092.mcc466.3gppnetwork.org>;tag=vIbj3nqq
To: <sip:466920123456721@ims.mnc092.mcc466.3gppnetwork.org>;tag=5fb97de55168ec7ab0ef548dfaf210d4-33ac5374
Call-ID: uCnXqhWDXS5PpB0OYW9ih9Fn
CSeq: 1 REGISTER
Server: TelcoSuite Proxy-CSCF
Content-Length: 0
```

**Comment by herlesupreeth** [comment]
Ah, i see. Is your IMS able to talk with PCF using SBI interfaces? If not, then VoNR won't work. In the VoNR (similar to P-CSCF talking to PCRF in 4G) P-CSCF would talk to PCF over SBI interface

**Comment by WingPig99** [comment]
> Is your IMS able to talk with PCF using SBI interfaces?

It seems PCSCF only talks with pcrf (172.22.0.4). And I found it was added  *\<Peer FQDN="pcrf.EPC_DOMAIN" Realm="EPC_DOMAIN" port="3868"/>* in `pcscf.xml`. Does it make sense? I also tried to replace this line with *\<Peer FQDN="pcf.EPC_DOMAIN" Realm="EPC_DOMAIN" port="7777"/>*. Unfortunately, it still doesn't work.

**Comment by herlesupreeth** [comment]
> I also tried to replace this line with <Peer FQDN="pcf.EPC_DOMAIN" Realm="EPC_DOMAIN" port="7777"/>. Unfortunately, it still doesn't work.

The interface between PCF and P-CSCF is not diameter its an SBI interface and P-CSCF does not have SBI interface to talk with PCF

**Comment by WingPig99** [comment]
Thank you! That helps a lot.
