### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by modyngs** [herlesupreeth/docker_open5gs#69]
Dear @herlesupreeth 

The build have failed in open5gs_hss_cx branch as bellow:
```

Get:6 https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04 ./ Packages [37.1 kB]
Fetched 38.7 kB in 2s (21.9 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libdbd-sqlite3 libdbi1 libmnl0 libosmo-gsup-client0 libosmo-mslookup0
  libosmoabis10 libosmocore18 libosmoctrl0 libosmogsm17 libosmovty9 libsctp1
  libtalloc2 osmocom-latest
Suggested packages:
  lksctp-tools
The following NEW packages will be installed:
  libdbd-sqlite3 libdbi1 libmnl0 libosmo-gsup-client0 libosmo-mslookup0
  libosmoabis10 libosmocore18 libosmoctrl0 libosmogsm17 libosmovty9 libsctp1
  libtalloc2 osmo-hlr osmocom-latest
0 upgraded, 14 newly installed, 0 to remove and 10 not upgraded.
Need to get 941 kB of archives.
After this operation, 2499 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 libmnl0 amd64 1.0.4-2 [12.3 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 libdbi1 amd64 0.9.0-5 [27.3 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal/main amd64 libdbd-sqlite3 amd64 0.9.0-8ubuntu1 [175 kB]
Get:4 https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04 ./ osmocom-latest 1.0.0 [1156 B]
Get:13 http://archive.ubuntu.com/ubuntu focal/main amd64 libsctp1 amd64 1.0.18+dfsg-1 [7876 B]
Get:14 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libtalloc2 amd64 2.3.1-0ubuntu0.20.04.1 [29.5 kB]
Get:6 https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04 ./ libosmogsm17 1.6.0 [209 kB]
Get:7 https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04 ./ libosmovty9 1.6.0 [101 kB]
Get:9 https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04 ./ libosmo-gsup-client0 1.4.0 [20.6 kB]
Get:10 https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04 ./ libosmo-mslookup0 1.4.0 [25.0 kB]
Err:5 https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04 ./ libosmocore18 1.6.0
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 134.76.12.6 443]
Err:8 https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04 ./ libosmoabis10 1.2.0
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 134.76.12.6 443]
Err:12 https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04 ./ osmo-hlr 1.4.0
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 134.76.12.6 443]
Err:11 https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04 ./ libosmoctrl0 1.6.0
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 134.76.12.6 443]
Fetched 608 kB in 2min 2s (4973 B/s)
E: Failed to fetch https://ftp.gwdg.de/pub/opensuse/repositories/network:/osmocom:/latest/xUbuntu_20.04/amd64/libosmocore18_1.6.0_amd64.deb  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 134.76.12.6 443]
E: Failed to fetch https://ftp.gwdg.de/pub/opensuse/repositories/network:/osmocom:/latest/xUbuntu_20.04/amd64/libosmoabis10_1.2.0_amd64.deb  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 134.76.12.6 443]
E: Failed to fetch https://ftp.gwdg.de/pub/opensuse/repositories/network:/osmocom:/latest/xUbuntu_20.04/amd64/libosmoctrl0_1.6.0_amd64.deb  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 134.76.12.6 443]
E: Failed to fetch https://ftp.gwdg.de/pub/opensuse/repositories/network:/osmocom:/latest/xUbuntu_20.04/amd64/osmo-hlr_1.4.0_amd64.deb  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 134.76.12.6 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c wget https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04/Release.key &&     apt-key add Release.key &&     echo "deb https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04/ ./" > /etc/apt/sources.list.d/osmocom-latest.list &&     apt-get update && apt-get -y install osmo-hlr' returned a non-zero code: 100
ERROR: Service 'osmohlr' failed to build : Build failed
```

This happened under `docker-compose build --no-cache`

Thanks
Best regards

**Comment by modyngs** [comment]
I do not have any osmocom devices but if there is a way to send sms without any thing more than B210 and one or two pcs that would be really great

**Comment by herlesupreeth** [comment]
the osmocom hlr and msc are core network components used in this repo to send SMS over SGs interface

I am not sure why the build is failing. Its appearing from not able to resolve certain repository. I sugges tto check your IPTables or DNS or your networking. It works just fine for me

**Comment by modyngs** [comment]
Thank you so much for adding an amazing Feature,

I can not connect UE's to the Network after Update

[CORE+RAN.zip](https://github.com/herlesupreeth/docker_open5gs/files/8140601/CORE%2BRAN.zip)

**Comment by modyngs** [comment]
@herlesupreeth 

I have tested the usual network on `[Append RPort to fix non-receiving of in-dialog replies](https://github.com/herlesupreeth/docker_open5gs/commit/95c1bb6826bf1719a0a06abfd3b5cf0d679b9313)`
and everything works great. UE connect and VoLTE call works smoothly.

But when i used the `[Bump tag to be used for UERANSIM to v3.2.6](https://github.com/herlesupreeth/docker_open5gs/commit/b8e03d4d0879853f5b46b4719a37925139d68b0b)`
UE cannnot attach to the Network (maybe because of new components)


Do i need to add subscriber information into hlr and msc in order to connect the UE?

P.s. I'm using [open5gs_hss_cx](https://github.com/herlesupreeth/docker_open5gs/compare/open5gs_hss_cx)  CX in WebUI

Thanks 
Best Regards

**Comment by s5uishida** [comment]
Hi @modyngs 

You need to login to the `osmohlr` container and register the IMSI and MSISDN, as described below.

https://ftp.osmocom.org/docs/latest/osmohlr-usermanual.pdf
`6.1 Example: Add/Update/Delete Subscriber via VTY`

**Comment by modyngs** [comment]
@s5uishida 
Thank you so much for the help

@herlesupreeth 

I have just one way SMS!

Just one UE can send messages to the other ( and can deliver that the message has arrived on the other side )
I mean the UE1 send messages and can confirm the message has arrived to the UE2 by delivery message but UE2 can not sent SMS to the UE1!  While both of them are able to start the VOLTE call.

Can you please give me some hint?

Core PCAP : https://drive.google.com/file/d/1kW3Y35R277UvXSUO0Yetwl3Dw5vIZ-ZC/view?usp=sharing
RAN PCAP : https://drive.google.com/file/d/1DtzLA-K0IrzTN58RsFA-yxBlyKDVGg44/view?usp=sharing

Thanks
Best regards

**Comment by sancom2930** [comment]
> Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
> Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
> Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
> Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
> Ign:5 https://downloads.osmocom.org/packages/osmocom:/latest/xUbuntu_20.04 ./ InRelease
> Err:6 https://downloads.osmocom.org/packages/osmocom:/latest/xUbuntu_20.04 ./ Release
>   Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 146.112.51.94 443]
> Reading package lists...
> E: The repository 'https://downloads.osmocom.org/packages/osmocom:/latest/xUbuntu_20.04 ./ Release' does not have a Release file.
> ERROR: Service 'osmohlr' failed to build: The command '/bin/sh -c wget https://downloads.osmocom.org/packages/osmocom:/latest/xUbuntu_20.04/Release.key --no-check-certificate &&     mv Release.key /etc/apt/trusted.gpg.d/osmocom-latest.asc &&     echo "deb https://downloads.osmocom.org/packages/osmocom:/latest/xUbuntu_20.04/ ./" > /etc/apt/sources.list.d/osmocom-latest.list &&     apt-get update && apt-get -y install osmo-hlr' returned a non-zero code: 100

I am also getting same error while "docker-compose build --no-cache" command.
Tried on 2 different Ubuntu VMs. Tried with local as well as root user. Still same issue.
I also changed Server from India-Server to Main-Server in Software repo from Ubuntu UI.

**Comment by herlesupreeth** [comment]
I believe it your host machine networking issue so closing this.
