### ISSUE TITLE
rtpengine build always failing

### ISSUE THREAD

**Issue by bluejade008** [herlesupreeth/docker_open5gs#70]
Dear sir,

when doing the command:
"cd ..
set -a
source .env
docker-compose build --no-cache",
it was always failing. 
I checked the logs and find out that rtpengine failing to build blocked the whole docker-compose building procedure. And I tried to build up only rtpengine images by "cd ../rtpengine    docker build -t temprtpengine:v0.1 .:, the same problems come up, would you like to instruct me to build the docker-open5g, I'm very interested in the docker 5g together with IMS.

Thanks so much.

--------------------------------------------------------------------
Fetched 198 MB in 1min 50s (1801 kB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/libswresample3_4.2.4-1ubuntu0.1_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/libb/libbluray/libbluray2_1.2.0-1_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/libb/libbs2b/libbs2b0_3.1.0+dfsg-2.2build1_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/f/flite/libflite1_2.1-release-3_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/s/serd/libserd-0-0_0.30.2-1_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/s/sord/libsord-0-0_0.16.4-1_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/libv/libvidstab/libvidstab1.1_1.1.0-2_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/n/norm/libnorm1_1.5.8+dfsg2-2build1_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/libp/libpgm/libpgm-5.2-0_5.2.122~dfsg-3ubuntu1_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/z/zeromq3/libzmq5_4.3.2-2ubuntu1_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libb/libb-hooks-op-check-perl/libb-hooks-op-check-perl_0.22-1build2_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/libb/libbdplus/libbdplus0_0.1.2-3_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/m/module-assistant/module-assistant_0.11.10_all.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/libavcodec-extra_4.2.4-1ubuntu0.1_amd64.deb  Connection failed [IP: 91.189.88.152 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get update &&       apt-get -y install git vim tmux dpkg-dev debhelper libxtables-dev default-libmysqlclient-dev gperf libavcodec-dev libavfilter-dev libavformat-dev      libavutil-dev libbencode-perl libcrypt-openssl-rsa-perl libcrypt-rijndael-perl libdigest-crc-perl libdigest-hmac-perl                                    libevent-dev libhiredis-dev libio-multiplex-perl libio-socket-inet6-perl libiptc-dev libjson-glib-dev libnet-interface-perl                                     libpcap0.8-dev libpcre3-dev libsocket6-perl libspandsp-dev libssl-dev libswresample-dev libsystemd-dev libxmlrpc-core-c3-dev                                    markdown dkms module-assistant keyutils libnfsidmap2 nfs-common rpcbind libglib2.0-dev zlib1g-dev libavcodec-extra             libcurl4-openssl-dev netcat-openbsd netcat iptables iproute2 net-tools iputils-ping libconfig-tiny-perl libwebsockets-dev' returned a non-zero code: 100
--------------------------------------------------------------------------------------------------------------------------

**Comment by herlesupreeth** [comment]
> Connection failed [IP: 91.189.88.152 80]

This is a clue that some firewall/wrong iptables is blocking access to ubuntu servers to fetch the softwares. Its your networking issue
