### ISSUE TITLE
Issue with connecting phones. Location Update Reject

### ISSUE THREAD

**Issue by kevin21754** [herlesupreeth/docker_open5gs#71]
Sir, when following the read.me, I experience the location update reject. We are able to see the UE with proper IMSI attempt to connect and immediately get kicked off. Any ideas?

**Comment by kevin21754** [comment]
![image](https://user-images.githubusercontent.com/89085156/156209054-20038825-f036-424b-9f61-62d83ea0e3a6.png)
[enb.zip](https://github.com/herlesupreeth/docker_open5gs/files/8163207/enb.zip)
[enb_s1ap.zip](https://github.com/herlesupreeth/docker_open5gs/files/8163208/enb_s1ap.zip)

**Comment by herlesupreeth** [comment]
I have introduced osmomsc and osmohlr into docker_open5gs for sending SMS over SGs interface hence you need to add IMSI and associated MSISDN into osmohlr

**Comment by herlesupreeth** [comment]
Refer to this comment - https://github.com/herlesupreeth/docker_open5gs/issues/69#issuecomment-1051623419

**Comment by kevin21754** [comment]
Sir, still having the same issue. We can see the failure with osmomhlr.  Understand that the error orignates there. 

![image](https://user-images.githubusercontent.com/89085156/158403183-abea8ce1-54a9-4140-baf3-bc9a30a9978a.png)

However, we are unable to access osmohlr like in OsmoHLR documentation. 

![image](https://user-images.githubusercontent.com/89085156/158407632-912b0c53-45d4-44ef-b54f-97147eb08c1a.png)

Any ideas of how else to add IMSI information to osmohlr?  Thank you so much for your help.

**Comment by herlesupreeth** [comment]
First you need to login to osmohlr as below

docker exec -ti osmohlr bash

then execute the telnet command
