### ISSUE TITLE
Change IP address range for ims bearer

### ISSUE THREAD

**Issue by yasuhirom** [herlesupreeth/docker_open5gs#73]
Hi,

I would like to ask you to confirm,
To solve IP range conflict between eNB connection network and Open5GS assigns to ims bearer. (I use external eNB) I made attached modification. change IP range for ims bearer to 192.168.102.1/24
Is it enough and collect  ?

After this modification and re-build, everything works fine. UE can attach. can access to internet. can make VoLTE call between two.
[diff_changeIpRangeForIms.txt](https://github.com/herlesupreeth/docker_open5gs/files/8237010/diff_changeIpRangeForIms.txt)
.

**Comment by s5uishida** [comment]
Hi @yasuhirom 

IP addresses are assigned to APN `internet` and `ims` for each device connected to the core network, so it depends on whether `/24` meets your requirements.

In my case, it was enough to try VoLTE and SMS.

**Comment by yasuhirom** [comment]
Hi @s5uishida 

Thank you for your confirmation.
Sorry "enough" means my modification is covered all necessary change IP address range or need more modification.
Change 192.168.101.1/24 to 10.45.6.1/24 may more clear.

Yes, how many UE can be handled is , /24 is enough for my case.

**Comment by s5uishida** [comment]
Hi @yasuhirom 

I'm sorry I misunderstood.

BTW, if you want to try VoLTE easily, I recommend the `open5gs_hss_cx` branch without FHoSS.
If you want to try **SMS over IMS** in addition to VoLTE using IMS (Kamailio), you need to use  the `master` branch.

You may try **SMS over SGs** on either branch.

FYI.

**Comment by herlesupreeth** [comment]
For ue subnet change, you need to modify upf.yaml and smf.yaml and also in upf_init.sh file with the subnet you wnat

**Comment by yasuhirom** [comment]
@herlesupreeth 

pcscf_init.sh and rtpengine_init.sh as below. Is it unnecessary to modify ?

```
# Add static route to route traffic back to UE as there is not NATing
ip r add 192.168.101.0/24 via ${UPF_IP}
```

**Comment by yasuhirom** [comment]
hi, @s5uishida 

Thank you for your info.
Regarding SMS, I already got working by over SGx interface on non docker environment Open5GS w/o Kamailio.

**Comment by herlesupreeth** [comment]
Yes, you need to modify there as well

**Comment by yasuhirom** [comment]
@herlesupreeth 

thank you for your confirmation.
