### ISSUE TITLE
Bad voice quality in one way

### ISSUE THREAD

**Issue by Ablandin35** [herlesupreeth/docker_open5gs#75]
Hello,

I deployed volte setup with srsenb+USRP B210 and two Oneplus5 devices.
When device A calls device B, voice quality is very bad on device A.
Did you observe this behaviour? Is there specific settings in enodeb to support volte?
I attach pcap file.
[volte_call.zip](https://github.com/herlesupreeth/docker_open5gs/files/8262929/volte_call.zip)

**Comment by herlesupreeth** [comment]
Nope, i haven't observed bad voice quality even while using srsRAN eNB. I would suspect the power saving modes of the machine. I usually turned all of them off. You can set CPU governor to "performance" and see if that helps

**Comment by Ablandin35** [comment]
CPU governor is already set to "performance".
I will try to turn off power saving mode.

**Comment by Ablandin35** [comment]
Thanks Supreeth.
I have no more this issue with the release 21.04.
