### ISSUE TITLE
Delete bearer request not answered

### ISSUE THREAD

**Issue by Ablandin35** [herlesupreeth/docker_open5gs#76]
Hello,

I deployed volte setup with srsenb+USRP B210 and two Oneplus5 devices.
Delete bearer request is never answered, then I can't make a new call because bearer was not released.
Did you experience this issue?
I attach the traces.
[volte_call.zip](https://github.com/herlesupreeth/docker_open5gs/files/8263082/volte_call.zip)

**Comment by herlesupreeth** [comment]
Its a bug on srsenb, its not responding to E-RABReleaseCommand from MME. Which tag of srsRAN are you using?

**Comment by Ablandin35** [comment]
Hello,
I am using this srsRAN release:

srsenb --version

Built in Release mode using commit d045213fb on branch HEAD.

---  Software Radio Systems LTE eNodeB  ---

Version 19.12.0

**Comment by herlesupreeth** [comment]
I would suggest to use the tag release_21_04 as its fixed there

**Comment by Ablandin35** [comment]
Thanks Supreeth.
It is now fixed with the release 21.04.
