### ISSUE TITLE
About Kamailio 5.5

### ISSUE THREAD

**Issue by s5uishida** [herlesupreeth/docker_open5gs#79]
Hi @herlesupreeth 

Please let me know a little.

I found a branch for version 5.5 in your Kamailio repository. 
Could it be used for VoLTE and SMS over IMS with docker_open5gs?

If it works, I'll try it.

Best regards,

--Shigeru

**Comment by herlesupreeth** [comment]
@s5uishida yes, it could be but the configuration files needs to be tweaked as bit (only kamailio_pcscf config files)

**Comment by s5uishida** [comment]
Hi @herlesupreeth 

Thank you very much for your information.

I changed the Kamailio branch to `5.5` and tried SMS over IMS.
As a result, garbled characters occurred as in `5.3`.

Also, I have not changed anything for `docker_open5gs/pcscf/*`.

Thanks again!

--Shigeru
