### ISSUE TITLE
VoLTE issue Internet APN works but no IMS 

### ISSUE THREAD

**Issue by MauricioV** [herlesupreeth/docker_open5gs#82]
Dear @herlesupreeth,

I'm testing VoLTE but on my scenario I only have internet, SMS but no voice.

My scenario is the following

```
     eNodeB                Docker host - 172.22.0.0/24
    ---------             -------------
   |         |           |             |
   |         |           |             |
    ---------             -------------
        |                       |
-------------------------------------------------------
       .110                     .100      192.168.0.0/24
```

I have programmed the sysmoISIM-SJA2 card with the following parameters:

ADM1		45314232
ICCID 		8988211000000100023
IMSI	                001010000010002
MCC		001
MNC		01
Ki			DA4EDB6503743D404DA2F91A4446C26F
OPC			1CFA68FDE88DCA322C1BF33D0F2709A0
ACC    		0004
MSISDN		10002
IMS DOMAIN 	ims.mnc001.mcc001.3gppnetwork.org
IMPI		        001010000010002@ims.mnc001.mcc001.3gppnetwork.org
IMPU		sip:001010000010002@ims.mnc001.mcc001.3gppnetwork.org
PCSCF 		pcscf.ims.mnc001.mcc001.3gppnetwork.org

On the HSS I have:
![image](https://user-images.githubusercontent.com/6804880/159737106-5f6015d3-db9a-4147-85da-6b0707e0623f.png)

On the HLR:
![image](https://user-images.githubusercontent.com/6804880/159737501-93f8dbce-a23d-4aae-9a71-3f68d5daf499.png)

On the IMS:

IMSU:
![image](https://user-images.githubusercontent.com/6804880/159737614-5caa5a47-80c6-4e70-8d43-d17df1637ddf.png)

IMPI:
![image](https://user-images.githubusercontent.com/6804880/159737696-6173b770-8e4a-4ce7-bdf4-5f9a666be002.png)

IMPU:
![image](https://user-images.githubusercontent.com/6804880/159737828-fffb8862-17f6-41b2-8de5-8ca79c33dc06.png)

![image](https://user-images.githubusercontent.com/6804880/159737867-6f9257ae-2265-4f81-8401-6be56f500ba1.png)

![image](https://user-images.githubusercontent.com/6804880/159737939-3cc4fd80-ad3f-4417-8814-840f26729c71.png)

The configs applyed on the srsLTE eNB:
![image](https://user-images.githubusercontent.com/6804880/159738355-014e3b41-19ba-4aaa-8fda-baa6368f52ec.png)

The routes on eNB:
![image](https://user-images.githubusercontent.com/6804880/159738777-516d1f90-a8d6-4af6-a7e5-5fdef3295f0e.png)

The routes on docker host:
![image](https://user-images.githubusercontent.com/6804880/159738971-04d87208-16b8-476d-892a-2b1d0c8b3391.png)

This are my logs:
[log.zip](https://github.com/herlesupreeth/docker_open5gs/files/8334483/log.zip)

My Wireshark (v3.2.3) capture:
https://drive.google.com/file/d/1mlgm215w4-NVwgOzuiPb4uF5Mj2NVc0C/view?usp=sharing

My UE configuration (Samsung Galaxy S21+ 5G):
![Screenshot_20220323-154910_Call settings](https://user-images.githubusercontent.com/6804880/159741884-a8a30ac9-e2c9-4e45-869e-90751e5181d7.jpg)

![Screenshot_20220323-154921_Settings](https://user-images.githubusercontent.com/6804880/159741951-71f34cec-19a4-4022-860a-68bb8dd45a38.jpg)

![Screenshot_20220323-154925_Settings](https://user-images.githubusercontent.com/6804880/159741970-a39c23e0-06fa-485f-8ad2-f9ac83aa3aff.jpg)

![Screenshot_20220323-154935_Settings](https://user-images.githubusercontent.com/6804880/159741984-dccdf7c1-b858-4fff-b4ec-8940d6a17882.jpg)

![Screenshot_20220323-154946_CoIMS](https://user-images.githubusercontent.com/6804880/159742042-7ce75301-9ebe-4059-b0a5-6c2d3130d5d1.jpg)

![Screenshot_20220323-155007_Settings](https://user-images.githubusercontent.com/6804880/159742082-0f281109-e7a9-4b93-9032-88157529f11f.jpg)

**Comment by herlesupreeth** [comment]
![image](https://user-images.githubusercontent.com/4115839/159873337-3048a643-79a8-4de3-a4e1-0bbd5f8d543b.png)


Its because you have not configured your eNB to accept E-RAB with QCI 5

**Comment by herlesupreeth** [comment]
configured drb.conf of your srsLTE eNB as in this repository

**Comment by MauricioV** [comment]
Thank you so much Herle, now It's working. The version of srsLTE that I had (21.10) did not recognize the drb.conf file. So I switch to 21.04.
