### ISSUE TITLE
"docker-compose -f srsenb.yaml up -d && docker attach srsenb" ERROR

### ISSUE THREAD

**Issue by fj0831ec** [herlesupreeth/docker_open5gs#83]
Hello,

After building the srsENB container following the command in the readme
docker-compose -f srsenb.yaml build --no-cache

I tried to start the container
docker-compose -f srsenb.yaml up -d && docker attach srsenb

And got the following error:

$docker-compose -f srsenb.yaml up -d && docker attach srsenb
WARNING: Found orphan containers (mme, hss, smf, rtpengine, mysql, smsc, fhoss, sgwc, amf, udm, pcrf, icscf, udr, scscf, bsf, upf, ausf, pcf, nssf, osmomsc, pcscf, osmohlr, mongo, dns, webui, sgwu, nrf) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Removing srsenb
Recreating 316f629a00da_srsenb ... error

ERROR: for 316f629a00da_srsenb  Cannot start service srsenb: Invalid address 172.22.0.22: It does not belong to any of this network's subnets

ERROR: for srsenb  Cannot start service srsenb: Invalid address 172.22.0.22: It does not belong to any of this network's subnets
ERROR: Encountered errors while bringing up the project.

Am I missing some configuration? 

Thanks!

**Comment by s5uishida** [comment]
Hi @fj0831ec 

For your reference, as follows is an example of a combination of USRP B210 and srsENB.

https://github.com/MauricioV/docker_open5gs

**Comment by herlesupreeth** [comment]
@fj0831ec I believe you are trying to run srsenb in another VM than the EPC. In order to do that steps are quite different

**Comment by fj0831ec** [comment]
Hi @herlesupreeth

Thank you for answering.
I am trying to set up EPC and eNB on the same machine.
And SDR uses LimeSDR.
I proceeded with the procedure while looking at the README of docker_open5gs.
Why are you running srsenb on a VM other than the EPC?
Where did I make a mistake in the procedure?

**Comment by herlesupreeth** [comment]
@fj0831ec can you please share your .env file or rather can you run the below command in docker_open5gs folder and send me the output?

`git diff`

**Comment by fj0831ec** [comment]
Hi @herlesupreeth

Thank you for answering.
Was self resolved. (ENB was able to start normally)
I don't know why it was resolved. This is my first time using Docker Compose.
I ran the following command from -remove-orphans, as described in the warning section.
It is described below together with the execution result of eNB and the result of git diff.


docker-compose -f srsenb.yaml up -d && docker attach srsenb
WARNING: Found orphan containers (upf, mme, sgwu, rtpengine, fhoss, nssf, pcrf, mongo, icscf, sgwc, udm, bsf, osmohlr, mysql, pcscf, smsc, amf, pcf, smf, webui, osmomsc, udr, nrf, ausf, hss, dns, scscf) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating srsenb ... done
Soapy has found device #0: addr=1d50:6108, driver=lime, label=LimeSDR-USB [USB 3.0] 90726074D0C31, media=USB 3.0, module=FX3, name=LimeSDR-USB, serial=00090726074D0C31, 
Selecting Soapy device: 0
Detected LimeSDR. Consider using LTE rates for better RF performance.
Either compile with '-DUSE_LTE_RATES=True' or start srsENB/srsUE with '--expert.lte_sample_rates=true'
[INFO] Make connection: 'LimeSDR-USB [USB 3.0] 90726074D0C31'
[INFO] Reference clock 30.72 MHz
[INFO] Device name: LimeSDR-USB
[INFO] Reference: 30.72 MHz
[INFO] LMS7002M register cache: Disabled
Setting up Rx stream with 1 channel(s)
Setting up Tx stream with 1 channel(s)
[INFO] RX LPF configured
[INFO] Filter calibrated. Filter order-4th, filter bandwidth set to 5 MHz.Real pole 1st order filter set to 2.5 MHz. Preemphasis filter not active
[INFO] TX LPF configured
Available device sensors: 
 - clock_locked
 - lms7_temp
Available sensors for Rx channel 0: 
 - lo_locked
State of gain elements for Rx channel 0 (AGC not supported):
 - TIA: 9.00 dB
 - LNA: 30.00 dB
 - PGA: -7.00 dB
State of gain elements for Tx channel 0 (AGC not supported):
 - PAD: 0.00 dB
 - IAMP: 0.00 dB
Rx antenna set to LNAL
Tx antenna set to BAND1

==== eNodeB started ===
Type <t> to view trace
[INFO] RX LPF configured
[INFO] Filter calibrated. Filter order-4th, filter bandwidth set to 5.76 MHz.Real pole 1st order filter set to 2.5 MHz. Preemphasis filter not active
[INFO] TX LPF configured
Setting frequency: DL=2660.0 Mhz, UL=2540.0 MHz for cc_idx=0 nof_prb=25
[INFO] Tx calibration finished
[INFO] Rx calibration finished

$git diff
diff --git a/.env b/.env
index c5efbc0..8ad6395 100644
--- a/.env
+++ b/.env
@@ -5,7 +5,8 @@ MCC=001
 MNC=01
 
 TEST_NETWORK=172.22.0.0/24
-DOCKER_HOST_IP=192.168.1.223
+# DOCKER_HOST_IP=192.168.1.223
+DOCKER_HOST_IP=192.168.11.3
 
 # MONGODB
 MONGO_IP=172.22.0.2
diff --git a/srslte/enb.conf b/srslte/enb.conf
index 60936f4..0899620 100644
--- a/srslte/enb.conf
+++ b/srslte/enb.conf
@@ -67,7 +67,7 @@ rx_gain = 40
 #dl_earfcn = 6300
 #tx_gain = 56
 #rx_gain = 38
-#device_name = soapy
+device_name = soapy
 #device_args = rxant=LNAW,txant=BAND2
 #device_args = clock=external
