### ISSUE TITLE
IMS Registration issue

### ISSUE THREAD

**Issue by knt141** [herlesupreeth/docker_open5gs#84]
Hello @herlesupreeth, and thank you for making this docker! It really helps beginners like myself to play/learn in a format that works.

### Environment

**Device**: BladeRF
**eNodeB**: srsRAN 21.10, on host
**SIM**: Using SysmoISIM-SJA2
**Phones**: Rooted Samsung S9 (Android 10) / Pixel 4a (AOSP userdebug, Android 12)

Docker containers are all running, except srsRAN (formerly srsLTE), which runs on the host (and mme_addr points to docker), as docker srsran did not work with device_name = bladeRF (due to missing drivers in docker build). 
I am of course using the configuration of docker_open5gs for srsenb, however, I had to use most recent srsRAN (21.10), as 21.04 caused open5gs mme to report ASN/PDU decode failure (separate issue). I had to make one change to the enb.conf which was drb.conf rename.

srsenb informs us that s1ap connectivity is successfully established, and this is reflected in MME logs.

IMSI/MSISDN/Keys/APN details in open5gs web interface configured (as a subscriber, not profile) and also on FHoSS.

### Issue
UE connects to network fine as 4G, however I never see any SIP register (IMS), and when I try to make a call, the UE drops from the network immediately. Checking in wireshark makes it seem like the UE is trying to perform cs-fallback, which isn't configured. In the UE logs, some hints are provided that seem like the UE support for VoLTE  are correct (mIsSim1VolteSettingOn = true):

```
 ImsCommonModel: [D] (mIsSim1VolteSettingOn : true), (mIsLvcAvailable : false), (mIsSim1VolteAvailable : false), (mIsSim1VoWiFiEnabled : false), (mIsImsRegistered : false), (mRcsSim1Registered :false), (mIsSim1RcsUpSupported :true), (mIsSim1SupportVideoCapability :false), (mIsSupportRcsPhase2 :false), (mIsMessageRcsSupported :true), (mIsDualRcsSupported :false), (mIsLvcSettingOn : true), (mIsSim1MobileDataEnabled : true), (mIsDataRoamingEnabled : true)
 ```

### Things I tried
- Two separate sim cards (same batch)
- deleting APNs on phone and just adding 'ims' APN
- Two separate phones

[pcap.zip](https://github.com/herlesupreeth/docker_open5gs/files/8545885/pcap.zip)
Built from: s1ap || gtpv2 || pfcp || diameter || diameter.3gpp || sip

**Comment by s5uishida** [comment]
Hi @knt141 

According to pcap No.34, your UE's setting is `CS Voice only`, not `IMS PS voice preferred, CS Voice as secondary` (for example).
```
34	1.624415	172.22.0.1	172.22.0.9	S1AP/NAS-EPS	224	InitialUEMessage, Attach request, PDN connectivity request
...
Voice Domain Preference and UE's Usage Setting
    Element ID: 0x5d
    Length: 1
    0000 0... = Spare bit(s): 0
    .... .0.. = UE's usage setting: Voice centric
    .... ..00 = Voice domain preference for E-UTRAN: CS Voice only (0)
```

**Comment by knt141** [comment]
Hi Mr Ishida, thank you for responding with that hint!

When a Sim from a telecom local provider is used with this same UE, it appears IMS/VoLTE registers successfully.

I am guessing there is there something I need to do on the UE to convince it that it should use IMS for the MNC/MCC pair I am using, I will investigate this :) I had assumed CoIMS was not necessary for more modern Sims (SysmoISIM-SJA2), so that will be my starting point. There is probably an XML file on Android with MCC/MNC to map network features.

Thank you again for your response!

-------- Original Message --------

**Comment by knt141** [comment]
Hi @s5uishida, 

I updated the UE to use APN detail based on https://nickvsnetworking.com/android-apn-master-config/ and found that the UE connects with the correct APN and APN Types, in our wireshark we now see voice and IMS in the InitialUeMessage, yet the call seems to try to fallback to CS, it might be that I need to use CoIMS to configure further properties that isnt available via APN configuration and for this purpose I ordered a SIM reader/write online (but i think its a few weeks away). 

```
Voice Domain Preference and UE's Usage Setting
    Element ID: 0x5d
    Length: 1
    0000 0... = Spare bit(s): 0
    .... .0.. = UE's usage setting: Voice centric
    .... ..10 = Voice domain preference for E-UTRAN: CS voice preferred, IMS PS Voice as secondary (2)
```

Here is PCAP:
[github2.zip](https://github.com/herlesupreeth/docker_open5gs/files/8560124/github2.zip)

**Comment by s5uishida** [comment]
Hi @knt141 

There is a default EPS Bearer with QCI=5 (APN=`ims`), but a default EPS Bearer with QCI=9 has not been established. (For example, APN=`internet`)

Also, I think `CS voice preferred, IMS PS Voice as secondary` is the opposite of CSFB.

**Comment by knt141** [comment]
Sorry it took a while to get a sim reader. I confirmed that in CoIMS it now has carrier privileges and has correct carrierId (I added to carrier_list.pb, which was parsed by telephony and carrier DB was updated).

In the SIM settings on the phone I see VoLTE enabled. However, no IMS registration occurs, and under CoIMS => Testing mode => IMS Service Status, I see "Not registered". There is no SIP packet in PCAP.

[pca.zip](https://github.com/herlesupreeth/docker_open5gs/files/8674103/pca.zip)

Screenshots:

#### Testing mode 
![image](https://user-images.githubusercontent.com/102111224/167969560-2691097e-ed4d-4497-b61e-8060f604bb1e.png)

#### Testing mode - IMS registration status
![image](https://user-images.githubusercontent.com/102111224/167969610-add1b277-be66-4370-8620-65a5d4a9e6e6.png)



#### SIM system status
![image](https://user-images.githubusercontent.com/102111224/167969644-34417edd-66c7-420c-82ff-f48e40cbced4.png)


#### CoIMS 
![image](https://user-images.githubusercontent.com/102111224/167969676-5c28f744-0725-47b4-a9f0-dc6de3f21432.png)

**Comment by herlesupreeth** [comment]
@knt141 I would strongly recommend to re-program the SIM card for PLMN 001 01..there VoLTE is enabled even at firmware level for most phones.

In the above screenshot I do see that carrier privileges is enabled, however I have seen it does not work for some of the PLMNs other than 001 01

**Comment by herlesupreeth** [comment]
Oh wait..In the trace you attached, i see that UE is attaching to 'ims' APN. But I also see that you have wrongly configured the APN in the phone.

You have configured default APN as 'ims' which is wrong, rather you should have default APN as 'internet' and IMS APN as 'ims'

**Comment by knt141** [comment]
hi @herlesupreeth, I will re-program the sim card for PLMN 001 01 and retry (but this will take some time as it will require re-configuring FHoSS which is horrible), as changing the APN configuration as suggested didn't seem to change the result:
```
 <apn carrier="Open5gs"
    carrier_id ="10032"
    mcc="999"
    mnc="70"
    apn="ims"
    type="ims" 
    user_visible="true"
    />
  <apn carrier="Open5gs"
    carrier_id = "10032"
    mcc="999"
    mnc="70"
    apn="internet"
    type="default,supl"
    user_visible="true"
    />
```
[pcap.zip](https://github.com/herlesupreeth/docker_open5gs/files/8683729/pcap.zip)

**Comment by herlesupreeth** [comment]
@knt141 in the above pcap, the phone is not even attempting to attach to ims APN

**Comment by knt141** [comment]
Hi @herlesupreeth , sorry for the late reply, I obtained a sim programmer and reprogrammed the card to be PLMN 001/01 using pySim-prog.py. I configured APN on UE and open5gs interface (both web and smf/upf.yaml) as: apnName=VZWINTERNET, apnType=default and apnName=ims, apnType=ims. IMSI was also added to osmo-hlr via vty with 3g ki/opc (just coz I saw error in log relating to this, we are not trying to configure 3g)

`UplinkNASTransport, PDN connectivity request` correctly shows ims APN request, yet we are still seeing the CS fallback request when a call is made, with apparently no errors before hand (except GTP dns errors).

CoIMS reports carrier privileges and dots => phone info informs us that VoLTE is enabled and provisioned:
Data Service: Connected
Data network Type: LTE
Voice Service: In service
Voice Network Type: LTE

Checking IMS status via CoIMS shows that the phone is not yet registered (and I observe no SIP packet in pcap).

[pcap.zip](https://github.com/herlesupreeth/docker_open5gs/files/9089168/pcap.zip)

**Comment by herlesupreeth** [comment]
I see that phone is now attempting to connect to IMS APN and it even sends a TCP SYN packet to 172.22.0.21 but it looks like there is some kind of either wrong configuration or loop .. i see a GTP packet coming from 172.22.0.1 port 2152 to 172.22.0.1 port 2152

![image](https://user-images.githubusercontent.com/4115839/178441767-a385cb13-0e0c-478e-bf3a-0a2db9ba4f3c.png)


please check your .env file for incorrect configuration

**Comment by knt141** [comment]
Hmm that syn is to port 5060, but I missed it as I wasnt looking at GTP properly. .21 is PCSCF_IP according to .Env (same as https://github.com/herlesupreeth/docker_open5gs/blob/master/.env#L68). That would make sense that IMS is unregistered but LTE is connected.

I will try to run enb inside same docker (it's currently running on docker host 172.22.0.1:2152 bound to same docker network), that should rule out any weird loop potentials

-------- Original Message --------

**Comment by knt141** [comment]
Ok it is now working! After moving srslte/enb to docker, and resetting .env to be default (minus first few vars), LTE on pixel device and IMS registers. Next part will be working out calls, but I think this issue can be closed.

Ultimately it came down to user error (or PLMN 001/01!) :)
