### ISSUE TITLE
no sdr hardware (or cheapest)?

### ISSUE THREAD

**Issue by gmaruzz** [herlesupreeth/docker_open5gs#86]
Hello,

is it possible to test this setup without using SDR hardware?

If yes, how?

If SDR hardware is required, what is the cheapest one known to work?

Thanks in advance for all replies!

**Comment by gmaruzz** [comment]
(a cheap SDR hardware would be ok, if needed)

**Comment by herlesupreeth** [comment]
I have used LimeSDR Mini v1 and LimeSDR USB with srsRAN and they worked just fine (although I have heard others complain about it not working). Those two are the cheapest SDRs on which you could try VoLTE. The next cheapest SDR would be blade RF 

> But at moment, all I want to do is:
> 
>     have an IMS system working
>     connect my AS to it
>     use an IMS softphone (eg Bolghe) for testing services from AS

You can achieve this even without the SDR by using the ZMQ link between the srsRAN eNB and srsRAN UE. But the files in this repo are solely configured to work with a SDR. (https://docs.srsran.com/en/latest/app_notes/source/zeromq/source/index.html)

**Comment by gmaruzz** [comment]
I'm looking to options for buying limesdr, but it seems they will ship in September 2022, not sooner, from crowdsupply

there are other online supplier that you know about?

**Comment by herlesupreeth** [comment]
Mouser electronics is an option..but slightly expensive than crowdsupply

**Comment by gmaruzz** [comment]
So nice from you, thanks!
Unfortunately, same ETA :/
