### ISSUE TITLE
Build Fails: osmocom Release.key expired (EXPKEYSIG)

### ISSUE THREAD

**Issue by hussam-qasem** [herlesupreeth/docker_open5gs#89]
Building [`osmohlr`](https://osmocom.org/projects/cellular-infrastructure) fails due to expired key, it seems:
```
% docker-compose build --no-cache osmohlr

Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:2 https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04 ./ InRelease [1603 B]
Err:2 https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04 ./ InRelease
  The following signatures were invalid: EXPKEYSIG 62EB1A0917280DDF network OBS Project <network@build.opensuse.org>
```

Checking the [`Release.key`](https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04/Release.key)
```
wget https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04/Release.key
gpg --list-packets Release.key
```
Not sure if I'm on the right track here:
```
date -d @1585641835
```
Then add `8y259d15h59m`?

**Comment by herlesupreeth** [comment]
@hussam-qasem let me check at my end and get back to you

**Comment by hussam-qasem** [comment]
Dear @herlesupreeth. Please disregard. It appears the [key was updated this morning](https://download.opensuse.org/repositories/network:/osmocom:/latest/xUbuntu_20.04/)!
