### ISSUE TITLE
REMOTE Request Duplicated. Discard! for step 1 type 176 peer. 

### ISSUE THREAD

**Issue by zikkuratti** [herlesupreeth/docker_open5gs#90]
@herlesupreeth Greetings comrade! Have you ever encountered a connection failure after the fourth call in VoLTE? In my opinion, SGW-U loses the tunnel bearer from UPF FID key to ENB. I use a configuration identical to this branch and I can't debug for a month. I will be grateful for your advice.

**Comment by herlesupreeth** [comment]
Hey @zikkuratti if you could send me a wireshark trace for that scenario I can take a look

**Comment by zikkuratti** [comment]
look at that, install  UMLet i make an lil card of main lines of processes ( also im confused why requests all go double from to dest u got same? 
[4Git.zip](https://github.com/herlesupreeth/docker_open5gs/files/9053748/4Git.zip)
