### ISSUE TITLE
Unable to bring AMF up in SA-Deploy Model

### ISSUE THREAD

**Issue by giangdh1009** [herlesupreeth/docker_open5gs#93]
I tried to Run SA Model with gnodeB at another machine, but unable to bring amf up? 
docker_open5gs$ docker-compose -f sa-deploy.yaml up 
Creating volume "docker_open5gs_mongodbdata" with default driver
Creating nrf   ... done
Creating mongo ... done
Creating webui ... done
Creating bsf   ... done
Creating smf   ... done
Creating ausf  ... done
Creating nssf  ... done
Creating udr   ... done
Creating pcf   ... done
Creating udm   ... done
Creating upf   ... done
Creating amf   ... 
Creating amf   ... error

ERROR: for amf  Cannot start service amf: driver failed programming external connectivity on endpoint amf (352a58f6e6f8a0ff04eac3a6bbf825c698554003e3b614950b6c6b4183535ce9): Error starting userland proxy: protocol not supported

ERROR: for amf  Cannot start service amf: driver failed programming external connectivity on endpoint amf (352a58f6e6f8a0ff04eac3a6bbf825c698554003e3b614950b6c6b4183535ce9): Error starting userland proxy: protocol not supported
ERROR: Encountered errors while bringing up the project.

**Comment by giangdh1009** [comment]
smf      | 07/26 02:31:59.436: [diam] ERROR: pid:Main in fd_sctp_create_bind_server@sctp.c:829: ERROR: in '(*sock = socket(family, SOCK_STREAM, IPPROTO_SCTP))' :    Protocol not supported
smf      |  ((null):0)
smf      | 07/26 02:31:59.436: [diam] ERROR: pid:Main in fd_cnx_serv_sctp@cnxctx.c:181: ERROR: in '(fd_sctp_create_bind_server( &cnx->cc_socket, cnx->cc_family, ep_list, port ))' : Protocol not supported
smf      |  ((null):0)
smf      | 07/26 02:31:59.436: [diam] ERROR: pid:Main in fd_servers_start@server.c:355: ERROR: in '(s->conn = fd_cnx_serv_sctp(fd_g_config->cnf_port, empty_conf_ep ? ((void *)0) : &fd_g_config->cnf_endpoints))' : Protocol not supported
smf      |  ((null):0)
smf      | 07/26 02:31:59.436: [diam] ERROR: pid:Main in fd_core_start_int@core.c:300: ERROR: in '((fd_servers_start()))' : Protocol not supported
smf      |  ((null):0)
smf      | 07/26 02:31:59.436: [diam] ERROR: pid:Main in ogs_diam_start@init.c:71: ERROR: in '(fd_core_start())' :      Protocol not supported
smf      |  ((null):0)
smf      | 07/26 02:31:59.546: [smf] FATAL: smf_fd_init: Assertion `rv == 0' failed. (../src/smf/fd-path.c:50)
smf      | 07/26 02:31:59.546: [core] FATAL: backtrace() returned 7 addresses (../lib/core/ogs-abort.c:37)

**Comment by herlesupreeth** [comment]
It could be due to two things

1. You are running old version of docker-ce and docker-compose
2. Or, you are running it on non-linux platform where SCTP is not supported (e.g. windows)

**Comment by giangdh1009** [comment]
i change the ubuntu image, then it worked , it seem the old ubuntu OS didn't support SCTP but don't know to check. Thanks for your support :)
