### ISSUE TITLE
Kamailio bug in SMSOPS: body < 3 characters not transmitted (empty) 

### ISSUE THREAD

**Issue by gmaruzz** [herlesupreeth/docker_open5gs#97]
as per: https://github.com/kamailio/kamailio/issues/3211 

seems to me that if cellphone sends an SMS shorter than 3 characters (eg: "aa") it is sent as empty string

this maybe because of some snafu in PDU "payload" management in smsops_impl.c , pointer arithmetic between different characters' coding (ASCII, UTF8, UCS2, etc)

(tested with OnePlus 5t, 6t, Open5GS, SRSLTE, USRP201)

[sms.zip](https://github.com/herlesupreeth/docker_open5gs/files/9290484/sms.zip)
in the zip file two SMSs, one with payload "A" and one with payload "ABC"

I see after 5.3 there are at least 3 new commits related to payload management...
maybe is already fixed? can you check it out?

https://github.com/kamailio/kamailio/commits/master/src/modules/smsops

**Comment by gmaruzz** [comment]
I confirm, is fixed in Kamailio 6.1
would be nice to backport the fix

[sms_one_character_fixed_in_6.1.zip](https://github.com/herlesupreeth/docker_open5gs/files/9291090/sms_one_character_fixed_in_6.1.zip)

**Comment by gmaruzz** [comment]
thanks to you!

**Comment by herlesupreeth** [comment]
It's done. Can you please re-compile kamailio base image and give it a try? Thanks a lot

**Comment by gmaruzz** [comment]
works very well, thanks!
