### ISSUE TITLE
HTTP2 Wireshark reading isse

### ISSUE THREAD

**Issue by giangdh1009** [herlesupreeth/docker_open5gs#98]
I tried to replicated a 5G registration procedure with open5gs project, the setup was successfully, UE could ping to internet. But as i want to investigate SBI interface. I got a lot of TCP retranmission and TCP dup ack in wireshark. Does any one know way to fix it?

![image](https://user-images.githubusercontent.com/100834437/184574899-18869390-522d-4879-84c1-8ca72c2890cb.png)

**Comment by herlesupreeth** [comment]
Check out this one - https://github.com/open5gs/open5gs/discussions/751
